import type { Playbook } from './types';
import { close, opening, EXPERIENCE } from './shared';

export const codingPlaybook: Playbook = {
  subject: 'coding',
  title: 'Coding & AI',
  promise: 'They leave having made something that runs — and knowing they could make it better.',
  intake: {
    experience: EXPERIENCE('Never coded', 'Tried Scratch or a little code', 'Already writes code'),
    interests: [
      { id: 'games', label: 'Games', emoji: '🎮' },
      { id: 'animation', label: 'Animation & stories', emoji: '🎬' },
      { id: 'ai', label: 'AI & robots', emoji: '🤖' },
      { id: 'websites', label: 'Websites', emoji: '🌐' },
      { id: 'apps', label: 'Apps & tools', emoji: '📱' },
    ],
    warmUps: [
      { q: 'A robot is told: forward, forward, turn right, forward. How many steps forward did it take?', options: ['2', '3', '4'], answer: 1, explain: 'Three forwards. The turn is an instruction too, but it is not a step — computers do exactly what the list says.' },
      { q: 'You want a character to jump 10 times. What is the smartest way to tell the computer?', options: ['Write “jump” 10 times', 'Repeat “jump” 10 times', 'Jump once and hope'], answer: 1, explain: 'A loop — “repeat 10 times” — does the work for you. Programmers are lazy in the best way.' },
      { q: 'score = 3, then score = score + 2. What is score now?', options: ['3', '5', '32'], answer: 1, explain: 'The computer takes the old score (3), adds 2, and stores 5. That is how every game keeps score.', bands: ['middle', 'senior', 'adult'] },
      { q: 'Which of these is a bug?', options: ['A game that crashes when you press jump', 'A game that is too easy', 'A game with blue colours'], answer: 0, explain: 'A bug is when the program does something the maker did not mean. Finding them is half of coding.', bands: ['foundation', 'primary'] },
    ],
  },
  opening: opening('Ask what they play or watch on a screen, and what they would make if they could make anything. Write their answer down — it picks the path.'),
  diagnose: [
    {
      ask: 'Have you ever made something on a computer — a game, an animation, a website, anything?',
      listenFor: [
        { answer: '“No” or “only in a school lab once”', means: 'new' },
        { answer: 'Names Scratch, Code.org, a school project, or a little Python', means: 'some' },
        { answer: 'Describes something they built, with a language name and a problem they hit', means: 'strong' },
      ],
    },
    {
      ask: 'If a game character should move when you press the right arrow, what do you think the computer needs to be told?',
      listenFor: [
        { answer: 'Unsure, or “move right”', means: 'new' },
        { answer: '“When the key is pressed, change its position”', means: 'some' },
        { answer: 'Mentions events, x coordinates or a loop checking input', means: 'strong' },
      ],
    },
  ],
  paths: [
    {
      id: 'scratch-catch',
      name: 'Catch game in Scratch',
      forWho: 'Younger children new to code who love games.',
      levels: ['new', 'some'],
      bands: ['foundation', 'primary'],
      interests: ['games'],
      win: 'I made a game where you catch falling apples, and it keeps score.',
      tools: [{ label: 'Scratch', href: 'https://scratch.mit.edu/projects/editor/' }],
      steps: [
        { minutes: 4, title: 'Make it move', do: ['Share your screen, then hand them control or have them open Scratch too.', 'Pick a sprite together (a bowl or a cat). Add “when right arrow key pressed → change x by 10”.', 'Let THEM work out the left arrow.'], check: 'The sprite moves both ways and they did the left arrow themselves.' },
        { minutes: 5, title: 'Something falls', do: ['Add an apple sprite. “When green flag clicked → go to top, forever: change y by -5”.', 'Ask: “What should happen when it reaches the bottom?” — let them guess “go back to the top”.'], check: 'The apple falls and comes back.' },
        { minutes: 5, title: 'Keep score', do: ['Make a variable called score. “If touching bowl → change score by 1, go to top”.', 'Play it. Let them beat their own score once.'], say: 'You just used a variable. That is the same idea every big game uses.', check: 'The score goes up when they catch it.' },
        { minutes: 3, title: 'Make it theirs', do: ['Let them change one thing on their own: speed, costume, a sound when caught.'] },
      ],
      ifStuck: ['Do one block together, then “your turn” for the copy. Never take the mouse back for more than one block.', 'Swap the falling apple for a sprite they chose — motivation fixes more than explanation at this age.'],
      ifFlying: ['Add a “lose” rule: miss 3 apples and the game ends.', 'Make the apple fall from a random x position (pick random).', 'Speed up every 5 points.'],
      showOff: 'The child plays their game while the parent watches, and explains what the score variable does.',
    },
    {
      id: 'scratch-story',
      name: 'An animated story',
      forWho: 'Younger children who like drawing, stories or videos more than games.',
      levels: ['new'],
      bands: ['foundation', 'primary'],
      interests: ['animation'],
      win: 'I made two characters talk and move in a story I wrote.',
      tools: [{ label: 'Scratch', href: 'https://scratch.mit.edu/projects/editor/' }],
      steps: [
        { minutes: 4, title: 'Cast and set', do: ['Choose a backdrop and two characters with them.', 'Ask: “Who are they, and what is the problem?” Write a three-line story together.'] },
        { minutes: 6, title: 'They talk', do: ['“Say … for 2 seconds” on character one; “wait 2 seconds, say …” on character two.', 'Let them write the dialogue.'], check: 'The conversation plays in the right order.' },
        { minutes: 5, title: 'They move', do: ['“Glide to x,y” so one walks to the other. Change costume to make it look like walking.', 'Introduce “broadcast” to change the backdrop when the problem is solved.'] },
        { minutes: 2, title: 'The ending', do: ['Let them choose the ending and build it alone.'] },
      ],
      ifStuck: ['Keep it to two lines of dialogue and one movement. Finished beats ambitious.'],
      ifFlying: ['Add a question: “ask … and wait”, and have the story change with the answer.', 'Add sound effects and music.'],
      showOff: 'They press the green flag for the parent and narrate their story.',
    },
    {
      id: 'teachable-machine',
      name: 'Teach a computer to see',
      forWho: 'Curious children who asked about AI or robots; no coding needed.',
      levels: ['new', 'some'],
      bands: ['primary', 'middle'],
      interests: ['ai'],
      win: 'I trained an AI to tell my thumbs-up from my thumbs-down.',
      tools: [{ label: 'Teachable Machine', href: 'https://teachablemachine.withgoogle.com/train/image' }],
      steps: [
        { minutes: 3, title: 'What is “learning”?', do: ['Ask: “How did you learn what a dog is?” Lead to: by seeing lots of dogs.'], say: 'AI learns the same way — from examples. Today you are the teacher.' },
        { minutes: 6, title: 'Collect examples', do: ['Open an image project. Class 1 “thumbs up”, class 2 “thumbs down”. They hold each pose while you record ~50 images each (or they do, on their device).'] },
        { minutes: 4, title: 'Train and test', do: ['Train. Test live. Then try to FOOL it — a sideways thumb, a different hand.'], check: 'They find at least one way to fool it.' },
        { minutes: 4, title: 'Why it got fooled', do: ['Discuss: it only knows what it was shown. Add better examples and retrain.'], say: 'That is the most important idea in AI: a model is only as good as its examples.' },
      ],
      ifStuck: ['Use two very different things instead of gestures: a cup vs a book.'],
      ifFlying: ['Add a third class (“nothing”). Explain confidence percentages.', 'Talk about where this goes wrong in the real world — faces, fairness.'],
      showOff: 'The parent tries to fool the child’s AI, and the child explains why it was fooled.',
    },
    {
      id: 'python-guess',
      name: 'Number guessing game in Python',
      forWho: 'Older beginners who want “real” code, and like games or puzzles.',
      levels: ['new', 'some'],
      bands: ['middle', 'senior', 'adult'],
      interests: ['games', 'apps'],
      win: 'I wrote a Python game that picks a secret number and tells you higher or lower.',
      tools: [{ label: 'Any online Python editor (e.g. Programiz)', href: 'https://www.programiz.com/python-programming/online-compiler/' }],
      steps: [
        { minutes: 3, title: 'Say hello', do: ['print("Hello, <name>") — then input() their name and print it back.'], check: 'It greets them by the name they typed.' },
        { minutes: 5, title: 'A secret number', do: ['import random; secret = random.randint(1, 20). guess = int(input()). if guess == secret: print("You got it").'], say: 'Two equals signs mean “is it equal?”. One means “store this”. Everybody mixes them up once.' },
        { minutes: 6, title: 'Higher or lower, again and again', do: ['Add elif/else for “higher” and “lower”. Wrap it in while guess != secret.', 'Let them write the “lower” branch alone.'], check: 'The game keeps going until they win.' },
        { minutes: 3, title: 'Count the tries', do: ['Add tries = 0 and tries += 1; print it at the end.'] },
      ],
      ifStuck: ['Skip the loop: one guess, three messages. Add the loop only when that works.', 'Read the error message aloud together — teach that errors are directions, not failure.'],
      ifFlying: ['Limit to 5 tries. Let the player choose the range.', 'Swap roles: the computer guesses YOUR number using halving (binary search).'],
      showOff: 'The parent plays the game; the child explains the while loop.',
    },
    {
      id: 'web-page',
      name: 'Your own web page in twenty minutes',
      forWho: 'Older children and adults who like websites, design or making things look good.',
      levels: ['new', 'some'],
      bands: ['middle', 'senior', 'adult'],
      interests: ['websites', 'apps'],
      win: 'I built a web page about something I love, with a button that does something.',
      tools: [{ label: 'CodePen', href: 'https://codepen.io/pen/' }],
      steps: [
        { minutes: 4, title: 'Structure', do: ['HTML: an h1 with their name, a p about their favourite thing, an img from a URL.'], say: 'HTML is the skeleton. It says what things are, not how they look.' },
        { minutes: 6, title: 'Style', do: ['CSS: background colour, font, centre everything, round the image corners.', 'Let them pick every colour.'], check: 'It looks like theirs, not like the example.' },
        { minutes: 5, title: 'Make it do something', do: ['Add a button. JavaScript: on click, change the background colour or show a hidden fact.'] },
        { minutes: 2, title: 'Their own change', do: ['They add one element alone — a list, a link, a second button.'] },
      ],
      ifStuck: ['Stay in HTML and CSS; skip JavaScript. A beautiful page is still a win.'],
      ifFlying: ['Pick a random colour on each click with Math.random.', 'Make it responsive: what happens on a phone width?'],
      showOff: 'They share the CodePen link with the parent, who opens it on their own phone.',
    },
    {
      id: 'python-chatbot',
      name: 'A chatbot, and what real AI does differently',
      forWho: 'Teenagers and adults who already code a little and are curious about AI.',
      levels: ['some', 'strong'],
      bands: ['senior', 'adult', 'middle'],
      interests: ['ai', 'apps'],
      win: 'I built a chatbot, then saw exactly why it is not intelligent — and what would make it so.',
      tools: [{ label: 'Any online Python editor', href: 'https://www.programiz.com/python-programming/online-compiler/' }],
      steps: [
        { minutes: 5, title: 'A rule-based bot', do: ['A dict of keywords → replies. while True: read input, lowercase, look for keywords, reply or say “I do not understand”.'] },
        { minutes: 5, title: 'Break it', do: ['Have them ask it things it cannot handle: typos, sarcasm, a question with two keywords.'], say: 'It matches words. It does not understand anything.' },
        { minutes: 5, title: 'How real AI differs', do: ['Explain, with a whiteboard: next-word prediction, learning from examples instead of rules, why that fixes typos and creates new problems (confident nonsense).'] },
        { minutes: 3, title: 'Improve it their way', do: ['They add fuzzy matching (in / startswith) or a memory of their name.'] },
      ],
      ifStuck: ['Use if/elif instead of a dict. The idea is the same.'],
      ifFlying: ['Score replies by counting matching keywords. Discuss: that is a tiny step toward how search and early AI worked.', 'Talk through tokens and probabilities with a toy example.'],
      showOff: 'The parent chats with the bot and tries to break it; the child explains why it breaks.',
    },
    {
      id: 'debug-challenge',
      name: 'The debug challenge',
      forWho: 'Anyone who already writes code confidently and needs to be stretched, not taught basics.',
      levels: ['strong'],
      bands: ['middle', 'senior', 'adult'],
      interests: ['games', 'apps', 'websites', 'ai'],
      win: 'I found and fixed three bugs in code I had never seen, then added a feature.',
      steps: [
        { minutes: 3, title: 'Show what they know', do: ['Ask them to show or describe the best thing they have made, and the hardest bug they fixed.'] },
        { minutes: 8, title: 'Three planted bugs', do: ['Paste a 25-line program (a to-do list or tic-tac-toe check) with three bugs: an off-by-one, a wrong comparison, a variable shadowed or never updated.', 'They find them by reading and running — you only ask questions.'], check: 'They explain each bug in a sentence before fixing it.' },
        { minutes: 6, title: 'Extend it', do: ['A feature request: undo, a win on diagonals, saving to a file. Discuss design before typing.'] },
      ],
      ifStuck: ['Give the line range. Then the kind of bug. Never the answer.'],
      ifFlying: ['Ask for tests: what inputs would catch each bug next time?', 'Talk complexity: what happens with a million items?'],
      showOff: 'They walk the parent through one bug: what it was, how they found it, and the fix.',
    },
  ],
  close: close('The child runs what they built while the parent watches — no help from you unless it crashes.'),
  parentTalk: {
    new: 'Your child had never coded and built a working program in thirty minutes — they did the key step themselves. The course starts here and gets them making full games and projects on their own.',
    some: 'They already have the basics and picked up new ideas fast — loops and variables made sense quickly. The course would move them from following along to designing their own projects.',
    strong: 'They are genuinely ahead: they debugged code they had never seen. They need projects that stretch them, not the basics — the course would put them on advanced, real-world builds.',
  },
  avoid: [
    'Typing for the child. Every line you type is a line they did not learn.',
    'Explaining for more than two minutes at a time.',
    'Leaving without something that runs. Cut scope before you run out of time.',
  ],
};
