import type { Playbook } from './types';
import { close, opening, EXPERIENCE } from './shared';

const DESMOS = { label: 'Desmos graphing calculator', href: 'https://www.desmos.com/calculator' };

export const mathsPlaybook: Playbook = {
  subject: 'mathematics',
  title: 'Mathematics',
  promise: 'They leave having solved something they thought they could not — and knowing why the method works.',
  intake: {
    experience: EXPERIENCE('Finds maths hard right now', 'Doing fine at school', 'Top of the class, wants more'),
    interests: [
      { id: 'puzzles', label: 'Puzzles & patterns', emoji: '🧩' },
      { id: 'money', label: 'Money & shopping', emoji: '💰' },
      { id: 'shapes', label: 'Shapes & drawing', emoji: '📐' },
      { id: 'sports', label: 'Sports & scores', emoji: '⚽' },
      { id: 'space', label: 'Space & huge numbers', emoji: '🚀' },
    ],
    warmUps: [
      { q: 'What comes next? 2, 4, 8, 16, …', options: ['18', '24', '32'], answer: 2, explain: 'Each number doubles. Spotting the rule, not the next number, is the real skill.' },
      { q: 'A pencil costs ₹7. You pay with ₹20. How much change?', options: ['₹13', '₹17', '₹27'], answer: 0, explain: 'Count up from 7: 3 makes 10, and 10 more makes 20 — so 13.', bands: ['foundation', 'primary'] },
      { q: 'Which is bigger: 2/3 or 3/5?', options: ['2/3', '3/5', 'They are equal'], answer: 0, explain: '2/3 is about 0.67 and 3/5 is 0.6. Or: 10/15 against 9/15.', bands: ['primary', 'middle'] },
      { q: 'If 3x + 2 = 14, what is x?', options: ['4', '5', '12'], answer: 0, explain: 'Take 2 from both sides: 3x = 12. Share into 3: x = 4.', bands: ['middle', 'senior'] },
      { q: 'A square has a perimeter of 20 cm. What is its area?', options: ['20 cm²', '25 cm²', '100 cm²'], answer: 1, explain: 'Each side is 20 ÷ 4 = 5 cm, so the area is 5 × 5 = 25 cm².' },
    ],
  },
  opening: opening('Ask: “What is one thing in maths that makes sense, and one that does not?” The second answer is gold — it tells you what school has not fixed.'),
  diagnose: [
    {
      ask: 'Give a problem one step below their grade, then one at their grade. Ask them to think aloud.',
      listenFor: [
        { answer: 'Stuck on the easier one, or guesses without a method', means: 'new' },
        { answer: 'Solves both with the school method but cannot say why it works', means: 'some' },
        { answer: 'Solves both, explains why, maybe finds a shortcut', means: 'strong' },
      ],
    },
    {
      ask: '“How would you check your answer is right?”',
      listenFor: [
        { answer: '“Ask the teacher” or silence', means: 'new' },
        { answer: '“Do it again”', means: 'some' },
        { answer: 'Substitutes back, estimates, or uses a different method', means: 'strong' },
      ],
    },
  ],
  paths: [
    {
      id: 'shop',
      name: 'Run the shop',
      forWho: 'Younger children building number sense, especially if they like money.',
      levels: ['new', 'some'],
      bands: ['foundation', 'primary'],
      interests: ['money'],
      win: 'I ran a shop and worked out every customer’s change in my head.',
      steps: [
        { minutes: 4, title: 'Price the shop', do: ['Draw a shop on the whiteboard with them: 5 items they choose. They set prices under ₹50.'] },
        { minutes: 7, title: 'Customers arrive', do: ['You are the customer: buy 2 items, pay with a note. They add and give change.', 'Teach counting up for change (7 → 10 → 20) instead of column subtraction.'], check: 'They use counting up without being reminded.' },
        { minutes: 5, title: 'A sale', do: ['“Everything is half price” or “buy 2 get 1 free” — which is the better deal for 3 items?'] },
      ],
      ifStuck: ['Prices under ₹20, round numbers, and use drawn coins.'],
      ifFlying: ['Percentages: 10% off, 25% off. Which is better, 25% off or ₹10 off?', 'A budget: spend exactly ₹100 on at least 3 items.'],
      showOff: 'The parent buys something and the child gives change instantly, explaining how.',
    },
    {
      id: 'fractions',
      name: 'Fractions you can see',
      forWho: 'Children who find fractions confusing, and visual learners.',
      levels: ['new', 'some'],
      bands: ['primary', 'middle'],
      interests: ['shapes'],
      win: 'I can show why 2/3 is bigger than 3/5 with a drawing, not just a rule.',
      steps: [
        { minutes: 4, title: 'Fraction bars', do: ['Draw a bar, cut into 3, shade 2. Another bar cut into 5, shade 3. “Which has more shaded?”'] },
        { minutes: 6, title: 'Same-size pieces', do: ['Cut both bars into 15ths. Discover equivalent fractions (10/15 vs 9/15) by drawing, then name the rule.'], say: 'You did not memorise a rule — you found it. That is why you will not forget it.' },
        { minutes: 6, title: 'Pizza problems', do: ['“You eat 1/4, your brother eats 1/3. Who ate more, and how much is left?” Draw, then calculate.'], check: 'They draw before calculating without being told.' },
      ],
      ifStuck: ['Stay with halves, quarters and thirds, using drawn pizzas.'],
      ifFlying: ['Fractions of amounts: 3/4 of 60. Fraction ↔ decimal ↔ percentage.', 'Why dividing by 1/2 doubles.'],
      showOff: 'The child draws the proof for the parent that 2/3 > 3/5.',
    },
    {
      id: 'patterns',
      name: 'Pattern detective',
      forWho: 'Children who like puzzles and are ready to move from numbers to rules.',
      levels: ['some', 'strong'],
      bands: ['primary', 'middle'],
      interests: ['puzzles', 'space'],
      win: 'I found the rule for a pattern and predicted the 100th term without counting.',
      steps: [
        { minutes: 5, title: 'Matchstick squares', do: ['1 square uses 4 sticks, 2 in a row use 7, 3 use 10. Draw them. “How many for 10 squares?”'] },
        { minutes: 6, title: 'The rule', do: ['Table: squares → sticks. Find “+3 each time” then “3n + 1”. Ask why the +1.'], check: 'They explain the +1 from the picture (the first stick).' },
        { minutes: 5, title: 'The 100th', do: ['Predict 100 squares. Then a new pattern they must crack alone (triangles: 2n + 1).'] },
      ],
      ifStuck: ['Stay with the table and “what do you add each time?”. Skip the algebra.'],
      ifFlying: ['A non-linear pattern: square numbers, triangular numbers.', 'Work backwards: 301 sticks — how many squares?'],
      showOff: 'The parent picks any number of squares and the child answers instantly with the rule.',
    },
    {
      id: 'balance',
      name: 'Balance-scale algebra',
      forWho: 'Children meeting equations who think “x” is scary.',
      levels: ['new', 'some'],
      bands: ['middle'],
      interests: ['puzzles'],
      win: 'I solved two-step equations by keeping a scale balanced.',
      steps: [
        { minutes: 4, title: 'Mystery bags', do: ['Draw a scale: a bag + 3 blocks on one side, 7 blocks on the other. “How many in the bag?”'] },
        { minutes: 6, title: 'Same on both sides', do: ['Remove 3 from both sides. Write it as x + 3 = 7 → x = 4. Then 2 bags + 1 = 9.'], say: 'Algebra is just keeping the scale balanced.', check: 'They say “do the same to both sides” in their own words.' },
        { minutes: 6, title: 'Their turn', do: ['Four equations of rising difficulty, including one with x on both sides.'] },
      ],
      ifStuck: ['Only one-step equations, always with the picture.'],
      ifFlying: ['Negative numbers and fractions in equations. Make up a word problem that gives 3x − 5 = 16.'],
      showOff: 'The child writes an equation for the parent to solve — and checks the parent’s answer.',
    },
    {
      id: 'sports-stats',
      name: 'Who is the better player?',
      forWho: 'Children who love sport and are ready for averages and data.',
      levels: ['some', 'strong'],
      bands: ['middle', 'senior'],
      interests: ['sports'],
      win: 'I used data to argue who the better batter is — and showed how averages can lie.',
      steps: [
        { minutes: 4, title: 'Two players', do: ['Give scores for two batters over 7 innings (one consistent, one with a single huge score).'] },
        { minutes: 6, title: 'Mean, median, range', do: ['Calculate all three. Mean says player B, median says player A. “Who would you pick for a final?”'] },
        { minutes: 6, title: 'Make the case', do: ['They argue for one player using two statistics. You argue back.'], check: 'They use a statistic to answer your objection.' },
      ],
      ifStuck: ['Only the mean, with 4 scores each.'],
      ifFlying: ['Strike rate vs average. Standard deviation as “how spread out”.', 'Find a misleading graph and fix it.'],
      showOff: 'The child presents their pick to the parent with the numbers.',
    },
    {
      id: 'graphs',
      name: 'Graphs that tell a story',
      forWho: 'Older students who can do the algebra but do not see what it means.',
      levels: ['some', 'strong'],
      bands: ['senior'],
      interests: ['space', 'puzzles', 'sports'],
      win: 'I can look at an equation and sketch what it does before a computer draws it.',
      tools: [DESMOS],
      steps: [
        { minutes: 5, title: 'Sliders', do: ['Desmos: y = mx + c with sliders. They predict what m and c do before moving them.'] },
        { minutes: 6, title: 'The ball', do: ['A ball thrown up: y = −5t² + 20t. When is it highest? When does it land? Sketch first, then check.'], check: 'Their sketch matches the shape before Desmos shows it.' },
        { minutes: 5, title: 'Match the story', do: ['Three graphs, three stories (a car stopping, a phone battery, a savings account). They match and justify.'] },
      ],
      ifStuck: ['Stay with straight lines and gradients as “steepness”.'],
      ifFlying: ['Complete the square to find the vertex exactly.', 'Exponential vs quadratic: which grows faster, and when does it overtake?'],
      showOff: 'The parent names a shape; the child writes an equation that makes it.',
    },
  ],
  close: close('The child solves one final problem aloud for the parent, explaining each step.'),
  parentTalk: {
    new: 'Maths has been a struggle, but today they solved problems they could not do at the start — once the idea was drawn, it clicked. The course fills the gaps from the ground up so school stops feeling like catching up.',
    some: 'They are doing the school methods correctly and understood WHY they work today, which is what holds up in harder grades. The course builds that understanding ahead of school.',
    strong: 'They are ahead — they found rules and shortcuts on their own. They need problems that stretch them, not more practice of what they know: olympiad-style thinking and topics beyond their grade.',
  },
  avoid: [
    'Showing a method before they have tried anything.',
    'Saying “it is easy” — if it is not easy for them, you have just told them they are slow.',
    'Correcting every small slip. Let them find one of their own mistakes.',
  ],
};
