import type { Passage } from './types';

/**
 * SARIRO — passages sized for younger readers
 * ============================================================================
 * The main library is a minute each, about a hundred and fifty words — right
 * for Grade 7 up, and a wall of text for a six-year-old. These are the same
 * idea at the right size: Grades 1–3 read thirty to fifty words, Grades 4–6
 * sixty to ninety. Written to be said: no digits, simple punctuation, a full
 * stop wherever a young reader needs a breath.
 */

export const FOUNDATION_PASSAGES: readonly Passage[] = [
  { id: 'f-frog', title: 'The singing frog', topic: 'Story', text: 'Once there was a small green frog who wanted to sing. Every morning he practised by the pond. At first he croaked. The ducks laughed. But he kept going, and one day he sang.' },
  { id: 'f-kite', title: 'The red kite', topic: 'Story', text: 'Ria made a red kite from paper and string. The wind was strong. The kite flew up, up, up, over the trees. Ria held on tight and laughed. It was the best day of her summer.' },
  { id: 'f-lost-shoe', title: 'The lost shoe', topic: 'Story', text: 'Arjun could not find his left shoe. He looked under the bed. He looked in the garden. Then he saw the puppy, wagging its tail, with a shoe in its mouth. Arjun laughed and gave the puppy a hug.' },
  { id: 'f-rain', title: 'Where rain comes from', topic: 'Science & nature', text: 'The sun warms the water in lakes and seas. The water rises up into the sky as tiny drops. The drops join together to make clouds. When the clouds get heavy, the water falls down as rain.' },
  { id: 'f-bees', title: 'Busy bees', topic: 'Science & nature', text: 'Bees fly from flower to flower all day long. They drink sweet nectar and carry yellow pollen on their legs. This helps new flowers and fruits to grow. Without bees, we would have much less food.' },
  { id: 'f-moon', title: 'The moon at night', topic: 'Science & nature', text: 'The moon does not make its own light. It shines because the sun lights it up. Some nights it looks round and bright. Some nights it looks thin, like a smile. It is the same moon every time.' },
  { id: 'f-plant', title: 'How a seed grows', topic: 'Science & nature', text: 'Put a seed in soil and give it water. Wait a few days. A tiny green shoot pushes up towards the light. Roots grow down to drink. Soon, with sun and water, your seed becomes a plant.' },
  { id: 'f-breakfast', title: 'My breakfast', topic: 'Everyday life', text: 'Every morning I eat breakfast with my family. Sometimes we have idli. Sometimes we have toast and fruit. My favourite is warm milk with a banana. A good breakfast gives me energy for school.' },
  { id: 'f-bus', title: 'On the school bus', topic: 'Everyday life', text: 'The yellow school bus comes at eight o\'clock. I sit next to my best friend. We look out of the window and count red cars. By the time we reach school, we have counted eleven.' },
  { id: 'f-helping', title: 'Helping at home', topic: 'Everyday life', text: 'I like helping at home. I water the plants, put my toys away and set the table for dinner. My grandmother says thank you, and that makes me feel very proud.' },
  { id: 'f-park', title: 'A day at the park', topic: 'Everyday life', text: 'At the park there are swings, slides and a big tree to sit under. I run on the grass and chase the pigeons. When I get tired, I eat an orange in the shade with my dad.' },
  { id: 'f-elephant', title: 'The kind elephant', topic: 'Story', text: 'A little bird fell from its nest. A big grey elephant saw it. Very gently, the elephant lifted the bird with its trunk and put it back in the nest. The mother bird sang a thank you song.' },
  { id: 'f-diwali', title: 'Festival of lights', topic: 'India & the world', text: 'At Diwali, we light small lamps all around our home. We make pretty patterns with coloured powder. We share sweets with our neighbours. The whole street glows with light and happy faces.' },
  { id: 'f-ocean', title: 'Under the sea', topic: 'Science & nature', text: 'Deep under the sea there are colourful fish, wiggly octopus and slow turtles. Some fish glow in the dark. The ocean is so big that people are still finding new animals there today.' },
  { id: 'f-brave', title: 'Being brave', topic: 'Big ideas', text: 'Being brave does not mean you are not scared. It means you try anyway. When I read out loud in class, my tummy feels funny. I take a big breath, and I start. That is brave.' },
  { id: 'f-friend', title: 'A good friend', topic: 'Big ideas', text: 'A good friend shares, listens and helps you when you fall down. A good friend says sorry when they make a mistake. I want to be a good friend to everyone in my class.' },
];

export const PRIMARY_PASSAGES: readonly Passage[] = [
  { id: 'p-map', title: 'The map under the bed', topic: 'Story', text: 'Mia found a folded map under her bed. It showed her garden, with a big red cross next to the mango tree. She grabbed a spoon and started to dig. After ten minutes, the spoon hit something hard. It was a small tin box. Inside was a note from her grandmother: every adventure starts with curiosity.' },
  { id: 'p-robot', title: 'The robot who could not dance', topic: 'Story', text: 'Bolt was a robot built to sweep floors. Every night, when the school was empty, he watched a video of children dancing. He tried to copy them, but his wheels spun and he fell over. Night after night he practised. On the last day of term, the children came back early and found Bolt doing a perfect spin.' },
  { id: 'p-volcano', title: 'How volcanoes work', topic: 'Science & nature', text: 'Deep inside the Earth, it is so hot that rock melts into a thick liquid called magma. When pressure builds up, the magma pushes towards the surface through cracks. When it bursts out, we call it lava. Over thousands of years, cooled lava can build a mountain, and even create new islands in the ocean.' },
  { id: 'p-honeybee', title: 'The dance of the honeybee', topic: 'Science & nature', text: 'When a honeybee finds a field full of flowers, it flies back to the hive and dances. The dance is a message. The direction of the dance shows which way to fly, and how long the bee wiggles shows how far away the flowers are. Other bees watch, and then they fly straight to the food.' },
  { id: 'p-space', title: 'Living in space', topic: 'Science & nature', text: 'Astronauts on the space station float all the time, because they are falling around the Earth. They strap themselves into sleeping bags so they do not drift away at night. Water forms floating balls, so they drink from pouches. They also exercise for two hours a day, because muscles get weak when you do not need them to stand.' },
  { id: 'p-kalam', title: 'The boy who sold newspapers', topic: 'History & people', text: 'As a boy in Rameswaram, Abdul Kalam sold newspapers to help his family. He loved watching birds fly and wondered how they stayed in the air. That question stayed with him. He studied hard, became a scientist, helped India build rockets, and later became the President of India. He always said: dream, dream, dream.' },
  { id: 'p-wright', title: 'The first flight', topic: 'History & people', text: 'Two brothers, Orville and Wilbur Wright, ran a bicycle shop. They were fascinated by the idea of flying. They built gliders, crashed them, fixed them and tried again. In the winter of nineteen hundred and three, their plane stayed in the air for twelve seconds. It does not sound like much, but it changed the world.' },
  { id: 'p-recycling', title: 'Why recycling matters', topic: 'Everyday life', text: 'Every plastic bottle you throw away can last for hundreds of years. When we recycle, old bottles are melted down and made into new things, like benches, bags and even clothes. Recycling saves energy and keeps rubbish out of rivers and oceans. One family recycling every week can stop a mountain of waste from growing.' },
  { id: 'p-exam', title: 'The night before the test', topic: 'Everyday life', text: 'It was the night before the maths test, and Kabir could not sleep. He kept thinking about fractions. Then he remembered what his teacher said: you have practised, now rest. He took three slow breaths, thought about his favourite football match, and fell asleep. In the morning, the questions looked much friendlier.' },
  { id: 'p-team', title: 'The last-minute goal', topic: 'Everyday life', text: 'Our team was losing by one goal with two minutes left. Everyone was tired, but our captain shouted, one more push! Meera passed the ball to Sam, who dribbled past two defenders and kicked. The ball flew into the corner of the net. We did not win the match, but that draw felt like a victory.' },
  { id: 'p-monsoon', title: 'When the monsoon arrives', topic: 'India & the world', text: 'In India, the monsoon rains usually arrive in June. After months of heat, dark clouds roll in and the first drops fall on dry ground. The smell of wet earth fills the air. Farmers celebrate, because the rains fill rivers and help crops grow. Children splash in puddles, and the whole country breathes a sigh of relief.' },
  { id: 'p-penguins', title: 'Penguin parents', topic: 'India & the world', text: 'In Antarctica, emperor penguin fathers look after their eggs through the coldest winter on Earth. They balance the egg on their feet and cover it with a warm fold of skin. For two months they huddle together against freezing winds, without eating. When the chick hatches, the mother returns with food.' },
  { id: 'p-mistakes', title: 'Mistakes are teachers', topic: 'Big ideas', text: 'Nobody learns to ride a bicycle without falling off. Every fall teaches your body something about balance. Mistakes at school work the same way. When you get a question wrong and find out why, your brain builds a stronger path for next time. The only real mistake is being too afraid to try.' },
  { id: 'p-kindness', title: 'Small kindness, big difference', topic: 'Big ideas', text: 'On her first day at a new school, Zara sat alone at lunch. A girl named Tara came over and asked if she wanted to share her chapatis. It took only a minute, but Zara never forgot it. Years later, they were still best friends. A small act of kindness can change someone\'s whole day, or even their whole year.' },
  { id: 'p-trees', title: 'The tree that cleans the air', topic: 'Science & nature', text: 'Trees are like giant air cleaners. Their leaves take in carbon dioxide, a gas we breathe out, and give back oxygen, which we need to live. One big tree can give enough oxygen for two people every day. Trees also give shade, homes for birds and cool air on hot afternoons.' },
  { id: 'p-library', title: 'The secret library', topic: 'Story', text: 'Behind a dusty shelf in the school library, Dev found a small wooden door. He pushed it open and saw a room full of glowing books. When he opened one, he could hear the ocean. Another smelled of pine forests. A sign on the wall said: every book is a door. Choose one and step through.' },
];

/**
 * UG, PG & professionals: passages from working life — updates, pitches and
 * talks — for reading aloud with the pace and pauses a room of colleagues needs.
 */
export const PROFESSIONAL_PASSAGES: readonly Passage[] = [
  { id: 'w-update', title: 'A project update', topic: 'Everyday life', text: 'Good morning, everyone. Three quick things. First, the migration is on schedule, and testing is nearly complete. Second, we found a performance issue on the reporting page. It affects about one in ten users, and we have a fix ready for Thursday. Third, I need a decision today on whether we delay the launch by one week to include that fix, or ship now and patch it later. My recommendation is to delay. A one-week delay costs us less than a poor first impression with our largest client.' },
  { id: 'w-pitch', title: 'A sixty-second pitch', topic: 'Big ideas', text: 'Small clinics lose hours every day chasing missed appointments. Patients forget, staff call them one by one, and empty slots cost money that these clinics cannot spare. Our tool sends a friendly reminder on the patient\'s preferred app, lets them reschedule in one tap, and fills the gap from a waiting list. In our pilot with twelve clinics, missed appointments fell by nearly half in two months. We are raising funds to reach two hundred clinics this year, and we would like you to be part of that.' },
  { id: 'w-feedback', title: 'Giving feedback', topic: 'Everyday life', text: 'I wanted to share some feedback on yesterday\'s client presentation. When you opened with the customer story, the whole room leaned in. That was excellent. One thing to try next time: when the client asked about cost, you went into a lot of technical detail before giving the number. Lead with the number, then explain. Clients relax when they hear the answer first. Overall, it was a strong session, and I would be happy for you to lead the next one.' },
  { id: 'w-bad-news', title: 'Delivering bad news', topic: 'Everyday life', text: 'I want to be direct with you. We will not meet the deadline we agreed last month. The main reason is that the data we needed arrived three weeks late, and I should have raised that risk earlier. Here is what we can do. We can deliver the core analysis by the original date, and the full report two weeks later. I am sorry for the disruption, and I will send weekly updates until it is done.' },
  { id: 'w-research', title: 'A research finding', topic: 'Science & nature', text: 'Our study followed four hundred first-year students across one academic year. We expected that students who studied longer hours would perform better. They did not. The strongest predictor of results was not hours studied, but how often students tested themselves on the material. Students who used short self-tests every week outperformed those who reread their notes, even when they studied for less time. This suggests that how you study matters far more than how long.' },
  { id: 'w-leadership', title: 'A leader\'s message', topic: 'Big ideas', text: 'This has been a difficult quarter, and I know many of you have worked long hours. I want to thank you properly, not with a generic email, but by being honest about where we stand. We missed our growth target. We did not miss it because of effort. We missed it because we spread ourselves across too many projects. So next quarter, we are doing fewer things, and doing them well. That is a decision I own, and I believe it is the right one.' },
  { id: 'w-interview', title: 'An interview answer', topic: 'Everyday life', text: 'The toughest challenge in my last role was a product launch where two teams disagreed on priorities. Design wanted more time for testing. Sales had already promised a date to customers. I set up a short meeting with both leads and asked each to describe the worst outcome they were trying to avoid. It turned out both feared losing customer trust. We agreed to launch a smaller version on time and test the rest with a pilot group. The launch went smoothly, and both teams used that approach again.' },
  { id: 'w-meeting-open', title: 'Opening a meeting', topic: 'Everyday life', text: 'Thank you for making time today. We have thirty minutes and one decision to make: whether to renew our contract with the current vendor or move to the new one. I will take ten minutes to walk through the comparison, then we will discuss. By the end of this meeting, I would like a clear yes or no, and a named owner for the next step. Let us start with cost, because that is where the two options differ the most.' },
  { id: 'w-viva', title: 'Defending a method', topic: 'Science & nature', text: 'I chose interviews rather than a survey for one reason. The existing research could tell us how many small businesses struggled with digital payments, but not why. A survey would have confirmed the scale of the problem without explaining it. The trade-off is that twenty-four interviews cannot represent every business in the region. I address that limitation in chapter five, and I suggest a follow-up survey as the natural next step for this research.' },
  { id: 'w-networking', title: 'Introducing yourself', topic: 'Everyday life', text: 'Hi, I am Ananya. I work on supply chain analytics at a logistics company, which mostly means helping trucks carry fuller loads and drive fewer empty kilometres. Lately I have been looking at how smaller warehouses can use the same tools without large budgets. I noticed your talk mentioned rural distribution, and I would love to hear what surprised you most in that work. If it is useful, I am also happy to share what we learned from a pilot with three small warehouses last year.' },
  { id: 'w-conference', title: 'A conference talk opening', topic: 'Big ideas', text: 'Five years ago, our city installed more than a thousand air quality sensors. The data was public, free and updated every minute. And almost nobody used it. Not because people did not care about the air they breathe, but because nobody had turned the numbers into a decision anyone could make. Today I want to show you what happened when we stopped publishing data and started publishing answers. And I want to leave you with one question to take back to your own work.' },
  { id: 'w-negotiation', title: 'A careful negotiation', topic: 'Everyday life', text: 'I understand the budget is tight this year, and I want to find something that works for both of us. I am not able to reduce the price by twenty percent without cutting the support hours your team relies on. What I can do is spread the payment across four quarters, and include training for your new staff at no extra cost. That keeps the service your team values and makes the cost easier to plan for. Would that approach work for you?' },
];
