import type { Story } from './types';

/** Coding & AI, Grades 1–12 and grown-ups (13): one story each, from unplugged sequencing to shipping an AI tool. */
export const CODING_STORIES: Story[] = [
  {
    subject: 'coding', grade: 1, emoji: '🐶', title: 'Robo-Pup', role: 'Robo-Pup’s programmer',
    hook: 'Robo-Pup is a robot puppy who does EXACTLY what you tell him — no more, no less. He is hungry, and his bowl is across the room. Can you program him to get there?',
    mission: 'Give Robo-Pup instructions that get him to his dinner.',
    chapters: [
      { minutes: 5, title: 'Step by step', scene: 'Robo-Pup is 3 squares from his bowl, facing it.', task: 'Give him the instructions to reach the bowl, one step at a time.', lookFor: '“Forward, forward, forward” — exact, in order.', nudge: 'If you say “go to the bowl”, he doesn’t understand. What is ONE step?' },
      { minutes: 6, title: 'The turn', scene: 'Now the bowl is 2 squares forward, then 2 squares to his right.', task: 'Write the instructions with arrows. Where must he turn?', lookFor: 'Forward, forward, turn right, forward, forward.', nudge: 'Walk it yourself! When do you need to turn?' },
      { minutes: 6, title: 'The bug', scene: 'A helper wrote: forward, turn right, forward, forward. Robo-Pup bumped into the sofa!', task: 'Find the mistake and fix the program.', lookFor: 'The turn came too early — move “turn right” after the second forward.', nudge: 'Follow the instructions with your finger on the grid. Where does it go wrong?' },
    ],
    stretch: 'Robo-Pup has to walk forward 8 times. Is there a shorter way to write it? (“Repeat 8 times: forward.”)',
    cliffhanger: 'Robo-Pup has learned to dance — but only if we teach him the moves in a loop. Next class we make him dance to music on the computer.',
    win: 'I programmed a robot puppy and fixed a bug in his program.',
    skill: 'Sequencing, directions and debugging — the heart of all programming.',
  },
  {
    subject: 'coding', grade: 2, emoji: '🐭', title: 'The Maze Mouse', role: 'the maze designer',
    hook: 'Mo the mouse is trapped in a maze, and the cheese is at the other end. The maze changes every day, so Mo needs a program — not a map.',
    mission: 'Program Mo through the maze using loops.',
    chapters: [
      { minutes: 5, title: 'Straight corridors', scene: 'The first corridor is 6 squares long.', task: 'Write the program the long way, then the short way with “repeat”.', lookFor: 'Repeat 6: move forward — the child sees the loop saves writing.', nudge: 'Are you saying the same thing again and again? Say it once and how many times.' },
      { minutes: 6, title: 'Stairs', scene: 'The next part is like stairs: forward, turn left, forward, turn right — again and again, 4 times.', task: 'Write it as a loop.', lookFor: 'Repeat 4: forward, turn left, forward, turn right.', nudge: 'Which moves repeat together as a pattern?' },
      { minutes: 6, title: 'The trap', scene: 'Mo keeps crashing into a wall at the end of a corridor.', task: 'Debug the loop — how many times should it really repeat?', lookFor: 'Count the squares — off by one (e.g. repeat 5 instead of 6).', nudge: 'Count the squares carefully. Does Mo take one step too many?' },
    ],
    stretch: 'Design your own maze and write the program for a friend to test.',
    cliffhanger: 'The cheese has been moved and now there are two paths — Mo must choose! Next class we teach Mo to make decisions with “if”.',
    win: 'I programmed a mouse through a maze with loops and fixed a bug.',
    skill: 'Loops (repeat) and debugging.',
  },
  {
    subject: 'coding', grade: 3, emoji: '🎉', title: 'The Dance Party', role: 'the animation director',
    hook: 'The school’s virtual dance party is tonight — and the dancers are frozen! As animation director, you must bring them to life before the music starts.',
    mission: 'Animate a dance with events, loops and timing (block coding).',
    chapters: [
      { minutes: 5, title: 'When the flag is clicked', scene: 'Nothing happens when the party starts.', task: 'Choose the event block that starts the dance, and add three moves.', lookFor: '“When green flag clicked” followed by move/turn/costume blocks.', nudge: 'How does the program know WHEN to start?' },
      { minutes: 6, title: 'Dance forever', scene: 'The dancers stop after three moves and stand still.', task: 'Make them dance for the whole song.', lookFor: 'A “forever” (or repeat) loop around the dance moves, with a short wait so we can see each move.', nudge: 'Which block keeps doing something again and again?' },
      { minutes: 6, title: 'Press a key', scene: 'The DJ wants the lights to flash when you press the space bar.', task: 'Add a second event that changes the colour when space is pressed.', lookFor: '“When space key pressed” → change colour effect. Two events running together.', nudge: 'Is there an event block for pressing a key?' },
    ],
    stretch: 'Make two dancers do a mirror dance — one turns right while the other turns left.',
    cliffhanger: 'The party guests want to play a game on the dance floor, with a score! Next class we build a game with variables.',
    win: 'I animated a dance party with events and loops.',
    skill: 'Events, loops and timing in block-based code.',
  },
  {
    subject: 'coding', grade: 4, emoji: '❓', title: 'The Quiz Show', role: 'the quiz-show programmer',
    hook: 'The quiz show “Brain Blast” airs this weekend, but the scoreboard is broken and the questions do not check answers. The producer needs a programmer in the studio.',
    mission: 'Build a quiz that asks, checks answers and keeps score.',
    chapters: [
      { minutes: 5, title: 'Ask a question', scene: 'The quiz needs to ask: “What is 7 × 8?”', task: 'Use an “ask” block and store the answer.', lookFor: 'Ask … and wait; the answer is saved in “answer”.', nudge: 'Which block lets the computer ask the player something?' },
      { minutes: 6, title: 'Right or wrong', scene: 'The quiz says “Correct!” to every answer, even “banana”.', task: 'Add an if–else to check if the answer is 56.', lookFor: 'If answer = 56 then say “Correct!” else say “Try again”.', nudge: 'The computer has to COMPARE the answer with 56. What block compares?' },
      { minutes: 6, title: 'Keep score', scene: 'The producer wants the score to go up by 10 for each right answer.', task: 'Create a “score” variable, set it to 0 at the start and change it when correct.', lookFor: 'Set score to 0 at start; change score by 10 inside the “if”.', nudge: 'Where should the score start? Where should it grow?' },
    ],
    stretch: 'Add a timer: 10 seconds per question, and a “Game over” when time runs out.',
    cliffhanger: 'The contestants have figured out the questions are always the same! Next class we make the quiz pick random questions from a list.',
    win: 'I built a quiz that checks answers and keeps score.',
    skill: 'Input, if–else conditions and variables.',
  },
  {
    subject: 'coding', grade: 5, emoji: '🌡️', title: 'The Weather Robot', role: 'the robot’s programmer',
    hook: 'Your school has a new robot at the gate, WeatherBot, who is supposed to tell students what to wear. Right now it tells everyone to wear a raincoat — even on sunny days.',
    mission: 'Program WeatherBot to give the right advice for any weather.',
    chapters: [
      { minutes: 5, title: 'Hot or cold', scene: 'WeatherBot reads the temperature every morning.', task: 'Write the rule: if it is above 30°C say “Stay cool!”, otherwise say “Have a good day!”', lookFor: 'if temperature > 30 → “Stay cool!” else → “Have a good day!”', nudge: 'What is the question the robot asks itself? What are the two answers?' },
      { minutes: 6, title: 'More than two', scene: 'Now it must handle cold (below 15°C), mild and hot.', task: 'Write the rules for three cases.', lookFor: 'if > 30 … else if < 15 … else … (elif / else if).', nudge: 'Check one case, then the next, then everything else.' },
      { minutes: 6, title: 'Two things at once', scene: 'If it is hot AND raining, students need both an umbrella and water.', task: 'Write one condition that checks both.', lookFor: 'if temperature > 30 and raining → “Umbrella and water!” (AND).', nudge: 'How do you ask two questions in one “if”?' },
    ],
    stretch: 'Keep a list of the week’s temperatures and have the robot say the hottest day.',
    cliffhanger: 'WeatherBot has been so popular that parents want a chat with it! Next class we give WeatherBot a voice and teach it to answer questions.',
    win: 'I programmed a weather robot with if, else-if and AND.',
    skill: 'Conditions: if, else if, else, comparison and AND/OR.',
  },
  {
    subject: 'coding', grade: 6, emoji: '💬', title: 'Build a Chatbot', role: 'the chatbot developer',
    hook: 'The school library wants a chatbot to help students find books. The librarian has one requirement: it must feel friendly. You are the developer.',
    mission: 'Build a chatbot that understands questions and replies helpfully.',
    chapters: [
      { minutes: 5, title: 'Hello!', scene: 'A student types “hi” and the bot does nothing.', task: 'Make the bot greet anyone who says hi, hello or hey.', lookFor: 'Check the message against a list of greetings, or with OR conditions.', nudge: 'What words do people use to say hello? How can the bot check for any of them?' },
      { minutes: 6, title: 'Capital problems', scene: 'The bot answers “hello” but not “HELLO”.', task: 'Fix it so capitals don’t matter.', lookFor: 'Convert the message to lower case before checking.', nudge: 'Can you turn the message into all small letters first?' },
      { minutes: 6, title: 'Find the book', scene: 'A student asks: “Do you have books about space?”', task: 'Make the bot look for the word “space” in the message and suggest a book from a list.', lookFor: 'If “space” in message → reply with a book from a list of space books.', nudge: 'How can the bot check if a word is INSIDE the message?' },
    ],
    stretch: 'If the bot does not understand, it should say so kindly and suggest what to ask.',
    cliffhanger: 'The librarian wants the bot to learn new books by itself. Next class we find out how real AI chatbots learn — and build a smarter one.',
    win: 'I built a library chatbot that understands greetings and finds books.',
    skill: 'Strings, lists and conditions — and the idea behind chatbots.',
  },
  {
    subject: 'coding', grade: 7, emoji: '🔐', title: 'The Secret Agent Code', role: 'the agency’s code-breaker',
    hook: 'A secret message has been intercepted: “Wkh wuhdvxuh lv xqghu wkh eulgjh.” The agency’s code-breaker is away — and the handover is at midnight.',
    mission: 'Write a program that cracks (and makes) secret codes.',
    chapters: [
      { minutes: 5, title: 'Crack it by hand', scene: 'The spies use a Caesar cipher: every letter is shifted along the alphabet.', task: 'Shift each letter back by 3. What does the message say?', lookFor: '“The treasure is under the bridge.”', nudge: 'W is 3 letters after T. Try shifting back 3.' },
      { minutes: 6, title: 'Let the computer do it', scene: 'There are 500 messages — too many to do by hand.', task: 'Describe the program: loop over each letter, shift it, handle z → a.', lookFor: 'A loop over characters, letter → number, add/subtract the shift, wrap with modulo 26, back to a letter.', nudge: 'Computers store letters as numbers. What happens after “z”?' },
      { minutes: 6, title: 'The unknown shift', scene: 'A new message uses a shift nobody knows.', task: 'How could the program find the shift automatically?', lookFor: 'Try all 26 shifts and pick the one that makes real words (or use letter frequency — “e” is most common).', nudge: 'There are only 26 possible shifts. Could a computer just try them all?' },
    ],
    stretch: 'Why is a Caesar cipher easy to break? What would make a code harder to crack?',
    cliffhanger: 'The enemy just switched to a code that changes with every letter. Next class we build the Vigenère cipher — and learn how real encryption keeps your messages safe.',
    win: 'I cracked a secret message and designed a program that breaks codes.',
    skill: 'Strings, loops, character codes and modulo arithmetic — and brute-force search.',
  },
  {
    subject: 'coding', grade: 8, emoji: '🌐', title: 'Your First Website', role: 'the web developer',
    hook: 'A local bakery has no website, and customers keep calling to ask the opening hours. The owner will pay in cupcakes — if you can build it today.',
    mission: 'Build the bakery’s homepage with HTML and CSS.',
    chapters: [
      { minutes: 5, title: 'The structure', scene: 'The page needs the bakery’s name, a menu, and the opening hours.', task: 'Write the HTML: a heading, a list for the menu, a paragraph for the hours.', lookFor: '<h1> for the name, <ul><li> for the menu, <p> for the hours.', nudge: 'Which tag makes a big title? Which makes a list?' },
      { minutes: 6, title: 'Make it delicious', scene: 'The owner says: “It looks like a boring document.”', task: 'Add CSS: a background colour, a font, and a coloured heading.', lookFor: 'CSS rules for body { background, font-family } and h1 { color }.', nudge: 'CSS picks an element and changes how it looks. Start with the heading.' },
      { minutes: 6, title: 'The order button', scene: 'Customers want to order on WhatsApp.', task: 'Add a link that looks like a button.', lookFor: '<a href="…"> styled with padding, background and rounded corners.', nudge: 'A link is <a href>. How can CSS make it look like a button?' },
    ],
    stretch: 'Make the menu show side by side on a laptop but stacked on a phone (flexbox or a media query).',
    cliffhanger: 'The bakery wants the button to show how many cupcakes are left today — live. Next class we add JavaScript and make the page interactive.',
    win: 'I built a real bakery website with HTML and CSS.',
    skill: 'HTML structure, CSS styling and links — how every website is built.',
  },
  {
    subject: 'coding', grade: 9, emoji: '🎮', title: 'The Game Studio', role: 'the lead game developer',
    hook: 'An indie game studio is two days from launching “Space Dodge” — and the ship flies through the asteroids without crashing. The lead developer quit. That’s you now.',
    mission: 'Fix the game loop, the movement and the collisions.',
    chapters: [
      { minutes: 5, title: 'The game loop', scene: 'The game draws one frame and then freezes.', task: 'Explain what a game loop does, and list its three steps.', lookFor: 'Repeat about 60 times a second: read input, update positions, draw the screen.', nudge: 'A film is many pictures a second. What must change between pictures?' },
      { minutes: 6, title: 'Moving the ship', scene: 'The ship is at x = 100. Pressing the right arrow should move it 5 pixels each frame, but not past x = 400.', task: 'Write the rule in code-like steps.', lookFor: 'if right pressed: x = x + 5; if x > 400: x = 400 (a clamp).', nudge: 'Change x, then check it hasn’t gone too far.' },
      { minutes: 6, title: 'Crash!', scene: 'The ship is a 20 × 20 box at (x, y); an asteroid is a 30 × 30 box at (ax, ay).', task: 'Write the test for whether they overlap.', lookFor: 'x < ax + 30 and x + 20 > ax and y < ay + 30 and y + 20 > ay (rectangle collision).', nudge: 'Two boxes DON’T touch if one is fully left, right, above or below the other.' },
    ],
    stretch: 'Speed the asteroids up as the score grows. What should the formula be so it is hard but fair?',
    cliffhanger: 'Players want a high-score table saved online. Next class we store data and learn how games talk to servers.',
    win: 'I fixed a game’s loop, movement and collision detection.',
    skill: 'The game loop, coordinates and rectangle collision detection.',
  },
  {
    subject: 'coding', grade: 10, emoji: '🎧', title: 'The Recommender', role: 'the data engineer',
    hook: 'A music app wants a “You might like” button — like Spotify’s. Their only engineer is on leave, and the investors want a demo on Monday.',
    mission: 'Build a recommender with lists, dictionaries and a simple similarity score.',
    chapters: [
      { minutes: 5, title: 'The data', scene: 'Each user has a list of songs they liked.', task: 'How would you store every user’s liked songs in code?', lookFor: 'A dictionary: user → list (or set) of songs.', nudge: 'You need to look up a person and get their songs. What structure does that?' },
      { minutes: 6, title: 'Who is like you?', scene: 'Asha likes {A, B, C, D}. Kabir likes {B, C, D, E}. Mia likes {A, F}.', task: 'Who is most similar to Asha? How would you measure it?', lookFor: 'Kabir — 3 songs in common (intersection); a score like shared ÷ total (Jaccard).', nudge: 'Count the songs they both like.' },
      { minutes: 6, title: 'Recommend!', scene: 'Now suggest a new song to Asha.', task: 'Which song should you recommend, and why?', lookFor: 'E — liked by her most similar user and not yet heard by her.', nudge: 'What does Kabir like that Asha hasn’t heard?' },
    ],
    stretch: 'What goes wrong for a brand-new user with no likes? How would you fix it? (The cold-start problem.)',
    cliffhanger: 'The app has 10 million users and the recommender is now far too slow. Next class we find out about efficient algorithms — and how machine learning does this at scale.',
    win: 'I built a music recommender with dictionaries and a similarity score.',
    skill: 'Dictionaries and sets, similarity measures, and the idea behind recommendation systems.',
  },
  {
    subject: 'coding', grade: 11, emoji: '🤖', title: 'Train an AI', role: 'the machine-learning engineer',
    hook: 'A hospital wants an AI to spot which patients might need extra care. They have data but no ML engineer. You have 30 minutes to show them how it works — and what could go wrong.',
    mission: 'Train a simple model and test whether it can be trusted.',
    chapters: [
      { minutes: 5, title: 'Features and labels', scene: 'The data has age, blood pressure, heart rate, and whether the patient needed extra care.', task: 'Which columns are the features and which is the label? Why must we hold some data back?', lookFor: 'Features: age, BP, heart rate; label: needed care. Hold back a test set to check on unseen patients.', nudge: 'What do we KNOW about a patient, and what do we want to PREDICT?' },
      { minutes: 6, title: '99% accurate?', scene: 'Only 1 in 100 patients needed extra care. A model that always says “no” is 99% accurate!', task: 'Why is that model useless? What would you measure instead?', lookFor: 'It misses every patient who needs care — look at recall (how many of the real cases it catches).', nudge: 'How many patients who NEEDED care does it find?' },
      { minutes: 6, title: 'Bias', scene: 'The training data came almost entirely from one city’s hospital.', task: 'What could go wrong when the AI is used in a village clinic?', lookFor: 'The data may not represent other people, so predictions can be unfair or wrong — collect representative data, test on each group.', nudge: 'Would the patients in the village be like the patients in the city?' },
    ],
    stretch: 'Sketch how a decision tree might decide: which single question would you ask first, and why?',
    cliffhanger: 'The hospital loved the demo and wants to see the model actually learn. Next class we write Python that trains it — and watch its accuracy climb.',
    win: 'I explained how an AI model is trained, tested and made fair.',
    skill: 'Features and labels, train/test splits, accuracy vs recall, and bias in data.',
  },
  {
    subject: 'coding', grade: 12, emoji: '📱', title: 'Launch Your Startup', role: 'the startup’s CTO',
    hook: 'Three friends have a startup idea — an app that tells students which bus is coming, live. They have a pitch with investors next week, and no CTO. Until now.',
    mission: 'Design how the app gets, stores and shows live data.',
    chapters: [
      { minutes: 5, title: 'Where does the data come from?', scene: 'The city publishes bus positions through an API.', task: 'Explain what an API is, and what your app sends and gets back.', lookFor: 'An API is a way programs ask another service for data: send a request (bus route) → get JSON back (positions, times).', nudge: 'Think of a waiter taking your order to the kitchen. Who is the waiter here?' },
      { minutes: 6, title: 'Design the data', scene: 'The API returns: route, bus_id, lat, lon, updated_at.', task: 'How would you calculate “arriving in 4 minutes” for a student’s stop?', lookFor: 'Distance from the bus to the stop ÷ average speed (plus freshness check on updated_at).', nudge: 'You know where the bus is and where the stop is. What else do you need?' },
      { minutes: 6, title: 'When it breaks', scene: 'The city’s API goes down for 10 minutes every evening.', task: 'What should the app do? Design the fallback.', lookFor: 'Cache the last known data, show it with a “last updated” time, retry with backoff, never crash.', nudge: 'What would a user rather see: an error, or the last known position with a warning?' },
    ],
    stretch: '10,000 students open the app at 8 a.m. at once. How do you stop the server falling over?',
    cliffhanger: 'An investor asks: “Could AI predict delays before they happen?” Next class we build the first version — with real data and a real model.',
    win: 'I designed a live-data app like a CTO: the API, the logic and the fallback.',
    skill: 'APIs and JSON, data modelling, and designing for failure.',
  },
  {
    subject: 'coding', grade: 13, emoji: '⚙️', title: 'Automate Your Monday', role: 'the automation builder',
    hook: 'Every Monday someone on your team spends three hours copying numbers from emails into a spreadsheet. Today you build the thing that does it in three seconds.',
    mission: 'Design an automation — with a little code and a little AI — that saves hours every week.',
    chapters: [
      { minutes: 5, title: 'Find the pattern', scene: 'Each email says something like: “Order #4812 — 3 units — ₹1,200 — Pune”.', task: 'What are the steps a program must do, in order?', lookFor: 'Read each email → extract fields (order, units, amount, city) → write a row → repeat.', nudge: 'If you did it by hand, what would you do for each email?' },
      { minutes: 6, title: 'Extract the fields', scene: 'Most emails follow the pattern, but some are written freely: “Hi, please send 3 more units to Pune, same as #4812.”', task: 'How would you extract fields from both kinds?', lookFor: 'A pattern (regex) for the regular ones; an AI model with a fixed output format for the free-text ones — then validate.', nudge: 'Rules work for the tidy emails. What handles the messy ones?' },
      { minutes: 6, title: 'Trust but verify', scene: 'The automation will write straight into the finance sheet.', task: 'What checks do you add before it writes?', lookFor: 'Validate types and ranges, flag low-confidence rows for a human, log every change, never overwrite silently.', nudge: 'What is the worst thing that could happen if a number is read wrong?' },
    ],
    stretch: 'How would you measure whether the automation actually saves time and stays accurate over months?',
    cliffhanger: 'Your manager saw it and asks: “Can it also reply to the customers?” Next class we build an AI agent that drafts replies — with a human in the loop.',
    win: 'I designed a real automation that turns emails into a clean spreadsheet.',
    skill: 'Breaking a task into steps, pattern extraction, AI with structured output, and validation.',
  },
];
