import type { Story } from './types';

/** English, Grades 1–12: one story each — the child writes, reads or speaks their way through it. */
export const ENGLISH_STORIES: Story[] = [
  {
    subject: 'english', grade: 1, emoji: '🌳', title: 'The Talking Treehouse', role: 'the treehouse’s word keeper',
    hook: 'There is a treehouse that can talk — but only when someone says the magic rhyming words. The last word keeper moved away. The treehouse has chosen you!',
    mission: 'Wake up the talking treehouse with sounds, rhymes and your first sentence.',
    chapters: [
      { minutes: 5, title: 'The door sound', scene: 'The door only opens for words that start with the same sound as “tree”.', task: 'Say three words that start with the “t” sound.', lookFor: 'Words like top, ten, tiger, toy — the child hears the first sound.', nudge: 'Tap your tongue behind your teeth: t-t-t. What starts like that?' },
      { minutes: 6, title: 'The rhyming ladder', scene: 'Each step of the ladder needs a word that rhymes with the one before: cat …', task: 'Climb five steps: cat, hat, … keep going!', lookFor: 'Rhymes like mat, bat, sat, rat — same ending sound.', nudge: 'Listen to the end of “cat”. What else ends with “-at”?' },
      { minutes: 6, title: 'Talk to the treehouse', scene: 'The treehouse wakes up and asks, “Who are you, and what do you like?”', task: 'Answer in one sentence that starts with a capital letter and ends with a full stop.', lookFor: 'A sentence like “I am Asha and I like dogs.” — capital I, full stop at the end.', nudge: 'Start with “I am …”. What goes at the very end of a sentence?' },
    ],
    stretch: 'Make a two-line rhyme about the treehouse: “Up in the tree / …”',
    cliffhanger: 'The treehouse whispers a secret: a lost storybook is hidden in the garden, but its pages are all mixed up. Next class we put the story back in order.',
    win: 'I woke up the talking treehouse with sounds, rhymes and my own sentence.',
    skill: 'Beginning sounds, rhyming words and writing a simple sentence.',
  },
  {
    subject: 'english', grade: 2, emoji: '🐧', title: 'Postcards from Percy', role: 'Percy’s pen pal',
    hook: 'Percy the penguin has left the South Pole to see the world — and he keeps sending postcards with words missing! As his pen pal, you have to fill the gaps and write back.',
    mission: 'Read Percy’s postcards and write him a postcard of your own.',
    chapters: [
      { minutes: 5, title: 'Naming words', scene: 'Percy writes: “Today I saw a big ___ and ate an ice-cold ___.”', task: 'Fill each gap with a naming word (a noun).', lookFor: 'Nouns such as elephant/ship, lolly/fish — words for things.', nudge: 'What could Percy SEE? What could he EAT?' },
      { minutes: 6, title: 'Doing words', scene: 'Next card: “In India I ___ on a camel and ___ a kite.”', task: 'Add two doing words (verbs) in the past: what did Percy do?', lookFor: 'rode, flew — verbs, ideally in the past.', nudge: 'Did he do it today or yesterday? How do we say that?' },
      { minutes: 6, title: 'Write back', scene: 'Percy asks, “What is your town like?”', task: 'Write three sentences to Percy: start with “Dear Percy,” and end with your name.', lookFor: 'Three sentences with capitals and full stops, a greeting and a sign-off.', nudge: 'Tell him one thing you can see, one thing you can eat, one thing you like doing.' },
    ],
    stretch: 'Add describing words to make your postcard exciting: not “a dog” but “a fluffy, sleepy dog”.',
    cliffhanger: 'Percy’s next postcard arrives upside down and full of spelling mistakes — something is wrong! Next class we crack his secret message.',
    win: 'I read Percy’s postcards and wrote him one back.',
    skill: 'Nouns and verbs, past tense, and writing a short letter.',
  },
  {
    subject: 'english', grade: 3, emoji: '🐉', title: 'The Dragon Who Couldn’t Describe', role: 'the dragon’s word coach',
    hook: 'Dazzle the dragon wants to be a famous storyteller, but every story she tells is boring: “There was a castle. It was big.” She needs a word coach — fast.',
    mission: 'Teach Dazzle to tell a story people can SEE.',
    chapters: [
      { minutes: 5, title: 'Describing words', scene: 'Dazzle says: “There was a castle.”', task: 'Add three adjectives to make the castle come alive.', lookFor: 'e.g. “a dark, crumbling, enormous castle” — adjectives, with commas between them.', nudge: 'What colour is it? How old? How big?' },
      { minutes: 6, title: 'Use your senses', scene: 'Now Dazzle flies into a busy market.', task: 'Write one sentence each for what she sees, hears and smells.', lookFor: 'Sensory detail: “She heard sellers shouting”, “She smelled hot samosas”.', nudge: 'Close your eyes and imagine the market. What noises are there?' },
      { minutes: 6, title: 'Strong verbs', scene: 'Dazzle says: “The dragon went across the sky.”', task: 'Replace “went” with a verb that shows HOW she moved.', lookFor: 'swooped, soared, zoomed, glided — a verb that paints a picture.', nudge: 'Was she fast or slow? Graceful or clumsy?' },
    ],
    stretch: 'Write Dazzle’s opening line that makes a reader NEED to know what happens next.',
    cliffhanger: 'Dazzle’s story is so good that the King wants to hear it — but only if it has a proper beginning, middle and end. Next class we plan the whole story.',
    win: 'I taught a dragon to describe things so vividly that people could see them.',
    skill: 'Adjectives, sensory description and powerful verbs.',
  },
  {
    subject: 'english', grade: 4, emoji: '📰', title: 'Newsroom Kids', role: 'the youngest reporter',
    hook: 'Breaking news! A tiger cub has escaped from the city zoo and been found — sleeping in a school library. The Kids’ Times needs a reporter on the story in 20 minutes.',
    mission: 'Write the front-page news story.',
    chapters: [
      { minutes: 5, title: 'The 5 Ws', scene: 'You have the facts: a tiger cub, the city library, Tuesday morning, found by a librarian, it squeezed through a broken fence.', task: 'Sort the facts into Who, What, Where, When and Why.', lookFor: 'Who: cub/librarian; What: escaped and was found; Where: library; When: Tuesday morning; Why: broken fence.', nudge: 'Take one fact at a time: does it answer who, what, where, when or why?' },
      { minutes: 6, title: 'The headline', scene: 'The editor wants a headline that makes people pick up the paper.', task: 'Write a short, punchy headline (under 8 words).', lookFor: 'e.g. “Sleepy Tiger Cub Found in School Library!” — short, present tense, exciting.', nudge: 'What is the most surprising part of the story?' },
      { minutes: 6, title: 'The first sentence', scene: 'A news story tells the most important facts first.', task: 'Write the opening sentence using at least three of the 5 Ws, in the past tense.', lookFor: 'e.g. “On Tuesday morning, a tiger cub that escaped from the zoo was found asleep in the city library.”', nudge: 'Start with WHEN, then WHAT happened, then WHERE.' },
    ],
    stretch: 'Add a quote from the librarian, with speech marks: “…,” said the librarian.',
    cliffhanger: 'The editor loved it — and now the zoo wants the paper to find out who broke the fence. Next class we become investigative reporters and write an interview.',
    win: 'I wrote a front-page news story like a real reporter.',
    skill: 'The 5 Ws, headlines, and writing clear sentences in the past tense.',
  },
  {
    subject: 'english', grade: 5, emoji: '📔', title: 'The Secret Diary', role: 'the diary’s writer',
    hook: 'You find an old diary in your grandmother’s cupboard. The last entry stops mid-sentence: “Tomorrow I will finally tell everyone the truth about…”',
    mission: 'Read the diary’s clues, then write the missing entry.',
    chapters: [
      { minutes: 5, title: 'How did she feel?', scene: 'An entry reads: “My hands would not stop shaking, and I could not eat a thing at dinner.”', task: 'How was she feeling? Which words tell you — she never says the feeling!', lookFor: 'Nervous or scared — shown by the shaking hands and not eating (show, don’t tell).', nudge: 'When do YOUR hands shake? When do you lose your appetite?' },
      { minutes: 6, title: 'Feelings words', scene: '“Happy”, “sad” and “angry” appear on every page.', task: 'Find stronger feelings words for each: happy, sad, angry.', lookFor: 'e.g. overjoyed/delighted, miserable/heartbroken, furious/livid.', nudge: 'How happy? A little happy, or jumping-up-and-down happy?' },
      { minutes: 6, title: 'The missing entry', scene: 'The diary is waiting for the next day’s entry.', task: 'Write the entry: first person, past tense, one paragraph — and show a feeling without naming it.', lookFor: 'A paragraph with “I …”, past tense, and a shown (not told) emotion.', nudge: 'Start with “Dear Diary, today …”. What did her body do?' },
    ],
    stretch: 'Write the same moment from her best friend’s point of view — what did SHE notice?',
    cliffhanger: 'Tucked in the back cover is a letter, never sent, sealed in 1974. Next class we open it — and learn to write letters that move people.',
    win: 'I finished a mystery diary, showing feelings without naming them.',
    skill: 'Inference, emotive vocabulary, and first-person narrative writing.',
  },
  {
    subject: 'english', grade: 6, emoji: '📣', title: 'The Advert Agency', role: 'the agency’s youngest copywriter',
    hook: 'A new ice-cream brand, Frostbite, launches next week and their advert is terrible. Your agency has one day to win the account — and you are writing the words.',
    mission: 'Write an advert that makes people want Frostbite.',
    chapters: [
      { minutes: 5, title: 'Spot the tricks', scene: 'Look at a famous advert slogan: “Taste the rainbow.”', task: 'Why does it work? Name the technique.', lookFor: 'Imperative (a command), sensory/colourful imagery, short and memorable.', nudge: 'Is it telling you something, or telling you to DO something?' },
      { minutes: 6, title: 'The slogan', scene: 'Frostbite is cold, crunchy, and made with real mango.', task: 'Write a slogan using alliteration or a rhyme.', lookFor: 'e.g. “Crisp. Cold. Crunchy. Frostbite.” / “Mango so real, you’ll feel the chill.”', nudge: 'Pick a sound and repeat it: “c”, “m”, “f”…' },
      { minutes: 6, title: 'The pitch', scene: 'The client asks: “Why should a busy parent buy it?”', task: 'Write two persuasive sentences using a “rule of three” and a rhetorical question.', lookFor: 'e.g. “Want a treat that’s fresh, fruity and fun? …” — a triple and a question.', nudge: 'What three good things could you say? Start with a question.' },
    ],
    stretch: 'Now write a SNEAKY advert for a vegetable — can you make broccoli sound amazing?',
    cliffhanger: 'The client loved it — but a rival says the ad is “misleading”. Next class we look at facts and opinions, and learn to spot persuasive tricks in real news.',
    win: 'I wrote an advert with a slogan and a pitch that would sell ice-cream.',
    skill: 'Persuasive techniques: imperatives, alliteration, rule of three, rhetorical questions.',
  },
  {
    subject: 'english', grade: 7, emoji: '🌘', title: 'Midnight at the Museum', role: 'the mystery writer',
    hook: 'A publisher is running a mystery-story competition for young writers. The prize: your story printed in a real book. The theme: “midnight at the museum”. You have 30 minutes to plan the winner.',
    mission: 'Plan and open a gripping mystery story.',
    chapters: [
      { minutes: 5, title: 'The setting', scene: 'Your story opens in an empty museum at midnight.', task: 'Write two sentences that build atmosphere — use the senses and one simile.', lookFor: 'Sensory detail and a simile: “The corridor was as silent as a held breath.”', nudge: 'What can you hear in an empty building at night? What is it LIKE?' },
      { minutes: 6, title: 'Suspense', scene: 'Something moves in the dinosaur hall.', task: 'Write three sentences that build suspense without saying what it is.', lookFor: 'Short sentences, delayed reveal, hints (“a shadow”, “a scrape of claws”).', nudge: 'Short sentences speed up the reader’s heart. Only give a clue, not the answer.' },
      { minutes: 6, title: 'The dialogue', scene: 'The night guard and a school kid meet in the dark.', task: 'Write four lines of dialogue, punctuated correctly.', lookFor: 'Speech marks, a new line for each speaker, commas before the closing speech mark, e.g. “Who’s there?” whispered the guard.', nudge: 'Every new speaker gets a new line. Where does the comma go?' },
    ],
    stretch: 'End your opening with a cliffhanger sentence that forces the reader on.',
    cliffhanger: 'The competition judges want the full story — with a twist ending they don’t see coming. Next class we learn how great writers plant clues and pull off a twist.',
    win: 'I opened a mystery story with atmosphere, suspense and real dialogue.',
    skill: 'Setting, suspense and dialogue punctuation.',
  },
  {
    subject: 'english', grade: 8, emoji: '⚖️', title: 'The Debate Club', role: 'the team’s first speaker',
    hook: 'The inter-school debate final is on Friday. The motion: “Schools should ban mobile phones.” Your team’s first speaker is ill — and you are up.',
    mission: 'Build a winning argument — and answer the other side.',
    chapters: [
      { minutes: 5, title: 'Pick your points', scene: 'You are arguing FOR the ban.', task: 'List three strong reasons, and one piece of evidence or example for each.', lookFor: 'Three distinct points (focus, cyberbullying, social time) each backed with an example or fact.', nudge: 'What problems do phones cause in a school day? Can you give a real example?' },
      { minutes: 6, title: 'Link it up', scene: 'The judges mark you down for sounding like a list.', task: 'Connect your points with linking words that show argument.', lookFor: 'Furthermore, however, as a result, consequently, on the other hand.', nudge: 'How do you say “and also”, “because of this” and “but” more formally?' },
      { minutes: 6, title: 'The rebuttal', scene: 'The other side says: “Phones are needed in emergencies.”', task: 'Answer it in two sentences: accept part of it, then turn it round.', lookFor: 'e.g. “Emergencies matter; however, the school office phone solves that without 500 phones in classrooms.”', nudge: 'Start with “It is true that …, but …”.' },
    ],
    stretch: 'Swap sides: write the best opening line for the AGAINST team.',
    cliffhanger: 'You won the semi-final — and the final motion has just been announced: “AI should write our homework.” Next class we prepare, and learn how to argue with evidence you can trust.',
    win: 'I built a debate case with evidence, linking words and a rebuttal.',
    skill: 'Argument structure, formal connectives and rebuttal.',
  },
  {
    subject: 'english', grade: 9, emoji: '🎬', title: 'The Film Critic', role: 'the youngest film critic',
    hook: 'A national magazine is looking for a teen film critic. To get the job, you must review one scene — and make readers either rush to the cinema or stay home.',
    mission: 'Analyse a scene and write a review that convinces.',
    chapters: [
      { minutes: 5, title: 'The scene', scene: 'A hero stands alone on a bridge in the rain as music rises; the camera pulls back until she is tiny.', task: 'What mood does it create, and which three choices by the director create it?', lookFor: 'Loneliness or determination — rain (pathetic fallacy), rising music, the wide shot making her small.', nudge: 'How does the weather match her feelings? Why make her look tiny?' },
      { minutes: 6, title: 'Point, evidence, explain', scene: 'Your editor wants proof, not just opinions.', task: 'Write a PEE paragraph about one choice in the scene.', lookFor: 'A clear point, a specific detail as evidence, and an explanation of its effect on the viewer.', nudge: 'Make one claim. Which detail proves it? Why does that detail matter?' },
      { minutes: 6, title: 'The verdict', scene: 'The review needs a final line and a star rating.', task: 'Write a one-sentence verdict that uses a striking image or word choice.', lookFor: 'A confident, vivid verdict — e.g. “A slow-burn storm of a film that stays with you long after the lights come up.”', nudge: 'If the film were weather, what would it be?' },
    ],
    stretch: 'Rewrite your verdict for a newspaper that hated the film — keep it fair but critical.',
    cliffhanger: 'The magazine gives you a bigger job: compare the film with the novel it was based on. Next class we analyse how writers and directors tell the same story differently.',
    win: 'I analysed a film scene and wrote a review with evidence.',
    skill: 'Analysing technique and effect, PEE paragraphs, and evaluative vocabulary.',
  },
  {
    subject: 'english', grade: 10, emoji: '✉️', title: 'Letter to the Editor', role: 'the campaigning student',
    hook: 'The city plans to cut down the only big park near your school to build a car park. The newspaper will print one letter from a student this week. It had better be yours.',
    mission: 'Write a formal letter that changes minds.',
    chapters: [
      { minutes: 5, title: 'Formal or not?', scene: 'Two openings: “Hey editor, the park thing is so bad!!” and “I am writing to express my concern about the proposed…”', task: 'Which is right for a newspaper, and why? Rewrite the first one formally.', lookFor: 'The second — formal tone, no slang, full sentences; a good formal rewrite of the first.', nudge: 'Who reads a newspaper? How would you speak to a head teacher?' },
      { minutes: 6, title: 'Facts and feelings', scene: 'You know: 400 students use the park daily; it has 60 old trees; the city already has 3 car parks within 1 km.', task: 'Write a paragraph combining logic (facts) and emotion.', lookFor: 'Statistics used as evidence plus an emotive appeal (children playing, clean air).', nudge: 'Pick the strongest fact. Then say why it matters to people.' },
      { minutes: 6, title: 'The call to action', scene: 'Letters that end weakly are forgotten.', task: 'Write the closing paragraph with a clear request and a formal sign-off.', lookFor: 'A specific request (reconsider the plan / attend the council meeting) and “Yours faithfully/sincerely”.', nudge: 'What exactly do you want readers or the council to DO?' },
    ],
    stretch: 'Anticipate the council’s best argument (parking shortage) and answer it in one sentence.',
    cliffhanger: 'The letter was printed — and the council has invited you to speak at the public meeting next week. Next class we turn the letter into a speech.',
    win: 'I wrote a formal letter to a newspaper that argues with facts and feeling.',
    skill: 'Formal register, persuasion (logos and pathos) and letter conventions.',
  },
  {
    subject: 'english', grade: 11, emoji: '🎤', title: 'The TEDx Talk', role: 'the youngest TEDx speaker',
    hook: 'Your school is hosting a TEDx event and the organisers want one student speaker. Topic: “an idea worth spreading”. The audition is in three days.',
    mission: 'Write the opening of a talk that grips a room.',
    chapters: [
      { minutes: 5, title: 'The hook', scene: 'Most talks start with “Hello, my name is… and today I will talk about…”. The audience checks their phones.', task: 'Write an opening line that grabs attention: a question, a startling fact or a tiny story.', lookFor: 'A genuine hook, e.g. “By the time I finish this sentence, 250 babies will have been born.”', nudge: 'What would make YOU look up from your phone?' },
      { minutes: 6, title: 'Ethos, pathos, logos', scene: 'Your idea: “Every student should learn to cook.”', task: 'Write one sentence each of credibility, emotion and logic.', lookFor: 'Ethos (why listen to you), pathos (a feeling or story), logos (a fact or reasoned point).', nudge: 'Why should they trust YOU? What would make them feel something? What is the evidence?' },
      { minutes: 6, title: 'The one line they remember', scene: 'People forget most of a talk but remember one line.', task: 'Write a memorable closing line using a device (tricolon, antithesis or a callback to your hook).', lookFor: 'e.g. antithesis: “We don’t need more recipes; we need more people who can read them.”', nudge: 'Can you flip two ideas against each other, or come back to your opening?' },
    ],
    stretch: 'Write the same idea as a 15-second version for a social-media clip.',
    cliffhanger: 'You passed the audition — the full talk is 8 minutes, in front of 400 people. Next class we structure the whole talk and learn how to deliver it.',
    win: 'I wrote the hook, the argument and the closing line of a TEDx talk.',
    skill: 'Rhetorical hooks, ethos/pathos/logos and memorable rhetorical devices.',
  },
  {
    subject: 'english', grade: 12, emoji: '🎓', title: 'The College Essay', role: 'the applicant',
    hook: 'Your dream university has one essay question: “Tell us about a moment that changed how you see the world.” Thousands apply; the readers spend two minutes on each essay.',
    mission: 'Write an opening that makes a tired admissions reader sit up.',
    chapters: [
      { minutes: 5, title: 'Show, don’t tell', scene: 'Draft line: “I am a very determined person who never gives up.”', task: 'Rewrite it as a tiny scene that SHOWS determination.', lookFor: 'A concrete moment — e.g. “At 2 a.m., on my forty-first attempt, the code finally ran.”', nudge: 'When did you last refuse to give up? What exactly did you see and do?' },
      { minutes: 6, title: 'The specific detail', scene: 'Generic essays blur together; specific ones are remembered.', task: 'Add one precise, surprising detail to your scene.', lookFor: 'A sensory or unusual detail that only this writer could know.', nudge: 'What small thing do you still remember about that moment — a sound, an object, a word?' },
      { minutes: 6, title: 'The turn', scene: 'The question asks how the moment CHANGED you.', task: 'Write two sentences of reflection that move from the story to the insight.', lookFor: 'Reflection that names a change in thinking, not just a feeling.', nudge: 'What did you believe before? What do you believe now?' },
    ],
    stretch: 'Cut your paragraph by a third without losing its meaning — every word must earn its place.',
    cliffhanger: 'The university has a second prompt: “Why this subject?” Next class we write it — and learn to edit like a professional.',
    win: 'I wrote a college-essay opening that shows, not tells.',
    skill: 'Narrative non-fiction, specific detail, reflection and concise editing.',
  },
];
