import type { Story } from './types';

/** Mathematics, Grades 1–12: one story each, built on that grade's syllabus. */
export const MATHS_STORIES: Story[] = [
  {
    subject: 'mathematics', grade: 1, emoji: '🐒', title: 'The Monkey Bakery', role: 'the head baker',
    hook: 'Mango the monkey has opened a bakery in the jungle — and the animals are hungry! Today YOU are the head baker, and every order needs counting just right.',
    mission: 'Fill every animal’s order with exactly the right number of treats.',
    chapters: [
      { minutes: 5, title: 'The first customer', scene: 'Ellie the elephant wants 3 banana buns and 2 coconut cakes on one plate.', task: 'Draw the plate and count how many treats Ellie gets altogether.', lookFor: '5 — ideally counting on from 3 (“4, 5”) instead of starting again from 1.', nudge: 'Put up 3 fingers for the buns. Now add 2 more. How many fingers?' },
      { minutes: 6, title: 'The greedy parrot', scene: 'Polly the parrot takes 4 of the 9 cookies on the tray before anyone notices!', task: 'How many cookies are left for the other animals?', lookFor: '5 — by crossing out 4 of 9 drawn cookies, or counting back from 9.', nudge: 'Draw 9 circles. Cross out the 4 Polly took. Count the ones left.' },
      { minutes: 6, title: 'Party boxes', scene: 'The lion cubs are having a party. Each box holds 2 cupcakes, and there are 5 cubs.', task: 'How many cupcakes should the baker make so every cub gets a box?', lookFor: '10 — counting in twos (2, 4, 6, 8, 10).', nudge: 'Draw a box for each cub with 2 cupcakes in it. Count them all.' },
    ],
    stretch: 'Make 10 in as many ways as you can with two numbers (3 + 7, 6 + 4 …). How many ways are there?',
    cliffhanger: 'Oh no — the bakery oven just broke, and the big Jungle Fair is on Saturday. Next class we plan the fair: how many treats do we need for ALL the animals?',
    win: 'I ran the Monkey Bakery and counted every order correctly.',
    skill: 'Counting on, taking away and counting in twos — the start of addition, subtraction and multiplication.',
  },
  {
    subject: 'mathematics', grade: 2, emoji: '🚂', title: 'The Toy Train Station', role: 'the station master',
    hook: 'Welcome aboard! The toy train is leaving the station, but the tickets, the carriages and the clock all need a station master who is good with numbers. That’s you.',
    mission: 'Get every passenger on the train, with the right tickets, on time.',
    chapters: [
      { minutes: 5, title: 'Tens and ones', scene: 'Passengers sit in carriages of 10. Today 47 passengers are waiting on the platform.', task: 'How many FULL carriages do we need, and how many passengers sit in the last one?', lookFor: '4 full carriages and 7 in the next — 47 is 4 tens and 7 ones.', nudge: 'Draw a long stick for every 10 passengers and a dot for each extra one.' },
      { minutes: 6, title: 'The ticket office', scene: 'A ticket costs ₹25. A grandmother buys tickets for herself and her grandson.', task: 'How much does she pay? She gives ₹100 — how much change?', lookFor: '₹50, and ₹50 change — adding tens first (20 + 20, 5 + 5).', nudge: 'Add the tens together, then the ones. Then count up from 50 to 100.' },
      { minutes: 6, title: 'Beat the clock', scene: 'The train leaves at 3 o’clock and the journey takes 2 hours.', task: 'Show the arrival time on a clock face. What time is it?', lookFor: '5 o’clock — moving the hour hand on 2 hours.', nudge: 'Put your finger on 3 and count 2 more numbers round the clock.' },
    ],
    stretch: 'A second train carries 36 people and the first carries 47. How many more on the first train?',
    cliffhanger: 'The train has stopped in a tunnel — and the map to the next station is torn into pieces! Next class we put the map back together with shapes and measuring.',
    win: 'I was the station master and got 47 passengers onto the right train on time.',
    skill: 'Place value (tens and ones), adding and subtracting two-digit numbers, and telling the time.',
  },
  {
    subject: 'mathematics', grade: 3, emoji: '🌻', title: 'The School Garden', role: 'the garden planner',
    hook: 'The school has given your class an empty patch of ground and one job: turn it into the best garden in the city — before the Garden Show judges arrive.',
    mission: 'Plan a garden with the right number of plants, a fence around it, and fair shares of the harvest.',
    chapters: [
      { minutes: 5, title: 'Rows of flowers', scene: 'The sunflowers must be planted in 6 rows with 4 in each row.', task: 'How many sunflower seeds do we need? Show it as an array of dots.', lookFor: '24 — and the child sees 6 × 4 and 4 × 6 are the same array turned round.', nudge: 'Draw 6 rows of 4 dots. Can you count them in fours?' },
      { minutes: 6, title: 'The fence', scene: 'The garden is a rectangle 8 metres long and 5 metres wide. Rabbits keep getting in!', task: 'How many metres of fence go all the way round?', lookFor: '26 m — 8 + 5 + 8 + 5 (perimeter), not 8 × 5.', nudge: 'Walk your finger around the drawing. Write each side as you pass it.' },
      { minutes: 6, title: 'Sharing the tomatoes', scene: 'The garden grew 36 tomatoes. They are shared equally between 4 classes.', task: 'How many does each class get? What fraction of the harvest is that?', lookFor: '9 each — and one class gets 1/4 of the tomatoes.', nudge: 'Deal them out like cards: one for each class, again and again.' },
    ],
    stretch: 'If the garden were 10 m by 3 m, would the fence be longer or shorter? Is the space inside bigger or smaller?',
    cliffhanger: 'The judges arrive tomorrow — but someone has trampled half the garden! Next class we work out how much space is left, using area.',
    win: 'I planned a whole garden: the seeds, the fence and fair shares of the harvest.',
    skill: 'Multiplication as arrays, perimeter, and division as fair sharing — with a first look at fractions.',
  },
  {
    subject: 'mathematics', grade: 4, emoji: '🏏', title: 'The Cricket Tournament', role: 'the tournament organiser',
    hook: 'The inter-school cricket tournament is in trouble: the organiser has fallen ill! You have been handed the clipboard — the teams, the tickets and the scores are all yours now.',
    mission: 'Organise the tournament: fixtures, ticket money and the final scoreboard.',
    chapters: [
      { minutes: 5, title: 'The ticket money', scene: '1,245 people bought tickets at ₹30 each on the first day.', task: 'How much money came in? Estimate first, then work it out.', lookFor: '₹37,350 — with a sensible estimate first (about 1,200 × 30 = 36,000).', nudge: 'Try 1,245 × 3 first, then make it ten times bigger.' },
      { minutes: 6, title: 'Who plays whom', scene: 'There are 6 teams, and every team plays every other team once.', task: 'How many matches are there? Find a way to list them without missing any.', lookFor: '15 — found with a table or an organised list (A plays 5, B plays 4 new ones …).', nudge: 'Start with Team A: who does it play? Then Team B — who is left for B?' },
      { minutes: 6, title: 'The fraction of the final', scene: 'In the final, the winning team scored 180 runs. Their captain scored 3/10 of them.', task: 'How many runs did the captain score?', lookFor: '54 — find 1/10 (18), then 3 lots of it.', nudge: 'What is one tenth of 180? Now you need three of those.' },
    ],
    stretch: 'If there were 10 teams, how many matches? Can you spot the pattern from 2, 3, 4 teams?',
    cliffhanger: 'Rain has washed out the last two matches — and the league table is a mess. Next class we fix the table with averages and decide who really deserves the trophy.',
    win: 'I organised a cricket tournament: the money, the fixtures and the final.',
    skill: 'Multiplying large numbers with estimation, organised counting, and fractions of amounts.',
  },
  {
    subject: 'mathematics', grade: 5, emoji: '🛒', title: 'The Big Sale', role: 'the store manager',
    hook: 'You have just been made manager of Sariro Supermart — and tomorrow is the biggest sale of the year. The owner left three tasks on your desk before she flew off on holiday.',
    mission: 'Set the sale prices, stock the shelves and make sure the shop still makes money.',
    chapters: [
      { minutes: 5, title: 'Sale prices', scene: 'Everything is 20% off. A school bag costs ₹650.', task: 'What is the sale price of the bag?', lookFor: '₹520 — 10% is ₹65, so 20% is ₹130, and 650 − 130 = 520.', nudge: 'Find 10% first — divide by 10. How can that help you find 20%?' },
      { minutes: 6, title: 'The shelf', scene: 'A shelf is 1.2 metres long. Each cereal box is 0.15 metres wide.', task: 'How many boxes fit side by side on the shelf?', lookFor: '8 — thinking in cm helps: 120 ÷ 15 = 8.', nudge: 'Turn both lengths into centimetres. Now it is a division you know.' },
      { minutes: 6, title: 'Still making money?', scene: 'The shop buys a toy for ₹240 and usually sells it for ₹400. In the sale it is 30% off.', task: 'Does the shop still make a profit on each toy? How much?', lookFor: 'Yes — the sale price is ₹280, so ₹40 profit on each.', nudge: 'Find the sale price first. Then compare it with what the shop paid.' },
    ],
    stretch: 'Which is the better deal: 25% off, or “buy 3, get 1 free” on toys that cost the same?',
    cliffhanger: 'The owner has just called: a truck of 480 mangoes arrives tomorrow and they go bad in 3 days. Next class we plan how to sell every last one — with ratios and a budget.',
    win: 'I managed a supermarket sale and proved the shop still made a profit.',
    skill: 'Percentages, decimals as measurements, and profit — maths every shop uses.',
  },
  {
    subject: 'mathematics', grade: 6, emoji: '🏕️', title: 'The Himalayan Trek', role: 'the expedition planner',
    hook: 'Your class has won a place on a Himalayan trek! But the guide will only take the group if the plan is perfect — the food, the temperatures and the route are all in your hands.',
    mission: 'Plan a safe trek: food for everyone, the cold at the top and the distances each day.',
    chapters: [
      { minutes: 5, title: 'Food for the team', scene: 'The recipe for trail mix is nuts : raisins : chocolate = 3 : 2 : 1. You need 1.2 kg of trail mix.', task: 'How much of each should you buy?', lookFor: 'Nuts 600 g, raisins 400 g, chocolate 200 g — 6 parts, each part 200 g.', nudge: 'How many parts are there altogether? How much is one part?' },
      { minutes: 6, title: 'Colder and colder', scene: 'At base camp it is 8°C. Every 1,000 m up it gets 6°C colder. The top is 3,000 m above base camp.', task: 'What is the temperature at the top?', lookFor: '−10°C — 8 − 18 = −10, using a number line below zero.', nudge: 'Draw a thermometer. Start at 8 and go down 6 three times.' },
      { minutes: 6, title: 'The route', scene: 'The trek is 42 km over 4 days. The first day is the hardest, so it should be half as long as each of the other days.', task: 'How long is each day’s walk?', lookFor: 'Day 1: 6 km, the other days 12 km each — 0.5x + 3x = 42 gives x = 12.', nudge: 'If a normal day is one “chunk”, how many chunks is the whole trek?' },
    ],
    stretch: 'The team walks 3 km per hour uphill and 5 km per hour downhill. How long does a 12 km day take if half is up and half is down?',
    cliffhanger: 'A storm is coming — the guide says we must reach the next camp in half the time. Next class we work out the fastest route using speed, distance and time.',
    win: 'I planned a Himalayan trek: the food, the freezing temperatures and the daily route.',
    skill: 'Ratio, negative numbers and the first step into algebra.',
  },
  {
    subject: 'mathematics', grade: 7, emoji: '🕵️', title: 'The Missing Diamond', role: 'the detective',
    hook: 'The Blue Star diamond has vanished from the city museum overnight. The police are stumped, but they have left three clues written in maths — and they need a detective who can read them.',
    mission: 'Crack the three maths clues to find out who took the diamond.',
    chapters: [
      { minutes: 5, title: 'The locked door', scene: 'The thief left a note: “Three times my code, plus 7, makes 52.”', task: 'Write it as an equation and find the code.', lookFor: '3x + 7 = 52, so x = 15 — undoing each step in reverse.', nudge: 'What happened to the code first? Undo the last thing that was done to it.' },
      { minutes: 6, title: 'The footprints', scene: 'The footprints are 28 cm long. Detectives know height is about 6.5 times foot length.', task: 'Roughly how tall is the thief? Which suspect matches: 1.62 m, 1.82 m or 1.95 m?', lookFor: '182 cm — the 1.82 m suspect.', nudge: 'Multiply 28 by 6.5. Remember 100 cm is 1 m.' },
      { minutes: 6, title: 'The alibi', scene: 'A suspect says: “I drove 150 km home at 60 km/h and left at 9 pm.” The theft was at 11:30 pm.', task: 'When did the suspect get home? Is the alibi true?', lookFor: '11:30 pm exactly — 150 ÷ 60 = 2.5 h. So they could not have been at the museum: the alibi holds.', nudge: 'How long does 150 km take at 60 km each hour?' },
    ],
    stretch: 'The code for the safe is a number where double it minus 9 equals it plus 14. Find it.',
    cliffhanger: 'The last suspect’s phone shows a map with angles drawn on it — the diamond is hidden where two lines cross. Next class we solve the map with angles and parallel lines.',
    win: 'I cracked three maths clues and proved who was innocent.',
    skill: 'Forming and solving equations, multiplying decimals, and speed–distance–time.',
  },
  {
    subject: 'mathematics', grade: 8, emoji: '🏠', title: 'Design Your Dream Room', role: 'the interior designer',
    hook: 'A family has hired you — yes, you — to redesign their daughter’s bedroom. They have a budget, a room full of odd shapes, and a very picky cat.',
    mission: 'Design the room: paint, flooring and furniture, all inside the budget.',
    chapters: [
      { minutes: 5, title: 'The paint', scene: 'The room is 4 m long, 3.5 m wide and 3 m high. One litre of paint covers 10 m² of wall.', task: 'How many litres do you need for the four walls (ignore the door)?', lookFor: '4.5 litres — walls are 2 × (4 × 3) + 2 × (3.5 × 3) = 45 m².', nudge: 'Unfold the room: four rectangles. What is the area of each?' },
      { minutes: 6, title: 'The round rug', scene: 'The cat wants a round rug with a diameter of 1.4 m.', task: 'What is the area of the rug? (Use π ≈ 22/7.)', lookFor: '1.54 m² — radius 0.7, π × 0.7 × 0.7.', nudge: 'Area of a circle uses the radius, not the diameter. Halve it first.' },
      { minutes: 6, title: 'The budget', scene: 'The budget is ₹50,000. Flooring costs ₹850 per m², and the furniture comes to ₹28,500.', task: 'Is there enough money for flooring the whole floor? How much is left over, or short?', lookFor: 'Floor 14 m² × 850 = ₹11,900; total ₹40,400 — ₹9,600 left.', nudge: 'Find the floor area first. Then total up every cost.' },
    ],
    stretch: 'The family wants a triangular bookshelf in the corner with sides 1 m and 1 m. How long is the front edge? (Pythagoras.)',
    cliffhanger: 'The family loved it — and now they want the WHOLE house redesigned, including a curved window and a staircase. Next class we tackle 3-D shapes and volume.',
    win: 'I designed a real room with paint, a rug and flooring — and stayed on budget.',
    skill: 'Surface area, the area of a circle, and multi-step money problems.',
  },
  {
    subject: 'mathematics', grade: 9, emoji: '🚁', title: 'Drone Delivery', role: 'the drone flight engineer',
    hook: 'A new startup wants to deliver medicine by drone to villages in the hills. They need a flight engineer who can plan the routes with coordinates — they heard you are the one.',
    mission: 'Plan drone routes on a coordinate grid, and prove they are safe.',
    chapters: [
      { minutes: 5, title: 'The map', scene: 'The hospital is at (2, 3) and the first village is at (8, 11). Each grid square is 1 km.', task: 'How far does the drone fly in a straight line?', lookFor: '10 km — a 6–8–10 right triangle, √(36 + 64).', nudge: 'How far across? How far up? Now it is a right-angled triangle.' },
      { minutes: 6, title: 'The charging stop', scene: 'The drone must recharge exactly halfway between the hospital and the village.', task: 'Where should the charging pad go?', lookFor: '(5, 7) — the midpoint, averaging the x’s and the y’s.', nudge: 'Halfway across is the average of 2 and 8. Halfway up?' },
      { minutes: 6, title: 'The power line', scene: 'A power line runs along the straight line y = 2x − 1. Drones must not cross it.', task: 'Does the line pass through the charging pad? Is the pad safe?', lookFor: 'At x = 5 the line is at y = 9, not 7 — so the pad at (5, 7) is below it and safe.', nudge: 'Put x = 5 into the line. Is the answer the pad’s y?' },
    ],
    stretch: 'Find the gradient of the drone’s route. Is it steeper or shallower than the power line?',
    cliffhanger: 'Wind is pushing the drones off course — and three villages report late deliveries. Next class we use data and averages to find which route the wind hits worst.',
    win: 'I planned a drone delivery route with coordinates and proved it was safe.',
    skill: 'Coordinate geometry: distance, midpoint and straight-line equations.',
  },
  {
    subject: 'mathematics', grade: 10, emoji: '🏀', title: 'The Perfect Shot', role: 'the sports data analyst',
    hook: 'The state basketball team is losing close games, and the coach thinks maths is the answer. She has hired you as the team’s analyst — the season starts in a week.',
    mission: 'Use quadratics, trigonometry and probability to help the team win.',
    chapters: [
      { minutes: 5, title: 'The arc of the ball', scene: 'The height of a shot is h = −5t² + 10t + 2 metres, t seconds after it leaves the hand.', task: 'What is the highest point of the shot, and when?', lookFor: '7 m at t = 1 s — from the vertex (t = −b/2a) or completing the square.', nudge: 'The top of the curve is halfway between where it would cross the ground. Or try t = 0, 0.5, 1, 1.5.' },
      { minutes: 6, title: 'The angle', scene: 'A player stands 6 m from the hoop. The hoop is 3 m high and her hands are at 2 m.', task: 'At what angle does she look up at the hoop?', lookFor: 'About 9.5° — tan θ = 1/6.', nudge: 'Draw the right triangle: how far across, how far up? Which trig ratio uses those two?' },
      { minutes: 6, title: 'Two free throws', scene: 'The star player makes 80% of free throws. With 2 seconds left, the team is down by 1, and she gets two shots.', task: 'What is the chance she scores both? At least one?', lookFor: 'Both: 0.64. At least one: 1 − 0.04 = 0.96.', nudge: 'Missing both is 0.2 × 0.2. What is “at least one” the opposite of?' },
    ],
    stretch: 'When does the ball in chapter 1 hit the ground? (Solve −5t² + 10t + 2 = 0.)',
    cliffhanger: 'The rival team’s analyst has leaked their strategy — and it is full of graphs we cannot read yet. Next class we decode it with statistics and trigonometric functions.',
    win: 'I analysed a basketball shot with a quadratic, an angle and probability.',
    skill: 'Quadratics and their vertex, trigonometric ratios, and independent probability.',
  },
  {
    subject: 'mathematics', grade: 11, emoji: '📈', title: 'Viral', role: 'the growth strategist',
    hook: 'A student’s app has just gone viral — 1,000 downloads yesterday, and the servers are melting. The founder needs someone who can predict what happens next. That is you.',
    mission: 'Model the app’s growth and decide when to buy more servers.',
    chapters: [
      { minutes: 5, title: 'Growing sequences', scene: 'Downloads: 1,000 on day 1, 1,500 on day 2, 2,250 on day 3.', task: 'What kind of sequence is this? How many downloads on day 7?', lookFor: 'Geometric, ratio 1.5 — day 7 ≈ 1,000 × 1.5⁶ ≈ 11,391.', nudge: 'Is it adding the same amount each day, or multiplying by the same amount?' },
      { minutes: 6, title: 'The total', scene: 'Each server handles 20,000 downloads in total.', task: 'How many downloads over the first 7 days? How many servers?', lookFor: 'Sum ≈ 1,000 × (1.5⁷ − 1)/0.5 ≈ 32,172 — 2 servers.', nudge: 'Add the seven days, or use the geometric sum formula if you know it.' },
      { minutes: 6, title: 'When does it slow?', scene: 'Nothing grows forever. The founder thinks the growth factor falls by 0.05 each day after day 7.', task: 'On which day do downloads stop growing?', lookFor: 'When the factor reaches 1: 1.5 − 0.05k = 1 → 10 days later, day 17.', nudge: 'Growth stops when you multiply by 1. When does 1.5 become 1?' },
    ],
    stretch: 'Write the downloads on day n as a function. Sketch it: what shape is it?',
    cliffhanger: 'A competitor has launched the same app for free — and our curve has started to bend. Next class we model the battle with functions and limits, and find out who wins.',
    win: 'I modelled a viral app with sequences and predicted when to buy servers.',
    skill: 'Geometric sequences and series, and modelling with functions.',
  },
  {
    subject: 'mathematics', grade: 12, emoji: '🚀', title: 'Mission to the Moon', role: 'mission control’s lead mathematician',
    hook: 'T-minus 30 minutes. A student satellite is launching to lunar orbit and the flight software has crashed. Mission control needs the numbers worked out by hand — by you.',
    mission: 'Use calculus and vectors to launch, steer and save the satellite.',
    chapters: [
      { minutes: 5, title: 'The climb', scene: 'The rocket’s height is h(t) = 2t³ + 5t² metres, t seconds after launch.', task: 'How fast is it climbing at t = 10 s? Is it speeding up?', lookFor: 'h′(t) = 6t² + 10t = 700 m/s; h″(10) = 130 > 0, so yes.', nudge: 'Speed is the rate of change of height. What does differentiating give you?' },
      { minutes: 6, title: 'The course correction', scene: 'The satellite is moving along 3i + 4j and must turn to 4i + 3j.', task: 'By what angle must it turn?', lookFor: 'About 16.3° — cos θ = (12 + 12)/(5 × 5) = 0.96.', nudge: 'The dot product connects two vectors to the angle between them.' },
      { minutes: 6, title: 'The fuel', scene: 'The engine burns fuel at a rate of r(t) = 40 − 2t kg/s during a 10-second burn.', task: 'How much fuel does the burn use?', lookFor: '300 kg — ∫₀¹⁰ (40 − 2t) dt = 400 − 100.', nudge: 'The total of a rate over time is the area under it. Integrate.' },
    ],
    stretch: 'When during the burn is fuel used fastest? Is there a moment of maximum height if h(t) = −t³ + 30t² + 5?',
    cliffhanger: 'Houston, we have a problem: the satellite is tumbling, and its spin follows a differential equation. Next class we solve it — and bring the satellite home.',
    win: 'I used calculus and vectors to launch and steer a satellite.',
    skill: 'Differentiation and integration as rates, and vectors with the dot product.',
  },
];
