import type { Story } from './types';

/** Science G1–6, and Physics, Chemistry and Biology G7–12. */
export const SCIENCE_STORIES: Story[] = [
  /* ── Science, Grades 1–6 ─────────────────────────────────────────────── */
  {
    subject: 'science', grade: 1, emoji: '🌱', title: 'Pip the Little Plant', role: 'Pip’s plant doctor',
    hook: 'Pip is a tiny bean plant living on a windowsill — and Pip is feeling droopy. Only a plant doctor can find out what Pip needs. Ready, doctor?',
    mission: 'Find out what plants need to grow, and help Pip get strong.',
    chapters: [
      { minutes: 5, title: 'Alive or not?', scene: 'Pip’s windowsill has a pebble, a ladybird, a toy car and a flower.', task: 'Sort them: which are living, which are not? How can you tell?', lookFor: 'Ladybird and flower are living — they grow, need food and water, and make babies.', nudge: 'Does it grow? Does it need food or water?' },
      { minutes: 6, title: 'Pip’s needs', scene: 'Pip’s leaves are yellow. Pip has been in a dark cupboard with no water for three days.', task: 'What two things does Pip need most? What would you do?', lookFor: 'Light and water — move Pip to the window and water the soil.', nudge: 'What do YOU need every day? What do you think a plant needs?' },
      { minutes: 6, title: 'Pip’s senses test', scene: 'Pip wants to know how YOU find out about the world.', task: 'Name your five senses and one thing each one tells you about a banana.', lookFor: 'See (yellow), smell (sweet), touch (smooth), taste (sweet), hear (the peel ripping).', nudge: 'Point to your eyes. What can they tell you about a banana?' },
    ],
    stretch: 'Plan a test: two bean plants, one in light, one in the dark. What do you think will happen after a week?',
    cliffhanger: 'Pip has grown a bean pod — and something is inside! Next class we find out what seeds are and how a new plant is born.',
    win: 'I was a plant doctor and saved Pip by finding out what plants need.',
    skill: 'Living and non-living things, what plants need, and the five senses.',
  },
  {
    subject: 'science', grade: 2, emoji: '🌦️', title: 'The Weather Station', role: 'the TV weather reporter',
    hook: 'Lights, camera, action! The TV station’s weather reporter is on holiday, and tonight’s forecast goes live in 20 minutes. You are the new weather reporter!',
    mission: 'Read the weather, explain what water does, and give tonight’s forecast.',
    chapters: [
      { minutes: 5, title: 'What’s the weather?', scene: 'Four pictures come in from around the country: a sunny beach, a snowy hill, a rainy street and a windy field.', task: 'Name each kind of weather and say what people should wear there.', lookFor: 'Sunny — hat and cool clothes; snowy — warm coat; rainy — umbrella; windy — jacket.', nudge: 'Look at what people in the picture are wearing. Why?' },
      { minutes: 6, title: 'Water in disguise', scene: 'A viewer asks: “Where do puddles go on a sunny day?”', task: 'Explain what happens to the puddle, and where the water goes.', lookFor: 'The sun warms it; it turns into water vapour (a gas) and goes into the air.', nudge: 'What happens to an ice cube in your hand? What if water gets even warmer?' },
      { minutes: 6, title: 'The forecast', scene: 'Dark clouds are rolling in over the city and the wind is getting stronger.', task: 'Give the forecast in one sentence, like a real reporter.', lookFor: 'Something like: “Tonight, dark clouds will bring rain, so take an umbrella!”', nudge: 'What usually comes after dark clouds?' },
    ],
    stretch: 'Water can be solid, liquid or gas. Give an example of each from your kitchen.',
    cliffhanger: 'Breaking news: a rainbow has appeared — and viewers want to know how. Next class we find out how sunlight and rain make a rainbow.',
    win: 'I was a TV weather reporter and explained where puddles go.',
    skill: 'Types of weather, and water changing between ice, water and vapour.',
  },
  {
    subject: 'science', grade: 3, emoji: '🦁', title: 'Zookeeper for a Day', role: 'the head zookeeper',
    hook: 'The city zoo’s head keeper has lost her voice — and it is feeding time! The animals are hungry, and only someone who knows how animals live can run the zoo today.',
    mission: 'Feed every animal the right food and put each one in the right home.',
    chapters: [
      { minutes: 5, title: 'Who eats what?', scene: 'A lion, a cow, a bear and a goat are all waiting to be fed.', task: 'Sort them into plant-eaters, meat-eaters and both-eaters.', lookFor: 'Herbivores: cow, goat. Carnivore: lion. Omnivore: bear.', nudge: 'Look at their teeth: flat for chewing plants, or sharp for meat?' },
      { minutes: 6, title: 'The right home', scene: 'A camel, a polar bear and a frog have arrived in crates.', task: 'Which habitat does each need, and which body part helps it live there?', lookFor: 'Camel — desert (hump, wide feet); polar bear — Arctic (thick fur and fat); frog — pond (webbed feet, moist skin).', nudge: 'Where would each animal be comfortable? What is special about its body?' },
      { minutes: 6, title: 'The food chain', scene: 'Grass, a grasshopper, a frog and a snake live in the zoo’s wild garden.', task: 'Put them in a food chain with arrows.', lookFor: 'Grass → grasshopper → frog → snake (the arrow points to who eats).', nudge: 'Who eats the grass? Who eats that animal?' },
    ],
    stretch: 'What would happen to the frogs if all the snakes disappeared? And to the grasshoppers?',
    cliffhanger: 'A mystery egg was found in the zoo garden — nobody knows what will hatch! Next class we learn how different animals grow and change, and guess what is inside.',
    win: 'I ran the zoo: fed every animal and built a food chain.',
    skill: 'Herbivores, carnivores and omnivores; habitats and adaptations; food chains.',
  },
  {
    subject: 'science', grade: 4, emoji: '🧪', title: 'The Kitchen Scientist', role: 'the kitchen scientist',
    hook: 'Grandma’s famous lemonade stall opens this weekend — but her helpers keep making mistakes. She needs a scientist in the kitchen, and she is asking for you.',
    mission: 'Use science to fix Grandma’s lemonade stall.',
    chapters: [
      { minutes: 5, title: 'Float or sink?', scene: 'The ice, a lemon, a spoon and a grape fall into the jug of water.', task: 'Predict which will float and which will sink. Why?', lookFor: 'Ice and lemon float; spoon and grape sink — lighter than water for their size floats.', nudge: 'Think of a boat and a stone. What makes one float?' },
      { minutes: 6, title: 'Where did the sugar go?', scene: 'A helper stirs sugar into the lemonade and it disappears!', task: 'Is the sugar gone? How could you prove it is still there?', lookFor: 'It dissolved — it is still there (taste it, or evaporate the water and sugar crystals are left).', nudge: 'Taste is a clue. What if you let the water dry up in the sun?' },
      { minutes: 6, title: 'Ice that won’t melt', scene: 'On a hot day the ice melts too fast and the lemonade gets warm.', task: 'Suggest two ways to keep the ice from melting so fast, and explain why each works.', lookFor: 'Insulate (a cooler, wrapping in cloth), keep in shade, bigger ice blocks — slow the heat getting in.', nudge: 'Why do we wear a sweater in winter? Could the ice wear one?' },
    ],
    stretch: 'Design a fair test: does salt or sugar dissolve faster in water? What must stay the same?',
    cliffhanger: 'Grandma’s stall needs a sign that lights up at night — but there is no plug outside! Next class we build a circuit with a battery and a bulb.',
    win: 'I used science to fix a lemonade stall: floating, dissolving and keeping things cold.',
    skill: 'Floating and sinking, dissolving, and heat moving (insulation).',
  },
  {
    subject: 'science', grade: 5, emoji: '🌙', title: 'Space Camp', role: 'the young astronaut',
    hook: 'You have been picked for Space Camp! Before you can fly, the trainers test every astronaut on how the Earth, the Moon and the Sun really move.',
    mission: 'Pass the three astronaut tests about day, night, the Moon and the planets.',
    chapters: [
      { minutes: 5, title: 'Day and night', scene: 'The trainer shines a torch (the Sun) on a globe in a dark room.', task: 'Explain why it is night in India when it is day in America.', lookFor: 'The Earth spins; the side facing the Sun has day, the other side night.', nudge: 'Spin the globe slowly. Which parts are lit? Which are dark?' },
      { minutes: 6, title: 'The changing Moon', scene: 'An astronaut notices the Moon looks like a banana one week and a full circle two weeks later.', task: 'Does the Moon really change shape? What is happening?', lookFor: 'No — we see different amounts of its sunlit half as it orbits the Earth.', nudge: 'Hold a ball at arm’s length near a lamp and turn around. What do you see?' },
      { minutes: 6, title: 'How big is space?', scene: 'If the Sun were a football, the Earth would be a peppercorn 25 metres away.', task: 'Where would Jupiter be — nearer or farther? Why do planets far away feel so cold?', lookFor: 'Farther (about 130 m away); less sunlight reaches it, so it is colder.', nudge: 'Stand near a heater, then walk away. What changes?' },
    ],
    stretch: 'Why do we have seasons? (Hint: the Earth is tilted.)',
    cliffhanger: 'Mission control has spotted a strange light moving across the sky — it is not a planet. Next class we find out about satellites, comets and gravity.',
    win: 'I passed Space Camp: I can explain day and night and the phases of the Moon.',
    skill: 'The Earth’s rotation, the Moon’s phases, and the scale of the solar system.',
  },
  {
    subject: 'science', grade: 6, emoji: '💧', title: 'The Clean Water Challenge', role: 'the village water engineer',
    hook: 'A village’s only well has turned muddy after the floods. There is no shop for bottled water for miles — and they have asked for an engineer who knows science. That is you.',
    mission: 'Turn muddy, salty water into water that is safe to drink.',
    chapters: [
      { minutes: 5, title: 'What’s in the water?', scene: 'A jar of well water has mud, leaves, and it tastes a little salty.', task: 'Name each thing mixed in, and say which ones you can see and which you can’t.', lookFor: 'Leaves and mud (insoluble, visible); salt (dissolved, invisible). It is a mixture.', nudge: 'If you leave the jar still for an hour, what will sink to the bottom?' },
      { minutes: 6, title: 'Build a filter', scene: 'You have sand, gravel, cloth, charcoal and a plastic bottle.', task: 'Design a filter: what order do the layers go in, and what does each one catch?', lookFor: 'Gravel then sand then charcoal, cloth at the bottom — big bits caught first, charcoal removes smells.', nudge: 'Which layer should catch the biggest things? Which the smallest?' },
      { minutes: 6, title: 'The salt problem', scene: 'The filtered water is clear — but still salty. The filter cannot catch dissolved salt.', task: 'How could you get pure water out of salty water, using the Sun?', lookFor: 'Evaporation and condensation — heat it so water becomes vapour, cool the vapour on a cold surface and collect it (a solar still).', nudge: 'Where does water go when a puddle dries? Can we catch it?' },
    ],
    stretch: 'Filtered water can still have germs. What else would make it safe to drink?',
    cliffhanger: 'The village needs power for its new water pump — and the only thing they have is wind. Next class we find out how energy changes from one form to another.',
    win: 'I designed a way to turn muddy, salty water into clean water.',
    skill: 'Mixtures, and separating them: sedimentation, filtration, evaporation and condensation.',
  },

  /* ── Physics, Grades 7–12 ───────────────────────────────────────────── */
  {
    subject: 'physics', grade: 7, emoji: '🎢', title: 'Theme Park Engineer', role: 'the ride engineer',
    hook: 'The new theme park opens on Saturday, and three rides have failed their safety checks. The chief engineer has handed you the toolbox and the rulebook.',
    mission: 'Get three rides safe and running using the physics of motion, heat and electricity.',
    chapters: [
      { minutes: 5, title: 'The go-kart track', scene: 'A go-kart covers the 600 m track in 2 minutes. The safety limit is 20 km/h.', task: 'What is the go-kart’s average speed? Is it under the limit?', lookFor: '5 m/s = 18 km/h — under the limit.', nudge: 'Speed = distance ÷ time. Get the time in seconds first.' },
      { minutes: 6, title: 'The hot slide', scene: 'The metal water slide gets too hot to touch in the afternoon sun, but the plastic one doesn’t.', task: 'Why does the metal feel hotter? Suggest a fix.', lookFor: 'Metal conducts heat well (and heats up); plastic is an insulator. Fix: shade, water spray, plastic coating.', nudge: 'Which feels colder on a winter morning: a metal railing or a wooden bench? Why?' },
      { minutes: 6, title: 'The lights', scene: 'The ride has 3 bulbs on one circuit. When one bulb breaks, all the lights go out.', task: 'Why did all the lights go out? Draw a better circuit.', lookFor: 'They are in series — one break stops the current. Parallel wiring keeps the others on.', nudge: 'Trace the path of the current with your finger. What happens at the broken bulb?' },
    ],
    stretch: 'Sketch a distance–time graph for a go-kart that starts, speeds up, then stops at the finish.',
    cliffhanger: 'The big roller coaster keeps stopping just before the loop! Next class we work out how energy and speed get a coaster round a loop.',
    win: 'I fixed three theme-park rides with the physics of speed, heat and circuits.',
    skill: 'Average speed, conductors and insulators of heat, and series vs parallel circuits.',
  },
  {
    subject: 'physics', grade: 8, emoji: '🥚', title: 'The Great Egg Drop', role: 'the rescue-capsule designer',
    hook: 'A drone must drop emergency supplies — including eggs! — to a village cut off by floods. If they break, the mission fails. You are designing the capsule.',
    mission: 'Design a capsule that lands an egg safely, using force, pressure and friction.',
    chapters: [
      { minutes: 5, title: 'Why eggs break', scene: 'An egg dropped on concrete smashes; the same egg dropped on a pillow survives.', task: 'Explain the difference using force and time.', lookFor: 'The pillow makes the egg stop over a longer time, so the force on it is smaller.', nudge: 'Why do you bend your knees when you jump down from a wall?' },
      { minutes: 6, title: 'Pressure points', scene: 'Your capsule must sit on soft mud. A spike-legged design sinks; a flat-bottomed one doesn’t.', task: 'Why? Use the word pressure.', lookFor: 'Pressure = force ÷ area. The flat base spreads the force over a bigger area, so less pressure.', nudge: 'Why are snowshoes wide? Why is a nail pointed?' },
      { minutes: 6, title: 'Slowing the fall', scene: 'You can add a parachute, but the wind might blow the capsule off target.', task: 'How does a parachute slow the capsule? What is the trade-off?', lookFor: 'Air resistance (friction with air) opposes the fall; a bigger chute is slower but drifts more in wind.', nudge: 'Drop a flat sheet of paper and a crumpled one. Which lands first?' },
    ],
    stretch: 'Sound travels about 340 m/s. If you hear the capsule land 0.5 s after seeing it, how far away was it?',
    cliffhanger: 'The villagers radio back: they heard a strange echo when the capsule landed in the valley. Next class we explore sound — echoes, pitch and how bats see in the dark.',
    win: 'I designed an egg capsule using force, pressure and air resistance.',
    skill: 'Force and impact time, pressure = force ÷ area, and friction (air resistance).',
  },
  {
    subject: 'physics', grade: 9, emoji: '🚀', title: 'The Rocket Club', role: 'the rocket club’s chief engineer',
    hook: 'The school rocket club wants to win the national water-rocket contest — but last year’s rocket flipped over and crashed. They need an engineer who understands Newton’s laws.',
    mission: 'Make the water rocket fly straight and high, using forces and energy.',
    chapters: [
      { minutes: 5, title: 'Lift off', scene: 'The bottle rocket pushes water out of the bottom — and shoots up.', task: 'Explain lift-off using Newton’s third law.', lookFor: 'The rocket pushes water down; the water pushes the rocket up with an equal and opposite force.', nudge: 'What happens to you when you push off from a wall on skates?' },
      { minutes: 6, title: 'Heavy or light?', scene: 'The rocket (mass 0.5 kg) gets a 20 N thrust. Gravity pulls it down too (g ≈ 10 m/s²).', task: 'What is the net force, and the rocket’s acceleration?', lookFor: 'Weight 5 N; net 15 N up; a = F/m = 30 m/s².', nudge: 'Find the weight first (m × g). Which way does each force point?' },
      { minutes: 6, title: 'How high?', scene: 'At the top of its flight the rocket stops for a moment, with 0.5 kg of mass.', task: 'If it reached 20 m, how much gravitational potential energy does it have? What speed did it leave with (ignoring air)?', lookFor: 'PE = mgh = 100 J; ½mv² = 100 → v = 20 m/s.', nudge: 'At the top, the kinetic energy has all become potential energy.' },
    ],
    stretch: 'Why does adding fins at the back make the rocket fly straight?',
    cliffhanger: 'The contest judges add a new rule: the rocket must land in a target 50 m away. Next class we tackle projectile motion and gravity’s pull.',
    win: 'I used Newton’s laws and energy to design a better water rocket.',
    skill: 'Newton’s second and third laws, and gravitational potential and kinetic energy.',
  },
  {
    subject: 'physics', grade: 10, emoji: '💡', title: 'The Light Show', role: 'the festival’s lighting designer',
    hook: 'The city’s Diwali light festival is tonight, and the lighting designer has quit! Mirrors, lenses and a whole street of lights are waiting for you.',
    mission: 'Design the light show: bend the beams, focus the spotlights, and keep the power safe.',
    chapters: [
      { minutes: 5, title: 'Mirror maze', scene: 'A laser must bounce off a mirror to hit a target on the stage.', task: 'If the beam hits the mirror at 35° to the normal, at what angle does it leave?', lookFor: '35° — the angle of reflection equals the angle of incidence.', nudge: 'Draw the normal (a line at 90° to the mirror). Measure both angles from it.' },
      { minutes: 6, title: 'The spotlight', scene: 'A convex lens has focal length 20 cm. The bulb sits 30 cm from the lens.', task: 'Where does the image form? (1/v − 1/u = 1/f)', lookFor: 'u = −30, f = 20 → 1/v = 1/20 − 1/30 = 1/60, v = 60 cm on the other side.', nudge: 'Use the sign convention: the object is on the left, so u is negative.' },
      { minutes: 6, title: 'Don’t blow the fuse', scene: 'Each light string is 60 W on 240 V. The fuse is 5 A.', task: 'How many strings can run together safely?', lookFor: 'I = P/V = 0.25 A each; 5 ÷ 0.25 = 20 strings.', nudge: 'Find the current one string draws. How many fit under 5 A?' },
    ],
    stretch: 'Why does a pencil look bent in a glass of water? Name the effect and what causes it.',
    cliffhanger: 'Halfway through the show, the stage turns every colour into a rainbow smear — someone put a prism in the beam! Next class we split white light and explain rainbows and the blue sky.',
    win: 'I designed a festival light show with mirrors, lenses and safe circuits.',
    skill: 'Laws of reflection, the lens formula, and electric power (P = VI).',
  },
  {
    subject: 'physics', grade: 11, emoji: '🏍️', title: 'The Stunt Double', role: 'the stunt coordinator',
    hook: 'A film crew is shooting a motorbike jump across a canyon tomorrow. The stunt coordinator must sign off the maths — or the jump is cancelled. You have the pen.',
    mission: 'Make sure the jump is safe with kinematics, projectile motion and momentum.',
    chapters: [
      { minutes: 5, title: 'The run-up', scene: 'The bike starts from rest and accelerates at 4 m/s² along a 50 m ramp.', task: 'How fast is it going at the edge?', lookFor: 'v² = u² + 2as = 400 → v = 20 m/s.', nudge: 'You know u, a and s. Which equation of motion connects them to v?' },
      { minutes: 6, title: 'Across the canyon', scene: 'The bike leaves horizontally at 20 m/s. The far side is 5 m lower. (g = 10 m/s²)', task: 'How long is the bike in the air, and how far does it travel across? The gap is 18 m.', lookFor: '5 = ½ × 10 × t² → t = 1 s; 20 m across — it clears the 18 m gap.', nudge: 'Treat vertical and horizontal motion separately. Which one decides the time in the air?' },
      { minutes: 6, title: 'The crash mat', scene: 'Rider plus bike weigh 200 kg and land moving at 22 m/s.', task: 'What is their momentum? If the mat stops them in 2 s, what is the average force?', lookFor: 'p = 4,400 kg m/s; F = Δp/Δt = 2,200 N.', nudge: 'Force is the rate of change of momentum.' },
    ],
    stretch: 'If the ramp is angled at 15° up instead of level, will the bike go farther or not as far? Why?',
    cliffhanger: 'The director wants a new shot: a car loop-the-loop. Next class we find the minimum speed to stay on the track at the top — circular motion.',
    win: 'I signed off a motorbike canyon jump with real physics.',
    skill: 'Equations of motion, projectile motion, and momentum and impulse.',
  },
  {
    subject: 'physics', grade: 12, emoji: '⚡', title: 'Keep the Lights On', role: 'the power-grid engineer',
    hook: 'A heatwave has hit the city and every air conditioner is on. The grid is about to fail, and the control room needs a physicist on shift tonight. That is you.',
    mission: 'Keep the city powered: circuits, transformers and generators.',
    chapters: [
      { minutes: 5, title: 'The overloaded line', scene: 'A cable has resistance 0.5 Ω and carries 200 A.', task: 'How much power is lost as heat in the cable?', lookFor: 'P = I²R = 20,000 W = 20 kW lost.', nudge: 'Which power formula uses current and resistance only?' },
      { minutes: 6, title: 'Why high voltage?', scene: 'The same power could be sent at 11 kV or at 220 kV.', task: 'Why do grids use very high voltage? Use your chapter 1 answer.', lookFor: 'For the same power, higher V means lower I, and heat loss ∝ I² — losses drop hugely.', nudge: 'P = VI. If V goes up 20 times, what happens to I, and to I²R?' },
      { minutes: 6, title: 'The transformer', scene: 'A transformer steps 220 kV down to 11 kV. The secondary coil has 500 turns.', task: 'How many turns does the primary coil have? Why won’t it work on DC?', lookFor: '10,000 turns (Vp/Vs = Np/Ns); it needs a changing magnetic field — only AC gives that (induction).', nudge: 'The voltage ratio equals the turns ratio.' },
    ],
    stretch: 'A generator coil spins in a magnetic field. What happens to the voltage if it spins twice as fast? Why?',
    cliffhanger: 'At 2 a.m. a solar farm comes online — but the sun has gone down! Next class we store energy with capacitors and batteries and look at the physics of the future grid.',
    win: 'I kept a city powered using the physics of circuits and transformers.',
    skill: 'Power loss (I²R), high-voltage transmission, transformers and electromagnetic induction.',
  },

  /* ── Chemistry, Grades 7–12 ─────────────────────────────────────────── */
  {
    subject: 'chemistry', grade: 7, emoji: '🧙', title: 'The Colour-Changing Potion', role: 'the potion master',
    hook: 'A magician’s show needs a potion that changes colour on stage — but the magician does not know it is really chemistry. You do, and the show is tonight.',
    mission: 'Make colour changes on cue using acids, bases and indicators.',
    chapters: [
      { minutes: 5, title: 'Sour or bitter?', scene: 'On the table: lemon juice, soap water, vinegar, baking soda water and plain water.', task: 'Sort them into acids, bases and neutral. What clues help?', lookFor: 'Acids: lemon juice, vinegar (sour). Bases: soap water, baking soda (bitter, soapy). Neutral: water.', nudge: 'Which taste sour? Which feel slippery?' },
      { minutes: 6, title: 'The turmeric trick', scene: 'A white cloth is painted with turmeric (yellow). A drop of soap water turns it red!', task: 'Which of the liquids would also turn it red? Why?', lookFor: 'Baking soda water — bases turn turmeric red; acids leave it yellow.', nudge: 'Soap water is a base. What else on the table is a base?' },
      { minutes: 6, title: 'Back to normal', scene: 'The magician wants the red cloth to turn yellow again for the finale.', task: 'What should he add, and what is happening?', lookFor: 'An acid, like lemon juice or vinegar — neutralisation cancels the base.', nudge: 'What is the opposite of a base?' },
    ],
    stretch: 'Why do people take an antacid for a stomach ache? Explain with neutralisation.',
    cliffhanger: 'Backstage, a bottle labelled “DO NOT MIX” has been knocked over — and it is fizzing. Next class we find out what happens when chemicals react and how to tell.',
    win: 'I made a colour-changing potion with acids, bases and indicators.',
    skill: 'Acids, bases and neutral substances, natural indicators and neutralisation.',
  },
  {
    subject: 'chemistry', grade: 8, emoji: '🚒', title: 'The Fire Station Chemist', role: 'the fire station’s chemist',
    hook: 'The fire station is training new firefighters, and they need someone to explain WHY fire behaves the way it does. The chief has picked you.',
    mission: 'Explain how fire starts, how to stop it, and which fuel is safest.',
    chapters: [
      { minutes: 5, title: 'The fire triangle', scene: 'A candle burns in a room. A glass jar is placed over it and the flame goes out.', task: 'What three things does fire need? Which one did the jar remove?', lookFor: 'Fuel, oxygen and heat — the jar cut off the oxygen.', nudge: 'What is inside the jar at the start that runs out?' },
      { minutes: 6, title: 'Water or not?', scene: 'A pan of oil catches fire in a kitchen. Someone reaches for a bucket of water.', task: 'Should they throw water? What should they do instead, and why?', lookFor: 'No — water sinks under oil and splashes burning oil. Cover the pan (remove oxygen) or use a CO₂/foam extinguisher.', nudge: 'Oil floats on water. What happens to the burning oil if water goes under it?' },
      { minutes: 6, title: 'The best fuel', scene: 'The station compares fuels: wood, coal, LPG. LPG gives 50 kJ/g, wood about 17 kJ/g.', task: 'Which is the better fuel, and why — think of heat, smoke and ash.', lookFor: 'LPG — more heat per gram, burns cleanly, little smoke or ash.', nudge: 'What makes a fuel “good”? Think about what you want and don’t want.' },
    ],
    stretch: 'Why does a match not catch fire on its own, but does when you strike it? (Ignition temperature.)',
    cliffhanger: 'A firefighter’s helmet has turned green and flaky after years of use. Next class we find out what metals and non-metals do when they react — and how to stop corrosion.',
    win: 'I explained fire like a chemist: the fire triangle, safe firefighting and the best fuel.',
    skill: 'Combustion, the fire triangle, extinguishing fires and fuel efficiency.',
  },
  {
    subject: 'chemistry', grade: 9, emoji: '🧂', title: 'The Mystery Powder', role: 'the forensic chemist',
    hook: 'A bag of white powder has been found at the airport, and security needs to know what it is — fast. The lab is yours.',
    mission: 'Identify the powder and separate it, using what matter is made of.',
    chapters: [
      { minutes: 5, title: 'Pure or mixture?', scene: 'Under the microscope the powder has two kinds of crystals: shiny cubes and tiny grains.', task: 'Is it a pure substance or a mixture? How could you tell for sure?', lookFor: 'A mixture — two kinds of particles; a pure substance has one fixed melting point.', nudge: 'If it were pure, would all the crystals look the same?' },
      { minutes: 6, title: 'Separate it', scene: 'You suspect salt mixed with sand-like chalk.', task: 'Plan the steps to get pure salt out.', lookFor: 'Dissolve in water, filter off the chalk, evaporate the water to get salt crystals.', nudge: 'Which one dissolves in water? How can you get it back out of the water?' },
      { minutes: 6, title: 'Counting atoms', scene: 'Salt is NaCl. Na has mass 23, Cl has mass 35.5.', task: 'What is the mass of one mole of salt? How many moles in 117 g?', lookFor: 'Molar mass 58.5 g; 117 ÷ 58.5 = 2 mol.', nudge: 'Add the atomic masses for one formula unit.' },
    ],
    stretch: 'How many sodium ions are in 2 moles of salt? (Avogadro’s number ≈ 6.02 × 10²³.)',
    cliffhanger: 'A second bag has arrived — and this one glows under UV light. Next class we look inside the atom itself to find out why.',
    win: 'I identified and separated a mystery powder, and counted its atoms in moles.',
    skill: 'Pure substances vs mixtures, separation techniques, and the mole.',
  },
  {
    subject: 'chemistry', grade: 10, emoji: '🚢', title: 'The Rusty Ship', role: 'the shipyard’s chemist',
    hook: 'An old ship is being restored as a museum — but rust is eating through the hull. The shipyard has hired a chemist to stop it. You start today.',
    mission: 'Understand rusting as a reaction, and protect the ship.',
    chapters: [
      { minutes: 5, title: 'What is rust?', scene: 'Three iron nails: one in dry air, one in water with air, one in boiled water under oil.', task: 'Which rusts? What two things does rusting need?', lookFor: 'Only the one with water AND air — rusting needs oxygen and water.', nudge: 'What is missing in the first tube? In the third?' },
      { minutes: 6, title: 'Write the reaction', scene: 'Iron reacts with oxygen to make iron(III) oxide: Fe + O₂ → Fe₂O₃.', task: 'Balance the equation. Is iron oxidised or reduced?', lookFor: '4Fe + 3O₂ → 2Fe₂O₃; iron is oxidised (it gains oxygen / loses electrons).', nudge: 'Balance the oxygen first with the smallest numbers, then fix the iron.' },
      { minutes: 6, title: 'Save the hull', scene: 'The engineers suggest paint, zinc coating, or bolting blocks of zinc to the hull.', task: 'Explain how the zinc blocks protect the iron even where the paint is scratched.', lookFor: 'Zinc is more reactive, so it corrodes instead of the iron (sacrificial protection).', nudge: 'Which metal is higher in the reactivity series, and what does that mean?' },
    ],
    stretch: 'Why does rust happen faster by the sea than in the desert?',
    cliffhanger: 'Inside the ship the team found an old battery that still works after 80 years. Next class we find out how reactions make electricity.',
    win: 'I stopped a ship rusting using real chemical reactions.',
    skill: 'Oxidation and rusting, balancing equations, and the reactivity series.',
  },
  {
    subject: 'chemistry', grade: 11, emoji: '🧴', title: 'The Perfume Lab', role: 'the head chemist of a perfume startup',
    hook: 'A new perfume brand launches next month, and the first batch came out wrong — too strong and it faded in an hour. The founders need a chemist who can do the maths.',
    mission: 'Fix the perfume formula with moles, concentration and gas behaviour.',
    chapters: [
      { minutes: 5, title: 'Too strong', scene: 'The recipe needs 0.1 mol of fragrance oil (molar mass 150 g/mol) per bottle, but 30 g was added.', task: 'How many moles were added? How much too strong is it?', lookFor: '30 ÷ 150 = 0.2 mol — twice as strong as it should be.', nudge: 'Moles = mass ÷ molar mass.' },
      { minutes: 6, title: 'Dilute it', scene: 'The perfume must be 0.5 mol/L. You have 200 mL at 2.0 mol/L.', task: 'How much will you end up with after diluting to the right strength?', lookFor: 'C₁V₁ = C₂V₂ → 2.0 × 200 = 0.5 × V₂ → V₂ = 800 mL (add 600 mL).', nudge: 'The amount of fragrance stays the same when you add solvent.' },
      { minutes: 6, title: 'Why it fades', scene: 'On warm skin the perfume evaporates in an hour; in a cool room it lasts all day.', task: 'Explain with particles and temperature.', lookFor: 'Higher temperature gives particles more kinetic energy, so more escape into the gas — faster evaporation.', nudge: 'What happens to particles when they are heated?' },
    ],
    stretch: 'At 27°C a scent vapour occupies 2 L. At 57°C (same pressure) what volume? (Charles’s law, in kelvin.)',
    cliffhanger: 'Customers love the scent — but chemists at a rival company say it is “just an ester”. Next class we find out what that means and make one on paper.',
    win: 'I fixed a perfume formula with moles, dilution and the particle model.',
    skill: 'The mole, concentration and dilution, and kinetic theory.',
  },
  {
    subject: 'chemistry', grade: 12, emoji: '🔋', title: 'The Battery Startup', role: 'the battery chemist',
    hook: 'A startup wants to build batteries for electric rickshaws — cheaper and longer-lasting than anything on the market. Investors meet on Friday. They need a chemist today.',
    mission: 'Design a better battery using electrochemistry and reaction rates.',
    chapters: [
      { minutes: 5, title: 'Pick the metals', scene: 'Standard potentials: Zn²⁺/Zn = −0.76 V, Cu²⁺/Cu = +0.34 V, Ag⁺/Ag = +0.80 V.', task: 'Which pair gives the highest voltage? What is it?', lookFor: 'Zn and Ag: 0.80 − (−0.76) = 1.56 V.', nudge: 'E°cell = E°(cathode) − E°(anode). Pick the two furthest apart.' },
      { minutes: 6, title: 'Which way do electrons go?', scene: 'In the Zn–Cu cell, one electrode dissolves and the other gets coated.', task: 'Which is the anode? Write the half-reaction at each electrode.', lookFor: 'Zn anode: Zn → Zn²⁺ + 2e⁻ (oxidation); Cu cathode: Cu²⁺ + 2e⁻ → Cu (reduction).', nudge: 'Oxidation happens at the anode. Which metal loses electrons more easily?' },
      { minutes: 6, title: 'The cold-morning problem', scene: 'Drivers report weak batteries on cold winter mornings.', task: 'Explain why, using reaction rates.', lookFor: 'Lower temperature means fewer particles with enough energy to react (activation energy), so a slower reaction and less current.', nudge: 'What does temperature do to how often particles collide with enough energy?' },
    ],
    stretch: 'Use the Nernst idea: what happens to the cell voltage as the battery runs down and ion concentrations change?',
    cliffhanger: 'The investors love it — but ask how long the battery will last before it degrades. Next class we model it with reaction kinetics and half-lives.',
    win: 'I designed a battery with electrochemistry and explained the cold-morning problem.',
    skill: 'Electrode potentials, cell reactions, and the effect of temperature on rate.',
  },

  /* ── Biology, Grades 7–12 ───────────────────────────────────────────── */
  {
    subject: 'biology', grade: 7, emoji: '🪴', title: 'The Plant Clinic', role: 'the plant doctor',
    hook: 'A rooftop farm in the city is losing its plants — leaves going pale, stems drooping. The farmers have called a plant doctor. Your first patient is waiting.',
    mission: 'Diagnose the sick plants using how plants make and use food.',
    chapters: [
      { minutes: 5, title: 'The pale leaves', scene: 'Plants kept under a shade cloth for two weeks have pale, weak leaves.', task: 'What process is failing, and what does it need?', lookFor: 'Photosynthesis — needs sunlight, water, CO₂ and chlorophyll to make glucose.', nudge: 'How does a plant make its food? What is missing under the shade?' },
      { minutes: 6, title: 'The starch test', scene: 'A leaf half-covered with foil for a day is tested with iodine. Only the uncovered half turns blue-black.', task: 'What does the colour show?', lookFor: 'Starch was made only in the part that got light — light is needed for photosynthesis.', nudge: 'Iodine shows starch. Where was the starch made?' },
      { minutes: 6, title: 'Night breathing', scene: 'A farmer says: “Plants give out oxygen, so keep them in the bedroom at night!”', task: 'Is that right at night? Explain.', lookFor: 'At night there is no photosynthesis; plants only respire — they take in O₂ and give out CO₂.', nudge: 'Do plants breathe? What happens when the light goes?' },
    ],
    stretch: 'Why do plants in water-logged soil wilt, even though they have plenty of water? (Roots need oxygen.)',
    cliffhanger: 'Now insects are chewing holes in the lettuce, and a strange fungus is spreading. Next class we meet the microorganisms — the good ones and the bad ones.',
    win: 'I diagnosed sick plants using photosynthesis and respiration.',
    skill: 'Photosynthesis, the starch test, and respiration in plants.',
  },
  {
    subject: 'biology', grade: 8, emoji: '🦠', title: 'Microbe Hunters', role: 'the microbe hunter',
    hook: 'A school canteen has had three students fall sick in one week. The health department has sent a microbe hunter to find the cause. That is you.',
    mission: 'Track down the harmful microbe and stop it spreading.',
    chapters: [
      { minutes: 5, title: 'Friend or foe?', scene: 'The canteen uses yeast for bread, curd in the lunches, and there is a mouldy loaf in the bin.', task: 'Which microbes are helpful here, and which could be harmful?', lookFor: 'Yeast (bread rises) and bacteria in curd are helpful; mould on old bread can be harmful.', nudge: 'Which microbes make food? Which spoil it?' },
      { minutes: 6, title: 'Follow the germs', scene: 'All three sick students ate the chicken salad, which was left out in the sun for 4 hours.', task: 'Why did leaving it out matter? What should the canteen do?', lookFor: 'Warmth lets bacteria multiply fast; refrigerate food, cook properly, wash hands.', nudge: 'Do bacteria grow faster in a fridge or in the sun?' },
      { minutes: 6, title: 'The vaccine question', scene: 'A parent asks: “How does a vaccine stop my child from getting sick?”', task: 'Explain it simply, like a doctor to a parent.', lookFor: 'A vaccine shows the body a harmless version of the germ, so the immune system makes antibodies and remembers it.', nudge: 'Think of a practice fire drill. How does practising help?' },
    ],
    stretch: 'Why don’t antibiotics work against a cold (a virus)?',
    cliffhanger: 'Under the microscope, the germ’s cell looks nothing like our cells. Next class we zoom right into cells and find out what makes each kind different.',
    win: 'I tracked down a food-poisoning microbe and explained how vaccines work.',
    skill: 'Useful and harmful microorganisms, food safety, and vaccination.',
  },
  {
    subject: 'biology', grade: 9, emoji: '🏙️', title: 'Cell City', role: 'the mayor of Cell City',
    hook: 'Cell City has 37 trillion citizens — you. It runs perfectly, until today, when the power plant, the control room and the delivery service all report problems. The mayor must act.',
    mission: 'Run Cell City: match every department to its organelle and fix the problems.',
    chapters: [
      { minutes: 5, title: 'Who does what?', scene: 'The city has a control room, power plants, a factory for proteins, a delivery system and a city wall.', task: 'Match each to its organelle.', lookFor: 'Nucleus (control), mitochondria (power), ribosomes (proteins), ER/Golgi (delivery), cell membrane (wall/gate).', nudge: 'Which part holds the instructions (DNA)? Where is energy released?' },
      { minutes: 6, title: 'The power cut', scene: 'Muscle cells are tired and slow. Scientists find fewer mitochondria in them.', task: 'Why would that make muscles tired?', lookFor: 'Mitochondria carry out respiration to release energy (ATP); fewer mitochondria, less energy.', nudge: 'What do mitochondria make, and what do muscles need to move?' },
      { minutes: 6, title: 'Plant town', scene: 'A neighbouring town is a plant cell. It has walls, green factories and a big water tank.', task: 'Name three things a plant cell has that an animal cell does not, and why each helps.', lookFor: 'Cell wall (support), chloroplasts (photosynthesis), large vacuole (stores water, keeps the cell firm).', nudge: 'Plants stand up without bones and make their own food. How?' },
    ],
    stretch: 'Why are red blood cells shaped like dimples, with no nucleus?',
    cliffhanger: 'Cells in one part of the city have started dividing out of control. Next class we find out how cells divide — and what happens when it goes wrong.',
    win: 'I ran Cell City and explained what each organelle does.',
    skill: 'Cell organelles and their jobs, and plant vs animal cells.',
  },
  {
    subject: 'biology', grade: 10, emoji: '🧬', title: 'The Family Mystery', role: 'the genetic counsellor',
    hook: 'Two brown-eyed parents have a blue-eyed baby — and the grandparents are arguing about how that is even possible. The family has asked a genetic counsellor to explain. That is you.',
    mission: 'Solve the eye-colour mystery with Mendel’s rules of inheritance.',
    chapters: [
      { minutes: 5, title: 'Dominant and recessive', scene: 'Brown eyes (B) are dominant; blue eyes (b) are recessive.', task: 'What genes could each brown-eyed parent have? What must the blue-eyed baby have?', lookFor: 'Parents BB or Bb; the baby must be bb — so both parents must be Bb.', nudge: 'To show a recessive trait, how many copies of b do you need?' },
      { minutes: 6, title: 'The Punnett square', scene: 'Both parents are Bb.', task: 'Draw a Punnett square. What is the chance of a blue-eyed child?', lookFor: 'BB, Bb, Bb, bb — 1 in 4 (25%) blue eyes.', nudge: 'Put one parent’s genes across the top and the other’s down the side.' },
      { minutes: 6, title: 'Boy or girl?', scene: 'The grandparents also ask: “Is it the mother who decides if the baby is a boy or a girl?”', task: 'Explain what decides the sex of a baby.', lookFor: 'The father’s sperm carries X or Y; the mother always gives X. XX is a girl, XY is a boy.', nudge: 'What sex chromosomes does each parent have?' },
    ],
    stretch: 'If the blue-eyed child grows up and has children with a BB partner, what colour eyes will their children have?',
    cliffhanger: 'A rare condition skips two generations in the same family tree. Next class we read pedigree charts and find out how.',
    win: 'I solved a family’s eye-colour mystery with Punnett squares.',
    skill: 'Dominant and recessive alleles, Punnett squares, and sex determination.',
  },
  {
    subject: 'biology', grade: 11, emoji: '🏃', title: 'Marathon Body', role: 'the sports physiologist',
    hook: 'A runner is training for her first marathon — and hits a wall at 30 km every time. Her coach has brought in a physiologist to find out what her body is doing. That is you.',
    mission: 'Explain what happens inside a runner’s body, and fix her race plan.',
    chapters: [
      { minutes: 5, title: 'Out of breath', scene: 'During a sprint, the runner’s breathing and heart rate shoot up.', task: 'Why does the body do this? Trace oxygen from the air to her leg muscles.', lookFor: 'Muscles need more O₂ for aerobic respiration: lungs → alveoli → blood (haemoglobin) → heart → arteries → muscle.', nudge: 'What do muscles need more of when they work hard? How does it get there?' },
      { minutes: 6, title: 'The burning legs', scene: 'In the final sprint, her legs burn and she has to slow down.', task: 'What happens when there is not enough oxygen?', lookFor: 'Anaerobic respiration: glucose → lactic acid (lactate), little energy, fatigue; an oxygen debt afterwards.', nudge: 'Can muscles release energy without oxygen? What is the cost?' },
      { minutes: 6, title: 'Hitting the wall', scene: 'At 30 km she runs out of energy, though she ate a big breakfast.', task: 'What has run out, and how should she change her race plan?', lookFor: 'Glycogen stores in muscles and liver; take carbohydrate during the race and pace herself.', nudge: 'Where does the body store glucose for quick use?' },
    ],
    stretch: 'Why do athletes train at high altitude before big races? (Red blood cells.)',
    cliffhanger: 'Her blood test shows something unusual about her hormones on race day. Next class we find out how the endocrine system controls the body under stress.',
    win: 'I explained a marathon runner’s body and fixed her race plan.',
    skill: 'Gas exchange and circulation, aerobic and anaerobic respiration, and glycogen.',
  },
  {
    subject: 'biology', grade: 12, emoji: '🔬', title: 'The DNA Detective', role: 'the forensic geneticist',
    hook: 'A 30-year-old case has been reopened: a single hair was found at the scene. The police lab has just enough DNA — and one chance to get it right. You are the geneticist.',
    mission: 'Copy, read and match the DNA to solve the case.',
    chapters: [
      { minutes: 5, title: 'Too little DNA', scene: 'The hair holds only a few copies of DNA — not enough to test.', task: 'How can you make millions of copies? Name the three temperature steps.', lookFor: 'PCR: denature (~95°C), anneal primers (~55°C), extend with Taq polymerase (~72°C), repeated in cycles.', nudge: 'The DNA is double-stranded. What must happen to it before it can be copied?' },
      { minutes: 6, title: 'How many copies?', scene: 'Each PCR cycle doubles the DNA. You start with 10 copies.', task: 'How many copies after 20 cycles?', lookFor: '10 × 2²⁰ ≈ 10 million copies.', nudge: 'Doubling 20 times is multiplying by 2 twenty times.' },
      { minutes: 6, title: 'The match', scene: 'Gel electrophoresis shows the band pattern from the hair and from three suspects.', task: 'How does the gel separate DNA, and how do you decide there is a match?', lookFor: 'DNA is negative and moves to the positive end; smaller fragments move farther. A match has the same band positions at every marker.', nudge: 'Why would small pieces travel farther through a gel?' },
    ],
    stretch: 'Why can DNA from identical twins not tell them apart, but fingerprints can?',
    cliffhanger: 'The DNA matches no suspect — but it matches a family in a genealogy database. Next class we use inheritance patterns to trace the family tree.',
    win: 'I used PCR and gel electrophoresis to solve a cold case.',
    skill: 'PCR, exponential amplification and gel electrophoresis — biotechnology.',
  },
];
