import type { Story } from './types';

/** Public Speaking by age (Grades 2, 5, 8, 11 and grown-ups), and one story for each focus course. */
export const SPEAKING_FOCUS_STORIES: Story[] = [
  /* ── Public Speaking ─────────────────────────────────────────────────── */
  {
    subject: 'public-speaking', grade: 2, emoji: '🧸', title: 'Show-and-Tell Superstar', role: 'the show-and-tell star',
    hook: 'It is Show-and-Tell day on the Moon School, and the aliens have never seen anything from Earth! You get to show them one thing — and make them love it.',
    mission: 'Tell the aliens about one favourite thing, loudly and clearly.',
    chapters: [
      { minutes: 5, title: 'Pick your treasure', scene: 'The aliens are waiting. What will you show them?', task: 'Choose one thing from your room. Say its name and one reason you love it.', lookFor: 'One clear sentence: “This is my teddy, and I love him because he’s soft.”', nudge: 'Hold it up! What is it called? Why is it special?' },
      { minutes: 6, title: 'Big voice, slow words', scene: 'The aliens are at the back of the Moon hall — they can’t hear a whisper!', task: 'Say your sentence again with a big, slow voice, looking at the camera.', lookFor: 'Louder, slower, eyes on the camera — the child notices the difference.', nudge: 'Pretend the aliens are far, far away. Can your voice reach them?' },
      { minutes: 6, title: 'Three things', scene: 'The aliens want to know MORE about your treasure.', task: 'Tell them three things: what it looks like, where you got it, and what you do with it.', lookFor: 'Three details in order — a first mini-talk with a beginning and an end.', nudge: 'First, what does it look like? Then… where did it come from?' },
    ],
    stretch: 'Finish with a question for the aliens: “What is YOUR favourite thing?”',
    cliffhanger: 'The aliens loved it — and they have invited you to be the storyteller at their Moon festival! Next class we learn how to tell a story that makes people gasp.',
    win: 'I did a show-and-tell for aliens with a big, clear voice.',
    skill: 'Speaking clearly and loudly, eye contact, and a first three-part talk.',
  },
  {
    subject: 'public-speaking', grade: 5, emoji: '📻', title: 'The School Radio Show', role: 'the radio host',
    hook: 'The school is starting its own radio station — “Sariro FM” — and the first host goes live on Monday. The producer wants to hear your audition.',
    mission: 'Host a 1-minute radio segment that keeps listeners listening.',
    chapters: [
      { minutes: 5, title: 'The welcome', scene: 'Radio has no pictures — only your voice.', task: 'Write and say a welcome line with energy: who you are and what’s coming up.', lookFor: 'An energetic, friendly opener — e.g. “Good morning, Sariro! I’m Kabir, and today we’ve got…”', nudge: 'Smile while you talk — listeners can hear it!' },
      { minutes: 6, title: 'Paint with your voice', scene: 'Your segment is about the school sports day.', task: 'Describe one moment so listeners can picture it — use pace and pauses.', lookFor: 'Changes of speed and a dramatic pause at the key moment.', nudge: 'Slow down for the exciting part. Pause… just before the winner.' },
      { minutes: 6, title: 'No “umm”s', scene: 'The producer counted 11 “umm”s in the last audition.', task: 'Say your segment again, replacing every “umm” with a short silent pause.', lookFor: 'Fewer fillers; pauses used on purpose.', nudge: 'When you feel an “umm” coming, close your mouth and breathe instead.' },
    ],
    stretch: 'Interview a “guest” (your teacher) with two questions that get more than a yes/no answer.',
    cliffhanger: 'Sariro FM is a hit — and the principal wants you to host the Annual Day, live on stage! Next class we learn how to hold a real audience.',
    win: 'I hosted a radio segment with energy, pace and no “umm”s.',
    skill: 'Vocal energy, pace and pausing, and cutting filler words.',
  },
  {
    subject: 'public-speaking', grade: 8, emoji: '🗳️', title: 'The Student Council Election', role: 'the candidate',
    hook: 'Student council elections are in one week. Each candidate gets a 90-second speech in the assembly. Your opponent is funny and popular. You need to be better.',
    mission: 'Write and deliver a campaign speech that wins votes.',
    chapters: [
      { minutes: 5, title: 'The opening', scene: '600 students, half of them half-asleep.', task: 'Write an opening that wakes them up: a question, a surprising fact or a quick story.', lookFor: 'A hook that is about THEM, e.g. “Hands up if you’ve ever waited 20 minutes in the canteen line.”', nudge: 'What problem does every student in the hall share?' },
      { minutes: 6, title: 'Three promises', scene: 'Voters remember three things, not ten.', task: 'Choose three promises and say each in one sentence with a reason.', lookFor: 'Three specific, believable promises with a “because”.', nudge: 'What would actually make school better? Why would it work?' },
      { minutes: 6, title: 'Stand and deliver', scene: 'You practise in front of the camera.', task: 'Deliver the speech standing, with eye contact, open hands and a strong final line.', lookFor: 'Posture, eye contact, gestures that match words, and a memorable close (“Vote for change — vote for …”).', nudge: 'Where do your hands go when you talk to a friend? Let them move like that.' },
    ],
    stretch: 'Your opponent says your promises are impossible. Answer in 20 seconds, calmly.',
    cliffhanger: 'The school has announced a live debate between the two final candidates. Next class we learn to think on our feet and answer tough questions.',
    win: 'I wrote and delivered a campaign speech with a hook and three promises.',
    skill: 'Audience-centred openings, structure (rule of three) and confident body language.',
  },
  {
    subject: 'public-speaking', grade: 11, emoji: '🎙️', title: 'The TEDx Stage', role: 'the TEDx speaker',
    hook: 'Your city’s TEDx has one slot for a student. The organisers want a talk that changes how people think. You have 8 minutes on stage, and 400 people in the dark.',
    mission: 'Build and deliver the opening two minutes of a talk that moves a room.',
    chapters: [
      { minutes: 5, title: 'The first 30 seconds', scene: 'The spotlight comes on. Nobody knows who you are.', task: 'Open with a story in the present tense — a single moment, no introduction.', lookFor: '“It’s 6 a.m., and I’m standing at the bus stop…” — straight into a scene.', nudge: 'Skip “Hi, my name is”. Start in the middle of the moment.' },
      { minutes: 6, title: 'The idea', scene: 'Great talks have one idea, said in one sentence.', task: 'State your idea in under 15 words, then give one reason and one example.', lookFor: 'A clear, surprising one-line idea supported by reason and example.', nudge: 'If the audience remembers only one sentence, what should it be?' },
      { minutes: 6, title: 'The delivery', scene: 'You practise the two minutes on camera.', task: 'Deliver it using pauses for emphasis, vocal variety and purposeful movement.', lookFor: 'Deliberate pauses after key lines, changes in pitch/pace, stillness when it matters.', nudge: 'After your big line, stop. Count to two in your head. Let it land.' },
    ],
    stretch: 'Handle the unexpected: your slides fail mid-talk. What do you say?',
    cliffhanger: 'The organisers loved your opening — and want the full talk, with a Q&A from the audience. Next class we build the full arc and practise handling hostile questions.',
    win: 'I opened a TEDx talk with a story, one big idea and a confident delivery.',
    skill: 'Narrative openings, a single clear message, and vocal delivery.',
  },
  {
    subject: 'public-speaking', grade: 13, emoji: '💼', title: 'The Big Pitch', role: 'the presenter',
    hook: 'You have 3 minutes with the leadership team to pitch an idea you care about. Half of them are on their phones before you start. By the end, you want a yes.',
    mission: 'Pitch an idea so clearly and confidently that it gets approved.',
    chapters: [
      { minutes: 5, title: 'Start with the problem', scene: 'Most pitches start with the solution. Busy people need to feel the problem first.', task: 'Open with the problem in one sentence, with a number that makes it real.', lookFor: 'A specific, costed problem: “We lose 40 hours a week re-typing invoices.”', nudge: 'What does the problem cost — in time, money or people?' },
      { minutes: 6, title: 'The ask', scene: 'Leaders decide faster when they know exactly what you want.', task: 'State your solution and your specific ask in two sentences.', lookFor: 'Solution + a clear ask (budget, time, a pilot) — no vagueness.', nudge: 'What exactly do you want them to say yes to?' },
      { minutes: 6, title: 'Handle the objection', scene: 'The finance head interrupts: “We tried something like this before and it failed.”', task: 'Respond in 30 seconds: acknowledge, differentiate, return to the ask.', lookFor: 'Calm acknowledgement, what is different now, and a return to the ask — without getting defensive.', nudge: 'Start with “That’s a fair point…”, then say what is different this time.' },
    ],
    stretch: 'Cut your whole pitch to 30 seconds for when the meeting runs late.',
    cliffhanger: 'They said yes — to a pilot. Now you must present the results to the whole company in a month. Next class we build a data story that keeps a big room with you.',
    win: 'I pitched an idea with a clear problem, a clear ask and a calm answer to an objection.',
    skill: 'Problem-first framing, a concrete ask, and handling objections.',
  },

  /* ── Focus courses ───────────────────────────────────────────────────── */
  {
    subject: 'algebra-1', grade: 9, emoji: '📱', title: 'The Phone Plan Battle', role: 'the family’s money adviser',
    hook: 'Your family is choosing a phone plan, and the two companies are both shouting “best deal!”. Only algebra can say who is telling the truth.',
    mission: 'Use linear equations to find the plan that is really cheaper.',
    chapters: [
      { minutes: 5, title: 'Write the rules', scene: 'Plan A: ₹200 a month plus ₹2 per GB. Plan B: ₹350 a month plus ₹0.50 per GB.', task: 'Write each plan’s monthly cost as an equation in g (GB used).', lookFor: 'A = 200 + 2g; B = 350 + 0.5g.', nudge: 'What is the cost if you use no data? What gets added for each GB?' },
      { minutes: 6, title: 'The break-even', scene: 'At some usage both plans cost the same.', task: 'Find it by solving the equations.', lookFor: '200 + 2g = 350 + 0.5g → g = 100 GB (both cost ₹400).', nudge: 'Set the two costs equal and solve for g.' },
      { minutes: 6, title: 'The graph', scene: 'Your parents want a picture, not an equation.', task: 'Sketch both lines. Which plan is cheaper below 100 GB, and above it?', lookFor: 'Plan A cheaper below 100 GB (lower start), Plan B cheaper above (flatter slope).', nudge: 'Which line starts lower? Which one is steeper?' },
    ],
    stretch: 'Plan C costs ₹500 flat. For what usage is it the best of all three?',
    cliffhanger: 'Plan B now offers a discount that shrinks every month. Next class we meet expressions that aren’t straight lines — and find out if the deal is a trap.',
    win: 'I used equations and a graph to find the truly cheaper phone plan.',
    skill: 'Writing linear equations, solving simultaneous equations, and reading graphs.',
  },
  {
    subject: 'algebra-2', grade: 11, emoji: '🦠', title: 'The Outbreak Model', role: 'the public-health modeller',
    hook: 'A new flu is spreading through a city, and the health minister must decide today whether to close schools. She has asked for a model — by the end of the class.',
    mission: 'Model the spread with exponentials and logarithms.',
    chapters: [
      { minutes: 5, title: 'Doubling', scene: 'There are 50 cases today, and cases double every 3 days.', task: 'Write the number of cases after t days.', lookFor: 'C(t) = 50 × 2^(t/3).', nudge: 'After 3 days: 100. After 6 days: 200. What is the pattern?' },
      { minutes: 6, title: 'When do hospitals fill?', scene: 'Hospitals can handle 12,800 cases.', task: 'After how many days are they full?', lookFor: '12,800 / 50 = 256 = 2⁸, so t/3 = 8 → t = 24 days.', nudge: 'How many doublings get you from 50 to 12,800?' },
      { minutes: 6, title: 'Slow it down', scene: 'Closing schools makes cases double every 5 days instead.', task: 'How many extra days does that buy the hospitals? Use logarithms.', lookFor: 'Still 8 doublings: 40 days instead of 24 — 16 extra days. log₂(256) = 8.', nudge: 'The number of doublings stays the same. What changes is how long each takes.' },
    ],
    stretch: 'Real outbreaks slow down as people become immune. Sketch what the real curve might look like.',
    cliffhanger: 'The data from week two doesn’t fit the model — the curve is bending. Next class we meet logistic growth and find out when the outbreak peaks.',
    win: 'I modelled an outbreak with exponentials and logs and advised a minister.',
    skill: 'Exponential growth, logarithms, and modelling with functions.',
  },
  {
    subject: 'trigonometry', grade: 10, emoji: '🗼', title: 'The Lighthouse Keeper', role: 'the lighthouse keeper',
    hook: 'A storm is rolling in. A ship has lost its GPS near the rocks, and the only thing between it and disaster is the lighthouse — and the keeper who can do trigonometry. That is you.',
    mission: 'Use angles to find the ship and guide it to safety.',
    chapters: [
      { minutes: 5, title: 'How far out?', scene: 'The lamp is 60 m above the sea. You look down at the ship at an angle of depression of 30°.', task: 'How far is the ship from the base of the lighthouse?', lookFor: 'tan 30° = 60 / d → d = 60√3 ≈ 104 m.', nudge: 'Draw the right triangle. Which sides do you know and want? Which ratio links them?' },
      { minutes: 6, title: 'Moving closer', scene: 'Ten minutes later the angle of depression is 60°.', task: 'How far is it now, and how far did it travel?', lookFor: 'd = 60/√3 ≈ 34.6 m; it moved about 69 m.', nudge: 'Same triangle, new angle. Then subtract.' },
      { minutes: 6, title: 'The safe course', scene: 'Rocks lie 50 m east of the ship. It must turn so it passes at least 40 m from the rocks.', task: 'Sketch the situation. What trig would you use to find the turning angle?', lookFor: 'A right triangle with hypotenuse 50 and opposite side 40 → sin θ = 40/50, θ ≈ 53°.', nudge: 'Which ratio uses the opposite side and the hypotenuse?' },
    ],
    stretch: 'Prove that tan 60° = √3 using an equilateral triangle cut in half.',
    cliffhanger: 'The ship’s radio reports a second vessel — but the angle readings don’t form a right triangle. Next class we learn the sine and cosine rules for ANY triangle.',
    win: 'I used trigonometry to guide a ship past the rocks in a storm.',
    skill: 'Angles of elevation and depression, and the trigonometric ratios.',
  },
  {
    subject: 'calculus', grade: 12, emoji: '📦', title: 'The Perfect Box', role: 'the packaging engineer',
    hook: 'An online store wastes thousands on cardboard. They want the box that holds the most with the least material — and they have heard calculus can find it.',
    mission: 'Use derivatives to design the biggest box from one sheet of card.',
    chapters: [
      { minutes: 5, title: 'Build the formula', scene: 'A 30 cm × 30 cm card has an x cm square cut from each corner; the sides fold up.', task: 'Write the volume V(x) of the box.', lookFor: 'V = x(30 − 2x)².', nudge: 'After cutting, how long is each side of the base? How tall is the box?' },
      { minutes: 6, title: 'Find the maximum', scene: 'Cut too little and the box is flat; cut too much and there is no base.', task: 'Differentiate and find the x that gives the biggest volume.', lookFor: 'V′ = (30 − 2x)(30 − 6x) = 0 → x = 5 (x = 15 gives no box); V = 2,000 cm³.', nudge: 'The maximum is where the slope of V is zero.' },
      { minutes: 6, title: 'Prove it is a maximum', scene: 'The manager asks: “How do you know it isn’t the smallest?”', task: 'Use the second derivative (or a sign check) to prove it.', lookFor: 'V″(5) < 0 (or V′ changes from + to −), so x = 5 is a maximum.', nudge: 'Is the curve bending down or up at x = 5?' },
    ],
    stretch: 'Now the box needs a lid and a fixed volume of 1,000 cm³. What shape uses the least card?',
    cliffhanger: 'The store now ships cylinders too — and wants to know how fast a drum fills when water pours in. Next class we do related rates.',
    win: 'I used calculus to design the box with the biggest possible volume.',
    skill: 'Modelling with functions, derivatives for optimisation, and the second-derivative test.',
  },
  {
    subject: 'mechanics', grade: 11, emoji: '🚗', title: 'The Crash Investigator', role: 'the accident investigator',
    hook: 'Two cars have collided at a junction. Both drivers say the other was speeding. The skid marks, the masses and the physics are on your desk — the court needs your report.',
    mission: 'Reconstruct the crash with kinematics and conservation of momentum.',
    chapters: [
      { minutes: 5, title: 'The skid marks', scene: 'Car A skidded 20 m to a stop. Its deceleration on this road is 5 m/s².', task: 'How fast was it going when the brakes locked?', lookFor: 'v² = u² − 2as → 0 = u² − 200 → u ≈ 14.1 m/s (≈ 51 km/h).', nudge: 'Final speed is 0. Which equation of motion has no time in it?' },
      { minutes: 6, title: 'The collision', scene: 'Car A (1,000 kg, 14 m/s) hits stationary Car B (1,500 kg) and they move off together.', task: 'How fast do they move together just after the crash?', lookFor: 'Momentum conserved: 14,000 = 2,500v → v = 5.6 m/s.', nudge: 'Total momentum before equals total momentum after.' },
      { minutes: 6, title: 'The verdict', scene: 'The speed limit was 40 km/h.', task: 'Was Car A speeding? Write the one-line conclusion for the court, with its assumptions.', lookFor: 'Yes — about 51 km/h > 40 km/h, assuming constant deceleration and that it braked fully before impact.', nudge: 'Convert m/s to km/h (× 3.6). What did you assume along the way?' },
    ],
    stretch: 'How much kinetic energy was lost in the collision, and where did it go?',
    cliffhanger: 'A witness says Car B was rolling, not stopped — and at an angle. Next class we handle 2-D momentum with vectors.',
    win: 'I reconstructed a car crash with kinematics and momentum.',
    skill: 'Equations of motion, conservation of momentum, and stating modelling assumptions.',
  },
  {
    subject: 'organic-chemistry', grade: 12, emoji: '🍌', title: 'The Scent Chemist', role: 'the flavour and fragrance chemist',
    hook: 'A sweet company wants a banana flavour that doesn’t need any bananas. The secret is a molecule — and they want the chemist who can make it on paper today.',
    mission: 'Design the banana-flavour molecule and the reaction that makes it.',
    chapters: [
      { minutes: 5, title: 'Read the molecule', scene: 'Banana flavour is isopentyl acetate: CH₃COOCH₂CH₂CH(CH₃)₂.', task: 'Which functional group is it? What family of compounds smells fruity?', lookFor: 'An ester (–COO–); esters give fruity smells.', nudge: 'Find the C, the double-bonded O and the O between two carbons.' },
      { minutes: 6, title: 'Make it', scene: 'Esters are made from an acid and an alcohol.', task: 'Which acid and which alcohol make isopentyl acetate? Name the reaction and the catalyst.', lookFor: 'Ethanoic (acetic) acid + 3-methylbutan-1-ol, with concentrated H₂SO₄: esterification (condensation, water lost).', nudge: 'Split the ester at the C–O bond. One half came from an acid, one from an alcohol.' },
      { minutes: 6, title: 'Push the yield', scene: 'The reaction is reversible and stops at about 65% yield.', task: 'Suggest two ways to get more ester, explaining with equilibrium.', lookFor: 'Use excess of one reactant, or remove water/ester as it forms — Le Chatelier shifts the equilibrium right.', nudge: 'If you take a product away, which way does the equilibrium move?' },
    ],
    stretch: 'Swap the alcohol for methanol and the acid for salicylic acid. What smell do you get? (Wintergreen.)',
    cliffhanger: 'The company now wants the flavour to survive baking at 200°C. Next class we look at structure and boiling points — and which molecules can take the heat.',
    win: 'I designed a banana-flavour molecule and the reaction that makes it.',
    skill: 'Functional groups, esterification, and equilibrium in organic synthesis.',
  },
];
