import type { CodeChallenge } from '../types';

/**
 * SARIRO — Code Lab: the Python pack
 * ============================================================================
 * For Python Basics, and for the tracks that work in Python (data, agents,
 * automation, security). First programs are checked by what they print; after
 * that, functions are checked by what they return. Names follow Python style
 * (snake_case), and the tests show values the way Python writes them.
 */

type Py = Omit<CodeChallenge, 'lang'>;

const P: Py[] = [
  /* ── First programs ──────────────────────────────────────────────────── */
  {
    id: 'lab:py:hello', mode: 'program', tier: 1, topic: 'First programs', title: 'Hello, World!',
    prompt: 'Every programmer\'s first program. Make it print exactly:\n\n`Hello, World!`',
    starter: '# print() shows a line of text\n',
    solution: 'print("Hello, World!")\n',
    tests: [{ stdout: 'Hello, World!', visible: true }],
    hints: ['`print(...)` shows whatever is inside the brackets.', 'Text goes in quotes: `"Hello, World!"`.', 'Capital H, comma, space, capital W, exclamation mark.'],
  },
  {
    id: 'lab:py:about-me', mode: 'program', tier: 1, topic: 'First programs', title: 'Variables',
    prompt: 'The starter code stores a name and an age. Print them as two lines, using the variables:\n\n`My name is Asha`\n`I am 11 years old`',
    starter: 'name = "Asha"\nage = 11\n\n# print two lines using name and age\n',
    solution: 'name = "Asha"\nage = 11\n\nprint("My name is " + name)\nprint(f"I am {age} years old")\n',
    tests: [{ stdout: 'My name is Asha\nI am 11 years old', visible: true }],
    hints: ['Join text with `+`: `"My name is " + name`.', 'A number cannot be joined with `+` directly — use an f-string: `f"I am {age} years old"`.'],
  },
  {
    id: 'lab:py:countdown', mode: 'program', tier: 1, topic: 'First programs', title: 'Countdown',
    prompt: 'Print 5, 4, 3, 2, 1 on separate lines, then `Liftoff!` — use a loop.',
    starter: '',
    solution: 'for i in range(5, 0, -1):\n    print(i)\nprint("Liftoff!")\n',
    tests: [{ stdout: '5\n4\n3\n2\n1\nLiftoff!', visible: true }],
    hints: ['`range(5, 0, -1)` counts 5, 4, 3, 2, 1.', 'Indent the `print(i)` so it is inside the loop.', 'Print `Liftoff!` once, after the loop — not indented.'],
  },
  {
    id: 'lab:py:times-table', mode: 'program', tier: 1, topic: 'First programs', title: 'The 7 times table',
    prompt: 'Print the 7 times table from 1 to 10, like this:\n\n`7 x 1 = 7`\n`7 x 2 = 14`\n…\n`7 x 10 = 70`',
    starter: '',
    solution: 'for i in range(1, 11):\n    print(f"7 x {i} = {7 * i}")\n',
    tests: [{ stdout: Array.from({ length: 10 }, (_, i) => `7 x ${i + 1} = ${7 * (i + 1)}`).join('\n'), visible: true }],
    hints: ['`range(1, 11)` gives 1 up to 10.', 'An f-string builds the line: `f"7 x {i} = {7 * i}"`.'],
  },
  {
    id: 'lab:py:triangle', mode: 'program', tier: 2, topic: 'First programs', title: 'A triangle of stars',
    prompt: 'Print a triangle five rows tall — one star on the first row, five on the last:\n\n`*`\n`**`\n`***`\n`****`\n`*****`',
    starter: '',
    solution: 'for row in range(1, 6):\n    print("*" * row)\n',
    tests: [{ stdout: '*\n**\n***\n****\n*****', visible: true }],
    hints: ['Loop the rows from 1 to 5.', 'In Python, `"*" * 3` is `"***"`.'],
  },

  /* ── Functions ───────────────────────────────────────────────────────── */
  {
    id: 'lab:py:add', mode: 'function', tier: 1, topic: 'Functions', title: 'Add two numbers', fnName: 'add',
    prompt: 'Write `add(a, b)` that returns the sum of the two numbers.',
    starter: 'def add(a, b):\n    pass\n',
    solution: 'def add(a, b):\n    return a + b\n',
    tests: [{ args: [2, 3], expected: 5, visible: true }, { args: [-1, 1], expected: 0, visible: true }, { args: [0.5, 0.25], expected: 0.75 }, { args: [100, 250], expected: 350 }],
    hints: ['`return` sends a value back out of the function.', 'Replace `pass` with `return a + b`.'],
  },
  {
    id: 'lab:py:say-hello', mode: 'function', tier: 1, topic: 'Functions', title: 'Say hello', fnName: 'say_hello',
    prompt: 'Write `say_hello(name)` that returns a greeting: `say_hello("Ada")` gives `"Hello, Ada!"`.',
    starter: 'def say_hello(name):\n    pass\n',
    solution: 'def say_hello(name):\n    return f"Hello, {name}!"\n',
    tests: [{ args: ['Ada'], expected: 'Hello, Ada!', visible: true }, { args: ['Sam'], expected: 'Hello, Sam!' }, { args: [''], expected: 'Hello, !' }],
    hints: ['Return the text — do not print it.', 'An f-string: `f"Hello, {name}!"`.'],
  },
  {
    id: 'lab:py:is-even', mode: 'function', tier: 1, topic: 'Functions', title: 'Even or odd', fnName: 'is_even',
    prompt: 'Write `is_even(n)` that returns `True` when `n` is even and `False` when it is odd.',
    starter: 'def is_even(n):\n    pass\n',
    solution: 'def is_even(n):\n    return n % 2 == 0\n',
    tests: [{ args: [4], expected: true, visible: true }, { args: [7], expected: false, visible: true }, { args: [0], expected: true }, { args: [-3], expected: false }],
    hints: ['`%` gives the remainder after dividing.', 'An even number leaves remainder 0 when divided by 2: `n % 2 == 0`.'],
  },
  {
    id: 'lab:py:celsius', mode: 'function', tier: 1, topic: 'Functions', title: 'Celsius to Fahrenheit', fnName: 'to_fahrenheit',
    prompt: 'Write `to_fahrenheit(c)`: multiply by 9, divide by 5, add 32. `to_fahrenheit(100)` is `212`.',
    starter: 'def to_fahrenheit(c):\n    pass\n',
    solution: 'def to_fahrenheit(c):\n    return c * 9 / 5 + 32\n',
    tests: [{ args: [100], expected: 212, visible: true }, { args: [0], expected: 32, visible: true }, { args: [-40], expected: -40 }, { args: [37], expected: 98.6 }],
    hints: ['Return the result.', '`c * 9 / 5 + 32`'],
  },
  {
    id: 'lab:py:max-of-three', mode: 'function', tier: 1, topic: 'Conditions', title: 'Biggest of three', fnName: 'biggest',
    prompt: 'Write `biggest(a, b, c)` that returns the largest of the three numbers — using `if`, not `max()`.',
    starter: 'def biggest(a, b, c):\n    pass\n',
    solution: 'def biggest(a, b, c):\n    best = a\n    if b > best:\n        best = b\n    if c > best:\n        best = c\n    return best\n',
    tests: [{ args: [1, 9, 4], expected: 9, visible: true }, { args: [7, 2, 3], expected: 7, visible: true }, { args: [-5, -2, -9], expected: -2 }, { args: [3, 3, 3], expected: 3 }],
    hints: ['Start by assuming `a` is the biggest.', 'Then check `b`, then `c`, and swap in whichever is bigger.'],
  },
  {
    id: 'lab:py:grade', mode: 'function', tier: 2, topic: 'Conditions', title: 'Report card', fnName: 'grade',
    prompt: 'Write `grade(score)`: `"A"` for 90 and above, `"B"` for 75–89, `"C"` for 50–74, and `"F"` below 50.',
    starter: 'def grade(score):\n    pass\n',
    solution: 'def grade(score):\n    if score >= 90:\n        return "A"\n    if score >= 75:\n        return "B"\n    if score >= 50:\n        return "C"\n    return "F"\n',
    tests: [{ args: [95], expected: 'A', visible: true }, { args: [75], expected: 'B', visible: true }, { args: [74], expected: 'C' }, { args: [50], expected: 'C' }, { args: [49], expected: 'F' }, { args: [90], expected: 'A' }],
    hints: ['Check from the top grade down with `if` / `elif`.', 'Once you `return`, the function stops — so the order of the checks matters.'],
  },

  /* ── Strings ─────────────────────────────────────────────────────────── */
  {
    id: 'lab:py:shout', mode: 'function', tier: 1, topic: 'Strings', title: 'Shout it', fnName: 'shout',
    prompt: 'Write `shout(text)` that returns the text in capitals with `!` on the end: `shout("hi")` → `"HI!"`.',
    starter: 'def shout(text):\n    pass\n',
    solution: 'def shout(text):\n    return text.upper() + "!"\n',
    tests: [{ args: ['hi'], expected: 'HI!', visible: true }, { args: ['Sariro rocks'], expected: 'SARIRO ROCKS!' }, { args: [''], expected: '!' }],
    hints: ['Strings have a method that makes them capitals: `.upper()`.', 'Then add `"!"` with `+`.'],
  },
  {
    id: 'lab:py:reverse', mode: 'function', tier: 1, topic: 'Strings', title: 'Backwards', fnName: 'reverse',
    prompt: 'Write `reverse(text)` that returns the text backwards: `reverse("abc")` → `"cba"`.',
    starter: 'def reverse(text):\n    pass\n',
    solution: 'def reverse(text):\n    return text[::-1]\n',
    tests: [{ args: ['abc'], expected: 'cba', visible: true }, { args: [''], expected: '', visible: true }, { args: ['racecar'], expected: 'racecar' }, { args: ['Hello!'], expected: '!olleH' }],
    hints: ['Slicing takes parts of a string: `text[start:stop:step]`.', 'A step of -1 walks backwards: `text[::-1]`.'],
  },
  {
    id: 'lab:py:count-vowels', mode: 'function', tier: 2, topic: 'Strings', title: 'Count the vowels', fnName: 'count_vowels',
    prompt: 'Write `count_vowels(text)` that counts a, e, i, o and u — capitals too.',
    starter: 'def count_vowels(text):\n    pass\n',
    solution: 'def count_vowels(text):\n    return sum(1 for ch in text.lower() if ch in "aeiou")\n',
    tests: [{ args: ['hello'], expected: 2, visible: true }, { args: ['SKY'], expected: 0, visible: true }, { args: ['AEIOU aeiou'], expected: 10 }, { args: [''], expected: 0 }],
    hints: ['Loop over the letters: `for ch in text:`.', '`ch in "aeiou"` asks if a letter is a vowel. Use `.lower()` first so capitals count.'],
  },
  {
    id: 'lab:py:palindrome', mode: 'function', tier: 2, topic: 'Strings', title: 'Palindromes', fnName: 'is_palindrome',
    prompt: 'A palindrome reads the same both ways. Write `is_palindrome(text)`, ignoring capitals and spaces: `"Never odd or even"` is one.',
    starter: 'def is_palindrome(text):\n    pass\n',
    solution: 'def is_palindrome(text):\n    clean = text.lower().replace(" ", "")\n    return clean == clean[::-1]\n',
    tests: [{ args: ['racecar'], expected: true, visible: true }, { args: ['Never odd or even'], expected: true, visible: true }, { args: ['python'], expected: false }, { args: [''], expected: true }],
    hints: ['Clean it first: `.lower()` and `.replace(" ", "")`.', 'Then compare it with its reverse, `clean[::-1]`.'],
  },
  {
    id: 'lab:py:initials', mode: 'function', tier: 2, topic: 'Strings', title: 'Initials', fnName: 'initials',
    prompt: 'Write `initials(name)`: `initials("Ada Lovelace")` is `"A.L."`, and `initials("grace brewster hopper")` is `"G.B.H."` — always capitals.',
    starter: 'def initials(name):\n    pass\n',
    solution: 'def initials(name):\n    return "".join(word[0].upper() + "." for word in name.split())\n',
    tests: [{ args: ['Ada Lovelace'], expected: 'A.L.', visible: true }, { args: ['grace brewster hopper'], expected: 'G.B.H.', visible: true }, { args: ['Alan'], expected: 'A.' }, { args: ['  Tim   Berners  '], expected: 'T.B.' }],
    hints: ['`name.split()` breaks a name into words (and ignores extra spaces).', 'Take `word[0].upper()`, add a dot, and join them together.'],
  },
  {
    id: 'lab:py:title-case', mode: 'function', tier: 2, topic: 'Strings', title: 'Title Case', fnName: 'title_case',
    prompt: 'Write `title_case(text)` that capitalises the first letter of every word and makes the rest lower case: `"hello wORLD"` → `"Hello World"`. Words are separated by single spaces.',
    starter: 'def title_case(text):\n    pass\n',
    solution: 'def title_case(text):\n    return " ".join(w[:1].upper() + w[1:].lower() for w in text.split(" "))\n',
    tests: [{ args: ['hello wORLD'], expected: 'Hello World', visible: true }, { args: [''], expected: '', visible: true }, { args: ['sARIRO'], expected: 'Sariro' }, { args: ['a b c'], expected: 'A B C' }],
    hints: ['Split into words, change each word, join them back with spaces.', 'First letter: `w[:1].upper()`; the rest: `w[1:].lower()`.'],
  },
  {
    id: 'lab:py:caesar', mode: 'function', tier: 3, topic: 'Strings', title: 'Caesar cipher', fnName: 'caesar',
    prompt: 'Write `caesar(text, shift)` that moves every letter `shift` places along the alphabet, wrapping from z to a. Keep capitals capital; leave everything else alone. `caesar("abc xyz", 3)` → `"def abc"`.',
    starter: 'def caesar(text, shift):\n    pass\n',
    solution: 'def caesar(text, shift):\n    out = ""\n    for ch in text:\n        if ch.isalpha() and ch.isascii():\n            base = ord("A") if ch.isupper() else ord("a")\n            out += chr((ord(ch) - base + shift) % 26 + base)\n        else:\n            out += ch\n    return out\n',
    tests: [{ args: ['abc xyz', 3], expected: 'def abc', visible: true }, { args: ['Hello, World!', 1], expected: 'Ifmmp, Xpsme!', visible: true }, { args: ['def', -3], expected: 'abc' }, { args: ['Zz', 27], expected: 'Aa' }],
    hints: ['`ord("a")` is 97 and `chr(97)` is `"a"`.', 'Take away the base, add the shift, wrap with `% 26`, add the base back.', 'In Python, `%` of a negative number still wraps correctly.'],
  },
  {
    id: 'lab:py:compress', mode: 'function', tier: 3, topic: 'Strings', title: 'Squash repeats', fnName: 'compress',
    prompt: 'Write `compress(text)` that writes each run of the same letter as the letter and how many: `"aaabcc"` → `"a3b1c2"`.',
    starter: 'def compress(text):\n    pass\n',
    solution: 'def compress(text):\n    out = ""\n    i = 0\n    while i < len(text):\n        j = i\n        while j < len(text) and text[j] == text[i]:\n            j += 1\n        out += text[i] + str(j - i)\n        i = j\n    return out\n',
    tests: [{ args: ['aaabcc'], expected: 'a3b1c2', visible: true }, { args: [''], expected: '', visible: true }, { args: ['z'], expected: 'z1' }, { args: ['aabbaa'], expected: 'a2b2a2' }],
    hints: ['Walk along the text and count how long each run of one letter lasts.', 'When the letter changes, write the letter and its count, and start counting again.'],
  },

  /* ── Lists ───────────────────────────────────────────────────────────── */
  {
    id: 'lab:py:total', mode: 'function', tier: 1, topic: 'Lists', title: 'Add them all', fnName: 'total',
    prompt: 'Write `total(nums)` that adds up every number in the list — with a loop, not `sum()`.',
    starter: 'def total(nums):\n    pass\n',
    solution: 'def total(nums):\n    result = 0\n    for n in nums:\n        result += n\n    return result\n',
    tests: [{ args: [[1, 2, 3]], expected: 6, visible: true }, { args: [[]], expected: 0, visible: true }, { args: [[-5, 5, 10]], expected: 10 }],
    hints: ['Start a running total at 0.', 'Loop `for n in nums:` and add each one on.'],
  },
  {
    id: 'lab:py:evens', mode: 'function', tier: 1, topic: 'Lists', title: 'Only the evens', fnName: 'evens',
    prompt: 'Write `evens(nums)` that returns a new list with only the even numbers, in the same order.',
    starter: 'def evens(nums):\n    pass\n',
    solution: 'def evens(nums):\n    return [n for n in nums if n % 2 == 0]\n',
    tests: [{ args: [[1, 2, 3, 4]], expected: [2, 4], visible: true }, { args: [[]], expected: [], visible: true }, { args: [[7, 9]], expected: [] }, { args: [[-2, 0, 5, 10]], expected: [-2, 0, 10] }],
    hints: ['Make an empty list and `.append()` each even number.', 'Or in one line: `[n for n in nums if n % 2 == 0]`.'],
  },
  {
    id: 'lab:py:largest', mode: 'function', tier: 2, topic: 'Lists', title: 'The largest number', fnName: 'largest',
    prompt: 'Write `largest(nums)` that returns the biggest number in a non-empty list — without `max()`.',
    starter: 'def largest(nums):\n    pass\n',
    solution: 'def largest(nums):\n    best = nums[0]\n    for n in nums:\n        if n > best:\n            best = n\n    return best\n',
    tests: [{ args: [[3, 9, 2]], expected: 9, visible: true }, { args: [[-7, -3, -10]], expected: -3, visible: true }, { args: [[5]], expected: 5 }],
    hints: ['Start with the first number as the best so far.', 'Walk the list; keep any number bigger than the best.'],
  },
  {
    id: 'lab:py:average', mode: 'function', tier: 2, topic: 'Lists', title: 'The average', fnName: 'average',
    prompt: 'Write `average(nums)` that returns the mean of the list, rounded to 2 decimal places. An empty list has an average of `0`.',
    starter: 'def average(nums):\n    pass\n',
    solution: 'def average(nums):\n    if not nums:\n        return 0\n    return round(sum(nums) / len(nums), 2)\n',
    tests: [{ args: [[1, 2, 3, 4]], expected: 2.5, visible: true }, { args: [[]], expected: 0, visible: true }, { args: [[1, 2]], expected: 1.5 }, { args: [[1, 1, 2]], expected: 1.33 }],
    hints: ['Mean = total ÷ how many: `sum(nums) / len(nums)`.', 'Dividing by zero crashes — handle the empty list first.', '`round(x, 2)` rounds to 2 places.'],
  },
  {
    id: 'lab:py:unique', mode: 'function', tier: 2, topic: 'Lists', title: 'No repeats', fnName: 'unique',
    prompt: 'Write `unique(items)` that removes repeats but keeps the first of each, in order: `[3, 1, 3, 2, 1]` → `[3, 1, 2]`.',
    starter: 'def unique(items):\n    pass\n',
    solution: 'def unique(items):\n    seen = []\n    for x in items:\n        if x not in seen:\n            seen.append(x)\n    return seen\n',
    tests: [{ args: [[3, 1, 3, 2, 1]], expected: [3, 1, 2], visible: true }, { args: [[]], expected: [], visible: true }, { args: [['a', 'a', 'a']], expected: ['a'] }],
    hints: ['Build a new list, adding each item only if it is not in there yet.', '`if x not in seen:`'],
  },
  {
    id: 'lab:py:flatten', mode: 'function', tier: 2, topic: 'Lists', title: 'Flatten', fnName: 'flatten',
    prompt: 'Write `flatten(lists)` that joins a list of lists into one list: `[[1, 2], [3], []]` → `[1, 2, 3]`.',
    starter: 'def flatten(lists):\n    pass\n',
    solution: 'def flatten(lists):\n    out = []\n    for inner in lists:\n        for x in inner:\n            out.append(x)\n    return out\n',
    tests: [{ args: [[[1, 2], [3], []]], expected: [1, 2, 3], visible: true }, { args: [[]], expected: [], visible: true }, { args: [[['a'], ['b', 'c']]], expected: ['a', 'b', 'c'] }],
    hints: ['A loop inside a loop.', 'Append every item of every inner list to one result list — or use `.extend(inner)`.'],
  },
  {
    id: 'lab:py:second-largest', mode: 'function', tier: 3, topic: 'Lists', title: 'Runner-up', fnName: 'second_largest',
    prompt: 'Write `second_largest(nums)` — the second-biggest DIFFERENT number. `[5, 9, 9, 2]` → `5`. If there is no second one, return `None`.',
    starter: 'def second_largest(nums):\n    pass\n',
    solution: 'def second_largest(nums):\n    values = sorted(set(nums), reverse=True)\n    return values[1] if len(values) > 1 else None\n',
    tests: [{ args: [[5, 9, 9, 2]], expected: 5, visible: true }, { args: [[4, 4]], expected: null, visible: true }, { args: [[1, 2, 3]], expected: 2 }, { args: [[-1, -5]], expected: -5 }],
    hints: ['`set(nums)` drops the repeats.', 'Sort biggest first with `sorted(..., reverse=True)` and take index 1 — if there is one.'],
  },
  {
    id: 'lab:py:rotate', mode: 'function', tier: 3, topic: 'Lists', title: 'Rotate', fnName: 'rotate',
    prompt: 'Write `rotate(items, k)` that moves every item `k` places to the right, wrapping around: `rotate([1, 2, 3, 4, 5], 2)` → `[4, 5, 1, 2, 3]`. `k` can be bigger than the list.',
    starter: 'def rotate(items, k):\n    pass\n',
    solution: 'def rotate(items, k):\n    if not items:\n        return []\n    k = k % len(items)\n    return items[-k:] + items[:-k] if k else list(items)\n',
    tests: [{ args: [[1, 2, 3, 4, 5], 2], expected: [4, 5, 1, 2, 3], visible: true }, { args: [[1, 2, 3], 0], expected: [1, 2, 3], visible: true }, { args: [[1, 2, 3], 4], expected: [3, 1, 2] }, { args: [[], 3], expected: [] }],
    hints: ['Rotating by the length changes nothing — use `k % len(items)`.', 'The last `k` items go to the front: `items[-k:] + items[:-k]`.', 'Careful when `k` is 0: `items[-0:]` is the whole list.'],
  },

  /* ── Dictionaries ────────────────────────────────────────────────────── */
  {
    id: 'lab:py:word-count', mode: 'function', tier: 3, topic: 'Dictionaries', title: 'Count the words', fnName: 'word_count',
    prompt: 'Write `word_count(text)` that returns a dictionary of how often each word appears, in lower case: `"the cat the"` → `{"the": 2, "cat": 1}`.',
    starter: 'def word_count(text):\n    pass\n',
    solution: 'def word_count(text):\n    counts = {}\n    for word in text.lower().split():\n        counts[word] = counts.get(word, 0) + 1\n    return counts\n',
    tests: [{ args: ['the cat the'], expected: { the: 2, cat: 1 }, visible: true }, { args: [''], expected: {}, visible: true }, { args: ['Go go GO'], expected: { go: 3 } }],
    hints: ['Start with an empty dictionary `{}`.', '`counts.get(word, 0)` gives the count so far, or 0 for a new word.'],
  },
  {
    id: 'lab:py:top-scorer', mode: 'function', tier: 2, topic: 'Dictionaries', title: 'Top scorer', fnName: 'top_scorer',
    prompt: 'Scores are a dictionary like `{"Asha": 82, "Kabir": 95}`. Write `top_scorer(scores)` that returns the name with the highest score.',
    starter: 'def top_scorer(scores):\n    pass\n',
    solution: 'def top_scorer(scores):\n    best = None\n    for name, score in scores.items():\n        if best is None or score > scores[best]:\n            best = name\n    return best\n',
    tests: [{ args: [{ Asha: 82, Kabir: 95 }], expected: 'Kabir', visible: true }, { args: [{ Mia: 70 }], expected: 'Mia', visible: true }, { args: [{ a: 1, b: 3, c: 2 }], expected: 'b' }],
    hints: ['`for name, score in scores.items():` walks every pair.', 'Keep the name with the best score so far.'],
  },
  {
    id: 'lab:py:invert', mode: 'function', tier: 2, topic: 'Dictionaries', title: 'Swap keys and values', fnName: 'invert',
    prompt: 'Write `invert(d)` that swaps every key with its value: `{"a": "x", "b": "y"}` → `{"x": "a", "y": "b"}`.',
    starter: 'def invert(d):\n    pass\n',
    solution: 'def invert(d):\n    return {value: key for key, value in d.items()}\n',
    tests: [{ args: [{ a: 'x', b: 'y' }], expected: { x: 'a', y: 'b' }, visible: true }, { args: [{}], expected: {}, visible: true }, { args: [{ cat: 'meow' }], expected: { meow: 'cat' } }],
    hints: ['Build a new dictionary.', 'For every `key, value` pair, set `new[value] = key`.'],
  },

  /* ── Algorithms ──────────────────────────────────────────────────────── */
  {
    id: 'lab:py:fizzbuzz', mode: 'function', tier: 2, topic: 'Algorithms', title: 'FizzBuzz', fnName: 'fizzbuzz',
    prompt: 'Write `fizzbuzz(n)` that returns a list for 1 to n: `"Fizz"` for multiples of 3, `"Buzz"` for multiples of 5, `"FizzBuzz"` for both, otherwise the number as text.',
    starter: 'def fizzbuzz(n):\n    pass\n',
    solution: 'def fizzbuzz(n):\n    out = []\n    for i in range(1, n + 1):\n        if i % 15 == 0:\n            out.append("FizzBuzz")\n        elif i % 3 == 0:\n            out.append("Fizz")\n        elif i % 5 == 0:\n            out.append("Buzz")\n        else:\n            out.append(str(i))\n    return out\n',
    tests: [{ args: [5], expected: ['1', '2', 'Fizz', '4', 'Buzz'], visible: true }, { args: [15], expected: ['1', '2', 'Fizz', '4', 'Buzz', 'Fizz', '7', '8', 'Fizz', 'Buzz', '11', 'Fizz', '13', '14', 'FizzBuzz'] }, { args: [0], expected: [] }],
    hints: ['Check "both" first — a multiple of 15 is a multiple of 3 and of 5.', 'Numbers go in as text: `str(i)`.'],
  },
  {
    id: 'lab:py:is-prime', mode: 'function', tier: 2, topic: 'Algorithms', title: 'Prime or not', fnName: 'is_prime',
    prompt: 'Write `is_prime(n)`: `True` if n is a prime number (it has exactly two factors, 1 and itself).',
    starter: 'def is_prime(n):\n    pass\n',
    solution: 'def is_prime(n):\n    if n < 2:\n        return False\n    d = 2\n    while d * d <= n:\n        if n % d == 0:\n            return False\n        d += 1\n    return True\n',
    tests: [{ args: [7], expected: true, visible: true }, { args: [1], expected: false, visible: true }, { args: [2], expected: true }, { args: [9], expected: false }, { args: [97], expected: true }, { args: [100], expected: false }],
    hints: ['Numbers below 2 are not prime.', 'Try dividing by 2, 3, 4… — only up to the square root is needed.'],
  },
  {
    id: 'lab:py:fibonacci', mode: 'function', tier: 2, topic: 'Algorithms', title: 'Fibonacci', fnName: 'fibonacci',
    prompt: 'Write `fibonacci(n)` that returns the first n Fibonacci numbers: each is the sum of the two before. `fibonacci(7)` → `[0, 1, 1, 2, 3, 5, 8]`.',
    starter: 'def fibonacci(n):\n    pass\n',
    solution: 'def fibonacci(n):\n    out = []\n    a, b = 0, 1\n    for _ in range(n):\n        out.append(a)\n        a, b = b, a + b\n    return out\n',
    tests: [{ args: [7], expected: [0, 1, 1, 2, 3, 5, 8], visible: true }, { args: [0], expected: [], visible: true }, { args: [1], expected: [0] }, { args: [10], expected: [0, 1, 1, 2, 3, 5, 8, 13, 21, 34] }],
    hints: ['Keep the last two numbers in `a` and `b`.', '`a, b = b, a + b` moves both along one step.'],
  },
  {
    id: 'lab:py:factorial', mode: 'function', tier: 2, topic: 'Algorithms', title: 'Factorial', fnName: 'factorial',
    prompt: 'Write `factorial(n)`: 1 × 2 × … × n. `factorial(5)` is `120`, and `factorial(0)` is `1`.',
    starter: 'def factorial(n):\n    pass\n',
    solution: 'def factorial(n):\n    result = 1\n    for i in range(2, n + 1):\n        result *= i\n    return result\n',
    tests: [{ args: [5], expected: 120, visible: true }, { args: [0], expected: 1, visible: true }, { args: [1], expected: 1 }, { args: [10], expected: 3628800 }],
    hints: ['Start the answer at 1 (not 0 — why?).', 'Multiply by every number from 2 up to n.'],
  },
  {
    id: 'lab:py:digit-sum', mode: 'function', tier: 1, topic: 'Algorithms', title: 'Add the digits', fnName: 'digit_sum',
    prompt: 'Write `digit_sum(n)` that adds up the digits of a whole number: `digit_sum(4096)` is `19`.',
    starter: 'def digit_sum(n):\n    pass\n',
    solution: 'def digit_sum(n):\n    return sum(int(d) for d in str(abs(n)))\n',
    tests: [{ args: [4096], expected: 19, visible: true }, { args: [0], expected: 0, visible: true }, { args: [7], expected: 7 }, { args: [-123], expected: 6 }],
    hints: ['Turn the number into text with `str(n)` and loop over its characters.', 'Turn each character back into a number with `int(d)`. Negative numbers: use `abs(n)`.'],
  },
  {
    id: 'lab:py:gcd', mode: 'function', tier: 3, topic: 'Algorithms', title: 'Greatest common divisor', fnName: 'gcd',
    prompt: 'Write `gcd(a, b)` — the biggest number that divides both. Use Euclid\'s trick: `gcd(a, b)` is the same as `gcd(b, a % b)`, until b is 0.',
    starter: 'def gcd(a, b):\n    pass\n',
    solution: 'def gcd(a, b):\n    while b:\n        a, b = b, a % b\n    return a\n',
    tests: [{ args: [12, 18], expected: 6, visible: true }, { args: [7, 5], expected: 1, visible: true }, { args: [100, 75], expected: 25 }, { args: [9, 0], expected: 9 }],
    hints: ['Loop while `b` is not zero.', 'Each time round: `a, b = b, a % b`. When b hits 0, a is the answer.'],
  },
  {
    id: 'lab:py:binary-search', mode: 'function', tier: 3, topic: 'Algorithms', title: 'Binary search', fnName: 'binary_search',
    prompt: 'The list is sorted. Write `binary_search(nums, target)` that returns the index of `target`, or `-1` if it is not there — by halving the search each step, not by checking every item.',
    starter: 'def binary_search(nums, target):\n    pass\n',
    solution: 'def binary_search(nums, target):\n    lo, hi = 0, len(nums) - 1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if nums[mid] == target:\n            return mid\n        if nums[mid] < target:\n            lo = mid + 1\n        else:\n            hi = mid - 1\n    return -1\n',
    tests: [{ args: [[1, 3, 5, 7, 9], 7], expected: 3, visible: true }, { args: [[1, 3, 5], 4], expected: -1, visible: true }, { args: [[], 1], expected: -1 }, { args: [[2], 2], expected: 0 }, { args: [[1, 2, 3, 4, 5, 6, 7, 8], 1], expected: 0 }],
    hints: ['Keep a low and a high index; look at the middle.', 'If the middle is too small, the target must be to the right: `lo = mid + 1`.', '`//` divides and rounds down.'],
  },
  {
    id: 'lab:py:bubble-sort', mode: 'function', tier: 3, topic: 'Algorithms', title: 'Sort it yourself', fnName: 'bubble_sort',
    prompt: 'Write `bubble_sort(nums)` that returns the numbers smallest first — without `sorted()` or `.sort()`. Walk the list swapping neighbours that are the wrong way round, again and again until nothing swaps.',
    starter: 'def bubble_sort(nums):\n    items = list(nums)\n    # your code here\n    return items\n',
    solution: 'def bubble_sort(nums):\n    items = list(nums)\n    swapped = True\n    while swapped:\n        swapped = False\n        for i in range(len(items) - 1):\n            if items[i] > items[i + 1]:\n                items[i], items[i + 1] = items[i + 1], items[i]\n                swapped = True\n    return items\n',
    tests: [{ args: [[5, 2, 9, 1]], expected: [1, 2, 5, 9], visible: true }, { args: [[]], expected: [], visible: true }, { args: [[3, 3, 1]], expected: [1, 3, 3] }, { args: [[-1, -5, 0]], expected: [-5, -1, 0] }],
    hints: ['Compare `items[i]` with `items[i + 1]` for every i.', 'Swap in one line: `items[i], items[i + 1] = items[i + 1], items[i]`.', 'Repeat the whole walk until a pass makes no swaps.'],
  },
  {
    id: 'lab:py:anagram', mode: 'function', tier: 2, topic: 'Algorithms', title: 'Anagrams', fnName: 'is_anagram',
    prompt: 'Two words are anagrams if they use exactly the same letters: "listen" and "silent". Write `is_anagram(a, b)`, ignoring capitals and spaces.',
    starter: 'def is_anagram(a, b):\n    pass\n',
    solution: 'def is_anagram(a, b):\n    clean = lambda s: sorted(s.lower().replace(" ", ""))\n    return clean(a) == clean(b)\n',
    tests: [{ args: ['listen', 'silent'], expected: true, visible: true }, { args: ['cat', 'car'], expected: false, visible: true }, { args: ['Dormitory', 'dirty room'], expected: true }, { args: ['aab', 'abb'], expected: false }],
    hints: ['Sorting the letters of both words makes anagrams look identical.', 'Clean first: lower case, no spaces.'],
  },
  {
    id: 'lab:py:two-sum', mode: 'function', tier: 4, topic: 'Algorithms', title: 'Two sum', fnName: 'two_sum',
    prompt: 'Write `two_sum(nums, target)` that returns the indexes `[i, j]` (i < j) of the two numbers adding up to `target`. There is exactly one answer. One pass with a dictionary is enough.',
    starter: 'def two_sum(nums, target):\n    pass\n',
    solution: 'def two_sum(nums, target):\n    seen = {}\n    for j, n in enumerate(nums):\n        if target - n in seen:\n            return [seen[target - n], j]\n        seen[n] = j\n    return []\n',
    tests: [{ args: [[2, 7, 11, 15], 9], expected: [0, 1], visible: true }, { args: [[3, 2, 4], 6], expected: [1, 2], visible: true }, { args: [[3, 3], 6], expected: [0, 1] }, { args: [[1, 5, 9, 14], 23], expected: [2, 3] }],
    hints: ['For each number, the partner you need is `target - n`.', 'Remember every number you have passed, and where, in a dictionary.'],
  },
  {
    id: 'lab:py:brackets', mode: 'function', tier: 4, topic: 'Algorithms', title: 'Balanced brackets', fnName: 'balanced',
    prompt: 'Write `balanced(text)` — `True` if every `(`, `[` and `{` is closed by the matching bracket in the right order. Other characters are ignored.',
    starter: 'def balanced(text):\n    pass\n',
    solution: 'def balanced(text):\n    pairs = {")": "(", "]": "[", "}": "{"}\n    stack = []\n    for ch in text:\n        if ch in "([{":\n            stack.append(ch)\n        elif ch in pairs:\n            if not stack or stack.pop() != pairs[ch]:\n                return False\n    return not stack\n',
    tests: [{ args: ['(a[b]{c})'], expected: true, visible: true }, { args: ['(]'], expected: false, visible: true }, { args: [''], expected: true }, { args: ['(()'], expected: false }, { args: [')('], expected: false }],
    hints: ['Use a list as a stack: append openers, pop on closers.', 'A closer must match the opener you pop — and there must be one to pop.'],
  },

  /* ── Data and security ───────────────────────────────────────────────── */
  {
    id: 'lab:py:median', mode: 'function', tier: 3, topic: 'Data', title: 'The median', fnName: 'median',
    prompt: 'Write `median(nums)` — the middle value once sorted. With an even count, it is the average of the middle two. `median([3, 1, 2])` → `2`; `median([4, 1, 3, 2])` → `2.5`.',
    starter: 'def median(nums):\n    pass\n',
    solution: 'def median(nums):\n    s = sorted(nums)\n    mid = len(s) // 2\n    if len(s) % 2:\n        return s[mid]\n    return (s[mid - 1] + s[mid]) / 2\n',
    tests: [{ args: [[3, 1, 2]], expected: 2, visible: true }, { args: [[4, 1, 3, 2]], expected: 2.5, visible: true }, { args: [[7]], expected: 7 }, { args: [[10, 2, 38, 23, 38, 23, 21]], expected: 23 }],
    hints: ['Sort first: `sorted(nums)`.', 'The middle index is `len(s) // 2`. With an even count, average the two either side of the middle.'],
  },
  {
    id: 'lab:py:strong-password', mode: 'function', tier: 3, topic: 'Security', title: 'Strong password?', fnName: 'is_strong',
    prompt: 'Write `is_strong(password)`: `True` when it has at least 8 characters, a capital letter, a small letter and a digit.',
    starter: 'def is_strong(password):\n    pass\n',
    solution: 'def is_strong(password):\n    return (\n        len(password) >= 8\n        and any(c.isupper() for c in password)\n        and any(c.islower() for c in password)\n        and any(c.isdigit() for c in password)\n    )\n',
    tests: [{ args: ['Sariro2026'], expected: true, visible: true }, { args: ['password'], expected: false, visible: true }, { args: ['Short1A'], expected: false }, { args: ['ALLCAPS123'], expected: false }, { args: ['lower12345x'], expected: false }],
    hints: ['Check each rule separately, then combine them with `and`.', '`any(c.isdigit() for c in password)` asks "is there a digit anywhere?"'],
  },
  {
    id: 'lab:py:mask-email', mode: 'function', tier: 2, topic: 'Security', title: 'Hide an email', fnName: 'mask_email',
    prompt: 'Write `mask_email(email)` that keeps the first letter of the name, hides the rest with `*`, and keeps the domain: `"ada@example.com"` → `"a**@example.com"`.',
    starter: 'def mask_email(email):\n    pass\n',
    solution: 'def mask_email(email):\n    name, domain = email.split("@")\n    return name[0] + "*" * (len(name) - 1) + "@" + domain\n',
    tests: [{ args: ['ada@example.com'], expected: 'a**@example.com', visible: true }, { args: ['k@sariro.com'], expected: 'k@sariro.com', visible: true }, { args: ['kabir.dev@mail.in'], expected: 'k********@mail.in' }],
    hints: ['`email.split("@")` gives the name and the domain.', '`"*" * 3` is `"***"`.'],
  },
];

export const PYTHON: CodeChallenge[] = P.map((c) => ({ ...c, lang: 'python' }));
